CREATE TABLE [dbo].[AlphaTickets] (
    [WO_NUM]                      INT            NOT NULL,
    [TASK]                        VARCHAR (100)  NULL,
    [TYPE]                        VARCHAR (30)   NULL,
    [REQUEST]                     VARCHAR (50)   NULL,
    [REQDATE]                     DATETIME       NULL,
    [OPENBY]                      VARCHAR (255)  NULL,
    [OPENDATE]                    DATETIME       NULL,
    [MODIBY]                      VARCHAR (255)  NULL,
    [MODIDATE]                    DATETIME       NULL,
    [CLSDBY]                      VARCHAR (255)  NULL,
    [CLSDDATE]                    DATETIME       NULL,
    [ELAPSETIME]                  VARCHAR (20)   NULL,
    [ELAPSEMIN]                   INT            NULL,
    [PRIORITY]                    VARCHAR (30)   NULL,
    [DUEDATE]                     DATETIME       NULL,
    [RESPONS]                     VARCHAR (30)   NULL,
    [ASSNDATE]                    DATETIME       NULL,
    [COMPLETED]                   DATETIME       NULL,
    [HOURS]                       FLOAT (53)     NULL,
    [RATE]                        FLOAT (53)     NULL,
    [CHARGE]                      FLOAT (53)     NULL,
    [WS_NUM]                      INT            NULL,
    [DEPT_NUM]                    VARCHAR (30)   NULL,
    [DEPT]                        VARCHAR (30)   NULL,
    [PHONE]                       VARCHAR (30)   NULL,
    [PHONE_EXT]                   VARCHAR (8)    NULL,
    [LOCATION]                    VARCHAR (30)   NULL,
    [DESCRIPT]                    TEXT           NULL,
    [WO_TEXT1]                    VARCHAR (40)   NULL,
    [WO_TEXT2]                    VARCHAR (40)   NULL,
    [WO_TEXT3]                    VARCHAR (40)   NULL,
    [WO_TEXT4]                    VARCHAR (40)   NULL,
    [WO_TEXT5]                    VARCHAR (40)   NULL,
    [WO_TEXT6]                    VARCHAR (40)   NULL,
    [WO_DATE1]                    DATETIME       NULL,
    [WO_DATE2]                    DATETIME       NULL,
    [WO_NUM1]                     FLOAT (53)     NULL,
    [WO_INT1]                     INT            NULL,
    [NOTE]                        TEXT           NULL,
    [FT]                          BIT            NULL,
    [COMPFLAG]                    VARCHAR (30)   NULL,
    [STATUS]                      VARCHAR (25)   NULL,
    [AGENTDATE]                   DATETIME       NULL,
    [AGENTLEVEL]                  TINYINT        NULL,
    [AWS_NUM]                     VARCHAR (40)   NULL,
    [LOOKUP1]                     VARCHAR (30)   NULL,
    [LOOKUP2]                     VARCHAR (30)   NULL,
    [GUIDO]                       VARCHAR (40)   NULL,
    [EMAILADDR]                   VARCHAR (1024) NULL,
    [USERID]                      INT            NULL,
    [PARENTWOID]                  INT            NULL,
    [WOID]                        INT            NOT NULL,
    [WOTYPE2]                     VARCHAR (30)   NULL,
    [WOTYPE3]                     VARCHAR (30)   NULL,
    [ATTACHCOUNT]                 INT            NULL,
    [AGENTLEVELREQ]               TINYINT        NULL,
    [AGENTDATEREQ]                DATETIME       NULL,
    [WorkOrderTypeId]             INT            NOT NULL,
    [WorkOrderStatusId]           INT            NULL,
    [AssignmentNumber]            INT            NULL,
    [PolicyDueDate]               DATETIME       NULL,
    [SLAKEY]                      INT            NULL,
    [SLANAME]                     VARCHAR (30)   NULL,
    [PolicyComponentName]         VARCHAR (255)  NULL,
    [PolicyComponentId]           INT            NULL,
    [PolicyPendingDueAlarmDate]   DATETIME       NULL,
    [PolicyOverdueAlarmDate]      DATETIME       NULL,
    [ExpComplOverdueAlarmDate]    DATETIME       NULL,
    [ExpComplPendingDueAlarmDate] DATETIME       NULL,
    [TaskLookup3]                 VARCHAR (30)   NULL,
    [TaskLookup4]                 VARCHAR (30)   NULL,
    [TaskLookup5]                 VARCHAR (30)   NULL,
    [TaskLookup6]                 VARCHAR (30)   NULL,
    [TaskLookup7]                 VARCHAR (30)   NULL,
    [TaskLookup8]                 VARCHAR (30)   NULL,
    [WO_DATE3]                    DATETIME       NULL,
    [WO_DATE4]                    DATETIME       NULL,
    [SessionId]                   INT            NULL,
    [WorkOrderTemplateName]       VARCHAR (255)  NULL,
    [NotificationFromAddress]     VARCHAR (1024) NULL,
    CONSTRAINT [PK_AlphaTickets] PRIMARY KEY CLUSTERED ([WO_NUM] ASC)
);


GO
GRANT SELECT
    ON OBJECT::[dbo].[AlphaTickets] TO [CANDY\HAlfaro]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[AlphaTickets] TO [CANDY\TChen]
    AS [dbo];

