CREATE TABLE [dbo].[AUDIT_SFDC_CONTACT] (
    [Created]  DATETIME     CONSTRAINT [DF_AUDIT_SFDC_CONTACT_Created] DEFAULT (getdate()) NULL,
    [Id]       VARCHAR (50) NOT NULL,
    [PersonId] INT          NULL,
    CONSTRAINT [PK_AUDIT_SFDC_CONTACT] PRIMARY KEY CLUSTERED ([Id] ASC)
);

