CREATE TABLE [dbo].[B_SFDC_OPPORTUNITY] (
    [ID]                       VARCHAR (25)  NOT NULL,
    [CLOSEDATE]                VARCHAR (50)  NULL,
    [ISCLOSED]                 VARCHAR (50)  NOT NULL,
    [CLOUD_TCV__C]             VARCHAR (50)  NULL,
    [NAME]                     VARCHAR (255) NULL,
    [OWNERROLE]                VARCHAR (50)  NULL,
    [STAGENAME]                VARCHAR (50)  NULL,
    [OWNERFULL_NAME__C]        VARCHAR (200) NULL,
    [AccountId]                VARCHAR (25)  NULL,
    [HeritageId]               VARCHAR (25)  NULL,
    [PrimaryPartner]           VARCHAR (255) NULL,
    [PrimaryDistributor]       VARCHAR (255) NULL,
    [SubAgent]                 VARCHAR (255) NULL,
    [OppType]                  VARCHAR (50)  NULL,
    [DealType]                 VARCHAR (50)  NULL,
    [ProductSuiteCategory]     VARCHAR (255) NULL,
    [Territory]                VARCHAR (50)  NULL,
    [ProductInterest]          VARCHAR (255) NULL,
    [BookingAmount]            FLOAT (53)    NULL,
    [RevenueAmount]            FLOAT (53)    NULL,
    [ForecastCategory]         VARCHAR (100) NULL,
    [Region]                   VARCHAR (100) NULL,
    [SubRegion]                VARCHAR (100) NULL,
    [LeadSource]               VARCHAR (100) NULL,
    [LeadSourceDescription]    VARCHAR (255) NULL,
    [RecordType]               VARCHAR (100) NULL,
    [CreatedDate]              VARCHAR (200) NULL,
    [DealId]                   VARCHAR (255) NULL,
    [Theatre]                  VARCHAR (255) NULL,
    [AccountName]              VARCHAR (500) NULL,
    [Competitors]              VARCHAR (500) NULL,
    [OwnerId]                  VARCHAR (25)  NULL,
    [ISRRegion]                VARCHAR (255) NULL,
    [BizibleOpportunityAmount] FLOAT (53)    NULL,
    [ForecastRegion]           VARCHAR (50)  NULL,
    [ForecastSubRegion]        VARCHAR (50)  NULL,
    [PartnerAddedDate]         VARCHAR (50)  NULL,
    [Next_Step_Date_Change__c] VARCHAR (50)  NULL,
    [CreatedBy]                VARCHAR (150) NULL,
    [DistyOppValue]            FLOAT (53)    NULL,
    [NodeEmployeeSize]         VARCHAR (25)  NULL,
    [TotalSeats]               FLOAT (53)    CONSTRAINT [DF_B_SFDC_OPPORTUNITY_TotalSeats] DEFAULT ((0)) NULL,
    [NodeIndustry]             VARCHAR (255) NULL,
    [DistyOppValue_Converted]  FLOAT (53)    NULL,
    [BookingAmount_Converted]  FLOAT (53)    NULL,
    [AccountSicCode]           VARCHAR (25)  NULL,
    [WonLostReason]            VARCHAR (100) NULL,
    [Vertical]                 VARCHAR (100) NULL,
    [Products]                 VARCHAR (255) NULL,
    [ContactEmail]             VARCHAR (200) NULL,
    [FieldMktgMngr]            VARCHAR (25)  NULL,
    [JointMarketingFunds]      VARCHAR (250) NULL,
    [PartnerSelectedCampaign]  VARCHAR (250) NULL,
    [PrimaryCampaignSource]    VARCHAR (250) NULL,
    [FirstCampaign]            VARCHAR (250) NULL,
    [CurrentVendors]           VARCHAR (250) NULL,
    [LeadSetBy]                VARCHAR (200) NULL,
    CONSTRAINT [PK_B_SFDC_OPPORTUNITY] PRIMARY KEY CLUSTERED ([ID] ASC)
);

