CREATE TABLE [dbo].[B_SFDC_LEADS] (
    [ID]                              VARCHAR (200) NOT NULL,
    [BANTDate]                        VARCHAR (50)  NULL,
    [City]                            VARCHAR (200) NULL,
    [Company]                         VARCHAR (255) NULL,
    [IsConverted]                     BIT           NOT NULL,
    [CONVERTEDDATE]                   VARCHAR (50)  NULL,
    [COUNTRY]                         VARCHAR (200) NULL,
    [CREATEDDATE]                     VARCHAR (200) NULL,
    [NAME]                            VARCHAR (200) NULL,
    [LEAD_OWNER_MANAGER__C]           VARCHAR (200) NULL,
    [MKTO2__LEAD_SCORE__C]            VARCHAR (50)  NULL,
    [LEAD_SET_BY__C]                  VARCHAR (200) NULL,
    [LEADSOURCE]                      VARCHAR (200) NULL,
    [MEMBER_FIRST_ASSOCIATED_DATE__C] VARCHAR (50)  NULL,
    [OWNERID]                         VARCHAR (200) NULL,
    [STATE]                           VARCHAR (200) NULL,
    [STATUS]                          VARCHAR (200) NULL,
    [OWNERNAME]                       VARCHAR (200) NULL,
    [RATING]                          VARCHAR (50)  NULL,
    [OwnerRoleId]                     VARCHAR (50)  NULL,
    [Region]                          VARCHAR (50)  NULL,
    [SubRegion]                       VARCHAR (50)  NULL,
    [LeadAge]                         FLOAT (53)    NULL,
    [LeadStatusAge]                   FLOAT (53)    NULL,
    [TimeToTouch]                     VARCHAR (50)  NULL,
    [LeadDisqualificationReason]      VARCHAR (150) NULL,
    [Description]                     VARCHAR (MAX) NULL,
    [ReportedChannelPartner]          VARCHAR (255) NULL,
    [Email]                           VARCHAR (250) NULL,
    CONSTRAINT [PK_B_SFDC_LEADS] PRIMARY KEY CLUSTERED ([ID] ASC)
);

