CREATE TABLE [dbo].[BmActiveUserMatchClean] (
    [USERNAME]      VARCHAR (8000) NULL,
    [FIRST_NAME]    VARCHAR (8000) NULL,
    [LAST_NAME]     VARCHAR (8000) NULL,
    [EMAIL]         VARCHAR (8000) NULL,
    [DATE_ADDED]    DATETIME       NULL,
    [DATE_MODIFIED] DATETIME       NULL,
    [LASTLOGIN]     DATETIME       NULL,
    [COMPANY]       VARCHAR (8000) NULL,
    [USERTYPE]      VARCHAR (8000) NULL,
    [GROUP]         VARCHAR (8000) NULL,
    [STATUS]        VARCHAR (8000) NULL
);

