CREATE TABLE [dbo].[BmActiveLastLogin] (
    [USERNAME]      VARCHAR (50)  NULL,
    [FIRST_NAME]    VARCHAR (500) NULL,
    [LAST_NAME]     VARCHAR (500) NULL,
    [EMAIL]         VARCHAR (500) NULL,
    [DATE_ADDED]    DATETIME      NULL,
    [DATE_MODIFIED] DATETIME      NULL,
    [LASTLOGIN]     DATETIME      NULL,
    [COMPANY]       VARCHAR (50)  NULL,
    [USERTYPE]      VARCHAR (50)  NULL,
    [GROUP]         VARCHAR (50)  NULL,
    [STATUS]        VARCHAR (50)  NULL
);

