CREATE TABLE [dbo].[CallidusSalesCompQTY2] (
    [ROWID]              BIGINT           IDENTITY (1, 1) NOT NULL,
    [Invoice]            NVARCHAR (50)    NULL,
    [Line]               NCHAR (10)       NULL,
    [SubLine]            NCHAR (10)       NULL,
    [EventType]          VARCHAR (20)     NULL,
    [SKU]                VARCHAR (50)     NULL,
    [ItemDesc]           NCHAR (1000)     NULL,
    [BillingsComp]       FLOAT (53)       NULL,
    [ValueUnitType]      NCHAR (10)       NULL,
    [QTY]                NUMERIC (38, 12) NULL,
    [InvoiceDate]        DATETIME         NULL,
    [CustomerPO]         NVARCHAR (50)    NULL,
    [SalesOrder]         NVARCHAR (50)    NULL,
    [OrigSalesOrder]     NVARCHAR (50)    NULL,
    [QMSOrderNumber]     VARCHAR (50)     NULL,
    [Source]             NVARCHAR (50)    NULL,
    [PartnerG]           VARCHAR (255)    NULL,
    [Partner]            VARCHAR (255)    NULL,
    [ImpactNumber]       NVARCHAR (50)    NULL,
    [EndCust]            NVARCHAR (50)    NULL,
    [EndCustName]        VARCHAR (255)    NULL,
    [RevType]            VARCHAR (255)    NULL,
    [Type]               VARCHAR (255)    NULL,
    [GMFamily]           VARCHAR (255)    NULL,
    [StockCode]          VARCHAR (50)     NULL,
    [StockCodeDesc]      VARCHAR (1000)   NULL,
    [OrderType]          VARCHAR (50)     NULL,
    [DBFamily]           VARCHAR (255)    NULL,
    [Currency]           NCHAR (3)        NULL,
    [OrderDate]          DATETIME         NULL,
    [RequestedShipDate]  DATETIME         NULL,
    [ShipCity]           NVARCHAR (100)   NULL,
    [ShipState]          NVARCHAR (100)   NULL,
    [ShipPostalCode]     NVARCHAR (10)    NULL,
    [ShipCountry]        NVARCHAR (100)   NULL,
    [EndCustZip]         NVARCHAR (50)    NULL,
    [MarketFamily]       VARCHAR (255)    NULL,
    [ItemType]           VARCHAR (255)    NULL,
    [EndCustCity]        NVARCHAR (50)    NULL,
    [EndCustCountry]     NVARCHAR (50)    NULL,
    [TransactionNumber]  VARCHAR (50)     NULL,
    [VAD_INVOICE_NUMBER] VARCHAR (100)    NULL,
    [VAD_ID]             VARCHAR (50)     NULL,
    [VADCustName]        VARCHAR (100)    NULL,
    [EndCustState]       NVARCHAR (50)    NULL,
    [PartnerOfRecord]    NVARCHAR (50)    NULL,
    [EndCustTheater]     NVARCHAR (50)    NULL,
    [Status]             VARCHAR (5)      NULL,
    [ErrorMsg]           TEXT             NULL,
    [Margin]             NUMERIC (30, 12) NULL
);

