CREATE TABLE [dbo].[CE_SVY_2014] (
    [Created]  DATETIME     CONSTRAINT [DF_CE_SVY2014_Created] DEFAULT (getdate()) NULL,
    [SvyID]    VARCHAR (15) NULL,
    [FIELD1]   FLOAT (53)   NOT NULL,
    [FIELD2]   DATETIME     NULL,
    [FIELD3]   TEXT         NULL,
    [FIELD4]   TEXT         NULL,
    [FIELD5]   DATETIME     NOT NULL,
    [FIELD6]   TEXT         NULL,
    [FIELD7]   TEXT         NULL,
    [FIELD8]   TEXT         NULL,
    [FIELD9]   TEXT         NULL,
    [FIELD10]  TEXT         NULL,
    [FIELD11]  TEXT         NULL,
    [FIELD12]  TEXT         NULL,
    [FIELD13]  TEXT         NULL,
    [FIELD14]  TEXT         NULL,
    [FIELD15]  TEXT         NULL,
    [FIELD16]  TEXT         NULL,
    [FIELD17]  TEXT         NULL,
    [FIELD18]  TEXT         NULL,
    [FIELD19]  TEXT         NULL,
    [FIELD20]  TEXT         NULL,
    [FIELD21]  TEXT         NULL,
    [FIELD22]  TEXT         NULL,
    [FIELD23]  TEXT         NULL,
    [FIELD24]  TEXT         NULL,
    [FIELD25]  TEXT         NULL,
    [FIELD26]  TEXT         NULL,
    [FIELD27]  TEXT         NULL,
    [FIELD28]  TEXT         NULL,
    [FIELD29]  TEXT         NULL,
    [FIELD30]  TEXT         NULL,
    [FIELD31]  TEXT         NULL,
    [FIELD32]  TEXT         NULL,
    [FIELD33]  TEXT         NULL,
    [FIELD34]  TEXT         NULL,
    [FIELD35]  TEXT         NULL,
    [FIELD36]  TEXT         NULL,
    [FIELD37]  TEXT         NULL,
    [FIELD38]  TEXT         NULL,
    [FIELD39]  TEXT         NULL,
    [FIELD40]  TEXT         NULL,
    [FIELD41]  TEXT         NULL,
    [FIELD42]  TEXT         NULL,
    [FIELD43]  TEXT         NULL,
    [FIELD44]  TEXT         NULL,
    [FIELD45]  TEXT         NULL,
    [FIELD46]  TEXT         NULL,
    [FIELD47]  TEXT         NULL,
    [FIELD48]  TEXT         NULL,
    [FIELD49]  TEXT         NULL,
    [FIELD50]  TEXT         NULL,
    [FIELD51]  TEXT         NULL,
    [FIELD52]  TEXT         NULL,
    [FIELD53]  TEXT         NULL,
    [FIELD54]  TEXT         NULL,
    [FIELD55]  TEXT         NULL,
    [FIELD56]  TEXT         NULL,
    [FIELD57]  TEXT         NULL,
    [FIELD58]  TEXT         NULL,
    [FIELD59]  TEXT         NULL,
    [FIELD60]  TEXT         NULL,
    [FIELD61]  TEXT         NULL,
    [FIELD62]  TEXT         NULL,
    [FIELD63]  TEXT         NULL,
    [FIELD64]  TEXT         NULL,
    [FIELD65]  TEXT         NULL,
    [FIELD66]  TEXT         NULL,
    [FIELD67]  TEXT         NULL,
    [FIELD68]  TEXT         NULL,
    [FIELD69]  TEXT         NULL,
    [FIELD70]  TEXT         NULL,
    [FIELD71]  TEXT         NULL,
    [FIELD72]  TEXT         NULL,
    [FIELD73]  TEXT         NULL,
    [FIELD74]  TEXT         NULL,
    [FIELD75]  TEXT         NULL,
    [FIELD76]  TEXT         NULL,
    [FIELD77]  TEXT         NULL,
    [FIELD78]  TEXT         NULL,
    [FIELD79]  TEXT         NULL,
    [FIELD80]  TEXT         NULL,
    [FIELD81]  TEXT         NULL,
    [FIELD82]  TEXT         NULL,
    [FIELD83]  TEXT         NULL,
    [FIELD84]  TEXT         NULL,
    [FIELD85]  TEXT         NULL,
    [FIELD86]  TEXT         NULL,
    [FIELD87]  TEXT         NULL,
    [FIELD88]  TEXT         NULL,
    [FIELD89]  TEXT         NULL,
    [FIELD90]  TEXT         NULL,
    [FIELD91]  TEXT         NULL,
    [FIELD92]  TEXT         NULL,
    [FIELD93]  TEXT         NULL,
    [FIELD94]  TEXT         NULL,
    [FIELD95]  TEXT         NULL,
    [FIELD96]  TEXT         NULL,
    [FIELD97]  TEXT         NULL,
    [FIELD98]  TEXT         NULL,
    [FIELD99]  TEXT         NULL,
    [FIELD100] TEXT         NULL,
    [FIELD101] TEXT         NULL,
    [FIELD102] TEXT         NULL,
    [FIELD103] TEXT         NULL,
    CONSTRAINT [PK_CE_SVY_2014] PRIMARY KEY CLUSTERED ([FIELD1] ASC)
);


GO
GRANT SELECT
    ON OBJECT::[dbo].[CE_SVY_2014] TO [CsatData]
    AS [dbo];

