CREATE TABLE [dbo].[CSAT_5638] (
    [Id]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [Created]        DATETIME        CONSTRAINT [DF_CSAT_5638_Created] DEFAULT (getdate()) NOT NULL,
    [INV_ID]         VARCHAR (15)    NULL,
    [INV_Date]       DATETIME        NULL,
    [Resp_ID]        VARCHAR (15)    NULL,
    [Resp_Date]      DATETIME        NULL,
    [Partnername]    VARCHAR (100)   NULL,
    [Comment_1]      VARCHAR (15)    NULL,
    [Comment_2]      VARCHAR (15)    NULL,
    [Comment_3]      VARCHAR (15)    NULL,
    [Q38]            VARCHAR (5)     NULL,
    [Q38_Comment]    TEXT            NULL,
    [Q1]             VARCHAR (5)     NULL,
    [Q2]             VARCHAR (5)     NULL,
    [Q3]             VARCHAR (5)     NULL,
    [Q13]            VARCHAR (5)     NULL,
    [Q14]            VARCHAR (5)     NULL,
    [Q18]            VARCHAR (5)     NULL,
    [Comment_4]      TEXT            NULL,
    [Comment_5]      VARCHAR (5)     NULL,
    [Comment_6]      VARCHAR (5)     NULL,
    [Comment_7]      TEXT            NULL,
    [Q4]             VARCHAR (5)     NULL,
    [Q7]             VARCHAR (5)     NULL,
    [Q8]             VARCHAR (5)     NULL,
    [Comment_8]      VARCHAR (5)     NULL,
    [Comment_9]      VARCHAR (5)     NULL,
    [Comment_10]     VARCHAR (5)     NULL,
    [Q9]             VARCHAR (5)     NULL,
    [Comment_11]     VARCHAR (5)     NULL,
    [Comment_12]     VARCHAR (5)     NULL,
    [Comment_13]     VARCHAR (5)     NULL,
    [Comment_14]     VARCHAR (5)     NULL,
    [Comment_15]     VARCHAR (5)     NULL,
    [Comment_16]     TEXT            NULL,
    [Comment_17]     VARCHAR (5)     NULL,
    [Q15]            VARCHAR (5)     NULL,
    [Q16]            VARCHAR (5)     NULL,
    [Q17]            VARCHAR (5)     NULL,
    [Comment_18]     TEXT            NULL,
    [Comment_19]     VARCHAR (5)     NULL,
    [Comment_20]     VARCHAR (5)     NULL,
    [Comment_21]     TEXT            NULL,
    [Comment_22]     TEXT            NULL,
    [Comment_23]     TEXT            NULL,
    [Q39]            VARCHAR (15)    NULL,
    [Q19]            VARCHAR (5)     NULL,
    [Q19_2]          VARCHAR (5)     NULL,
    [Q20]            VARCHAR (5)     NULL,
    [Q21]            VARCHAR (5)     NULL,
    [Q40_2]          VARCHAR (5)     NULL,
    [Comment_24]     VARCHAR (5)     NULL,
    [Q40]            VARCHAR (5)     NULL,
    [Q22]            TEXT            NULL,
    [Q23]            TEXT            NULL,
    [Comment_25]     TEXT            NULL,
    [Comment_26]     TEXT            NULL,
    [Q26]            TEXT            NULL,
    [Q27]            TEXT            NULL,
    [Q27_comment]    TEXT            NULL,
    [Q33]            TEXT            NULL,
    [Comment_27]     TEXT            NULL,
    [CsatCreated]    DATETIME        NULL,
    [CustActkey]     VARCHAR (15)    NULL,
    [Title]          VARCHAR (100)   NULL,
    [Salutation]     VARCHAR (50)    NULL,
    [First_Name]     VARCHAR (25)    NULL,
    [Last_Name]      VARCHAR (25)    NULL,
    [email]          VARCHAR (100)   NULL,
    [phone]          VARCHAR (50)    NULL,
    [SCI]            VARCHAR (100)   NULL,
    [PI]             DECIMAL (18, 2) NULL,
    [Company]        VARCHAR (100)   NULL,
    [First_Name2]    VARCHAR (50)    NULL,
    [Last_Name2]     VARCHAR (50)    NULL,
    [Job_Title]      VARCHAR (100)   NULL,
    [email2]         VARCHAR (100)   NULL,
    [Work_Phone]     VARCHAR (50)    NULL,
    [Address]        VARCHAR (100)   NULL,
    [city]           VARCHAR (50)    NULL,
    [state]          VARCHAR (50)    NULL,
    [zip]            VARCHAR (25)    NULL,
    [LOC]            VARCHAR (50)    NULL,
    [Region]         VARCHAR (25)    NULL,
    [PROWID]         VARCHAR (10)    NULL,
    [Agreement]      VARCHAR (50)    NULL,
    [SR_Email]       VARCHAR (100)   NULL,
    [Part_email]     VARCHAR (100)   NULL,
    [Impact]         VARCHAR (50)    NULL,
    [Comment_28]     VARCHAR (50)    NULL,
    [Comment_29]     VARCHAR (50)    NULL,
    [Comment_30]     VARCHAR (50)    NULL,
    [Comment_31]     TEXT            NULL,
    [Language]       VARCHAR (25)    NULL,
    [Final_Month]    VARCHAR (25)    NULL,
    [Final_Day]      VARCHAR (5)     NULL,
    [Final_Year]     VARCHAR (5)     NULL,
    [Final_TimeDate] VARCHAR (25)    NULL,
    [CROS1]          VARCHAR (25)    NULL,
    [Comment_32]     TEXT            NULL,
    [Comment_33]     TEXT            NULL,
    [Comment_34]     TEXT            NULL,
    [Comment_35]     TEXT            NULL,
    [License_count]  VARCHAR (25)    NULL,
    [Weight_Mult]    VARCHAR (5)     NULL,
    [Weight_PI]      VARCHAR (25)    NULL,
    [survey_type]    VARCHAR (50)    NULL,
    [Comment_36]     TEXT            NULL,
    [Comment_37]     TEXT            NULL,
    [Comment_38]     TEXT            NULL,
    [Comment_39]     TEXT            NULL,
    CONSTRAINT [PK_CSAT_5638] PRIMARY KEY CLUSTERED ([Id] ASC)
);

