CREATE TABLE [dbo].[CUSTOMER_SBE_SKUS] (
    [SKU]        VARCHAR (50)   NULL,
    [SystemType] NVARCHAR (255) NULL,
    [SBE100]     VARCHAR (15)   CONSTRAINT [DF_CUSTOMER_SBE_SKUS_SBE100] DEFAULT ('No') NULL
);


GO
GRANT SELECT
    ON OBJECT::[dbo].[CUSTOMER_SBE_SKUS] TO [PMData]
    AS [dbo];

