CREATE TABLE [dbo].[DNB_NUMBERS] (
    [SE_ID] VARCHAR (15)  NOT NULL,
    [Name]  VARCHAR (200) NULL,
    [DUNS]  VARCHAR (9)   NULL,
    CONSTRAINT [PK_DNB_NUMBERS] PRIMARY KEY CLUSTERED ([SE_ID] ASC)
);

