CREATE TABLE [dbo].[InvoiceExportTemp] (
    [Record ID]                         VARCHAR (8000) NULL,
    [AX End Customer]                   VARCHAR (8000) NULL,
    [AX Territory Code]                 VARCHAR (8000) NULL,
    [Billings]                          VARCHAR (8000) NULL,
    [CalendarMonthCommission]           VARCHAR (8000) NULL,
    [Created By ID]                     VARCHAR (8000) NULL,
    [Created Date]                      VARCHAR (8000) NULL,
    [Created Date (Virtual)]            VARCHAR (8000) NULL,
    [CSE Invoice]                       VARCHAR (8000) NULL,
    [CustomerPo]                        VARCHAR (8000) NULL,
    [Deleted]                           VARCHAR (8000) NULL,
    [EndCust Account Name]              VARCHAR (8000) NULL,
    [EndCust ShoreTel ID]               VARCHAR (8000) NULL,
    [EndCust ShoreTel ID (2)]           VARCHAR (8000) NULL,
    [EndCust ShoreTel Territory]        VARCHAR (8000) NULL,
    [EndCustBuild]                      VARCHAR (8000) NULL,
    [FiscalQuarterCommission]           VARCHAR (8000) NULL,
    [GOV]                               VARCHAR (8000) NULL,
    [GOVclass]                          VARCHAR (8000) NULL,
    [Invoice Date]                      VARCHAR (8000) NULL,
    [Invoice Name]                      VARCHAR (8000) NULL,
    [Invoice Number]                    VARCHAR (8000) NULL,
    [Invoice SO Number]                 VARCHAR (8000) NULL,
    [Last Modified By ID]               VARCHAR (8000) NULL,
    [Last Modified Date]                VARCHAR (8000) NULL,
    [Last Referenced Date]              VARCHAR (8000) NULL,
    [Last Viewed Date]                  VARCHAR (8000) NULL,
    [MAP]                               VARCHAR (8000) NULL,
    [Margin$]                           VARCHAR (8000) NULL,
    [Order Date]                        VARCHAR (8000) NULL,
    [OrderType]                         VARCHAR (8000) NULL,
    [OrigSalesArea]                     VARCHAR (8000) NULL,
    [Partner Account]                   VARCHAR (8000) NULL,
    [Partner ChampLevel]                VARCHAR (8000) NULL,
    [Partner Distributor]               VARCHAR (8000) NULL,
    [Partner Override Owner]            VARCHAR (8000) NULL,
    [Partner Owner]                     VARCHAR (8000) NULL,
    [Partner PBM Region]                VARCHAR (8000) NULL,
    [Partner ShoreTel ID]               VARCHAR (8000) NULL,
    [Partner ShoreTel ID (2)]           VARCHAR (8000) NULL,
    [Partner Status]                    VARCHAR (8000) NULL,
    [Partner Sub Type]                  VARCHAR (8000) NULL,
    [PartnerG]                          VARCHAR (8000) NULL,
    [QmsOrderNumber]                    VARCHAR (8000) NULL,
    [Received Connection ID]            VARCHAR (8000) NULL,
    [Region (End Customer)]             VARCHAR (8000) NULL,
    [RegionSub]                         VARCHAR (8000) NULL,
    [REVtype]                           VARCHAR (8000) NULL,
    [Sales Order]                       VARCHAR (8000) NULL,
    [Sent Connection ID]                VARCHAR (8000) NULL,
    [ShoreTel Territory (End Customer)] VARCHAR (8000) NULL,
    [Sub-Region (End Customer)]         VARCHAR (8000) NULL,
    [System Modstamp]                   VARCHAR (8000) NULL
);

