CREATE TABLE [dbo].[KB_SVY] (
    [Created] DATETIME       CONSTRAINT [DF_KB_SVY_Created] DEFAULT (getdate()) NULL,
    [FIELD1]  NVARCHAR (255) NOT NULL,
    [FIELD2]  DATETIME       NULL,
    [FIELD3]  NVARCHAR (255) NULL,
    [FIELD4]  NVARCHAR (255) NULL,
    [FIELD5]  NVARCHAR (255) NULL,
    [FIELD6]  TEXT           NULL,
    [FIELD7]  NVARCHAR (255) NULL,
    [FIELD8]  NVARCHAR (255) NULL,
    [FIELD9]  NVARCHAR (255) NULL,
    [FIELD10] NVARCHAR (255) NULL,
    [FIELD11] NVARCHAR (255) NULL,
    [FIELD12] NVARCHAR (255) NULL,
    [FIELD13] NVARCHAR (255) NULL,
    [FIELD14] NVARCHAR (255) NULL,
    [FIELD15] NVARCHAR (255) NULL,
    [FIELD16] NVARCHAR (255) NULL,
    [FIELD17] TEXT           NULL,
    [FIELD18] NVARCHAR (255) NULL,
    [FIELD19] TEXT           NULL,
    [FIELD20] NVARCHAR (255) NULL,
    [FIELD21] NVARCHAR (255) NULL,
    [FIELD22] TEXT           NULL,
    [FIELD23] NVARCHAR (255) NULL,
    CONSTRAINT [PK_KB_SVY] PRIMARY KEY CLUSTERED ([FIELD1] ASC)
);


GO
GRANT SELECT
    ON OBJECT::[dbo].[KB_SVY] TO [CsatData]
    AS [dbo];

