CREATE TABLE [dbo].[LEAD] (
    [Created]                DATETIME        CONSTRAINT [DF_LEADS_Created] DEFAULT (getdate()) NULL,
    [SfdcId]                 VARCHAR (50)    NOT NULL,
    [SfdcCreatedUTC]         DATETIME        NULL,
    [SfdcModifiedUTC]        DATETIME        NULL,
    [Company]                VARCHAR (500)   NULL,
    [CampaignDept]           VARCHAR (500)   NULL,
    [Status]                 VARCHAR (50)    NULL,
    [IsQualified]            VARCHAR (50)    NULL,
    [LeadNumber]             VARCHAR (50)    NULL,
    [PartnerSTID]            VARCHAR (50)    NULL,
    [STLeadId]               VARCHAR (50)    NULL,
    [PartnerSalesStage]      VARCHAR (50)    NULL,
    [AssocOptyStage]         VARCHAR (500)   NULL,
    [AssocPartnerChampLevel] VARCHAR (500)   NULL,
    [AssocPartnerSubType]    VARCHAR (500)   NULL,
    [AssocOpty]              VARCHAR (500)   NULL,
    [AssocPartner]           VARCHAR (500)   NULL,
    [PartnerAssignDate]      DATETIME        NULL,
    [PartnerEstCloseDate]    DATETIME        NULL,
    [LeadSource]             VARCHAR (50)    NULL,
    [MRRAmount]              DECIMAL (18, 2) NULL,
    [NRRAmount]              DECIMAL (18, 2) NULL,
    [OpptyRegApprDate]       DATETIME        NULL,
    [OpptyRegSubmitDate]     DATETIME        NULL,
    [OpptyRegEligDate]       DATETIME        NULL,
    [OpptyRegExpDate]        DATETIME        NULL,
    [OpptyRegStatus]         VARCHAR (50)    NULL,
    [OpptyCreatedDate]       DATETIME        NULL,
    [OpptyClosedDate]        DATETIME        NULL,
    [ConAcctOpptyRegExpDate] DATETIME        NULL,
    CONSTRAINT [PK_LEAD] PRIMARY KEY CLUSTERED ([SfdcId] ASC)
);

