CREATE TABLE [dbo].[Local_MASTERbacklog] (
    [DataSource]            VARCHAR (27)     NOT NULL,
    [OrderDate]             DATETIME         NULL,
    [SalesOrder]            NVARCHAR (20)    NULL,
    [CustomerPurchaseOrder] NVARCHAR (50)    NULL,
    [PartnerG]              CHAR (255)       NULL,
    [ImpactNumber]          NVARCHAR (40)    NULL,
    [Partner]               CHAR (255)       NULL,
    [ECnumber]              NVARCHAR (40)    NULL,
    [EndCustomer]           CHAR (255)       NULL,
    [DBfamily]              NVARCHAR (255)   NULL,
    [GMFamily]              NVARCHAR (255)   NULL,
    [REVtype]               NVARCHAR (255)   NULL,
    [Part]                  CHAR (11)        NULL,
    [PartDesc]              NVARCHAR (255)   NULL,
    [Sku]                   NVARCHAR (20)    NULL,
    [OrderType]             NVARCHAR (10)    NULL,
    [SalesTerritory]        NVARCHAR (255)   NULL,
    [QmsOrderNumber]        NVARCHAR (25)    NULL,
    [Units]                 DECIMAL (38, 12) NULL,
    [BklgUSD]               FLOAT (53)       NULL,
    [MAP]                   CHAR (3)         NULL,
    [GOV]                   CHAR (3)         NULL,
    [ZipPostalCode]         NVARCHAR (10)    NULL,
    [City]                  NVARCHAR (100)   NULL,
    [State]                 NVARCHAR (30)    NULL,
    [CountryRegion]         NVARCHAR (30)    NULL,
    [RegionArea]            NVARCHAR (255)   NULL,
    [RVP]                   NVARCHAR (255)   NULL,
    [Country]               NVARCHAR (255)   NULL,
    [Fquarter]              NVARCHAR (255)   NULL,
    [BklgClass]             CHAR (7)         NULL,
    [HoldType]              NVARCHAR (15)    NULL,
    [Channel]               CHAR (1)         NULL,
    [ProfitCenter]          NVARCHAR (255)   NULL,
    [ProductClass]          NVARCHAR (255)   NULL,
    [Status]                INT              NULL,
    [SEMCONFIRMEDOK]        INT              NULL,
    [CUSTOMERREF]           NVARCHAR (100)   NULL,
    [ConfirmedShipDate]     DATETIME         NULL,
    [RequestedShipDate]     DATETIME         NOT NULL,
    [BklgLC]                DECIMAL (38, 12) NULL,
    [ExchRate]              FLOAT (53)       NULL,
    [Currency]              NVARCHAR (3)     NULL,
    [Cquarter]              NVARCHAR (255)   NULL,
    [ListPrice]             DECIMAL (28, 12) NOT NULL,
    [PromoPrice]            DECIMAL (28, 12) NOT NULL,
    [MktFamily]             NVARCHAR (255)   NULL,
    [LineStatus]            INT              NOT NULL,
    [ConfirmedReceiptDate]  DATETIME         NULL,
    [RequestedReceiptDate]  DATETIME         NULL,
    [ShipDateRequested]     DATETIME         NOT NULL,
    [ShipDateConfirmed]     DATETIME         NULL,
    [DeliveryControlDate]   INT              NULL,
    [PickingListDate]       VARCHAR (1)      NOT NULL,
    [PackingSlipDate]       VARCHAR (1)      NOT NULL,
    [ChannelRole]           CHAR (10)        NULL
);

