CREATE TABLE [dbo].[MiCC_Agent] (
    [Source]                             VARCHAR (4)    NOT NULL,
    [ReportRecordId]                     NVARCHAR (123) NOT NULL,
    [Created]                            DATETIME       CONSTRAINT [DF_MiCC_Agent_Created] DEFAULT (getdate()) NOT NULL,
    [Date]                               DATETIME       NULL,
    [PCTACDabandonedcallsofACDpresented] INT            NULL,
    [PCTCmltvidletimeformultiplegroups]  INT            NULL,
    [PCTReleasetime]                     FLOAT (53)     NULL,
    [PCTReleasetimeformultiplegroups]    INT            NULL,
    [ACDabandonedcalls]                  FLOAT (53)     NULL,
    [ACDansweredcalls]                   INT            NULL,
    [ACDpresentednotansweredcalls]       INT            NULL,
    [AgentNameDel]                       INT            NULL,
    [AgentNumberDel]                     INT            NULL,
    [AvgACDemailinteractiontime]         DATETIME       NULL,
    [AvgACDholdtime]                     DATETIME       NULL,
    [AvgACDtalktime]                     DATETIME       NULL,
    [AvgACDWrapuptime]                   DATETIME       NULL,
    [AvgtalktimeofNACDincoming]          DATETIME       NULL,
    [AvgtalktimeofNACDoutgoing]          DATETIME       NULL,
    [Chatcontactsanswered]               INT            NULL,
    [Cmltvlogintime]                     DATETIME       NULL,
    [Cmltvreleasetimeformultiplegroups]  DATETIME       NULL,
    [CmltvtalktimeofNACDoutgoing]        DATETIME       NULL,
    [Emailcontactsanswered]              INT            NULL,
    [NACDincomingcalls]                  INT            NULL,
    [Logintimeformultiplegroups]         INT            NULL,
    [LongestACDtalktime]                 DATETIME       NULL,
    [AgentID]                            NVARCHAR (50)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [AgentNumber]                        NVARCHAR (50)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [AgentName]                          NVARCHAR (101) NULL,
    [ACDPresentedCalls]                  INT            NULL,
    [ChatContactsPresented]              INT            NULL,
    [EmailContactsPresented]             INT            NULL,
    [AvgACDChatInteractionTime]          DATETIME       NULL,
    [LongestACDChatInteractionTime]      DATETIME       NULL,
    [LongestACDEmailInteractionTime]     DATETIME       NULL,
    [ChatContactsPresentedNotAnswered]   INT            NULL,
    [CmltvACDEmailInteractionTime]       DATETIME       NULL,
    [OutboundACDAnswered]                INT            NULL,
    [CmltvIdleTimeForMultipleGroups]     DATETIME       NULL,
    [NACDOutgoingCalls]                  INT            NULL,
    [OutboundACDPresented]               INT            NULL,
    [AgentSfdcId]                        VARCHAR (25)   NULL,
    CONSTRAINT [PK_MiCC_Agent] PRIMARY KEY CLUSTERED ([ReportRecordId] ASC)
);

