CREATE TABLE [dbo].[MiCC_Group] (
    [Source]                                        VARCHAR (4)    NOT NULL,
    [Created]                                       DATETIME       CONSTRAINT [DF_MiCC_Group_Created] DEFAULT (getdate()) NOT NULL,
    [ReportRecordId]                                NVARCHAR (100) NOT NULL,
    [ReportDate]                                    DATETIME       NULL,
    [ACDCallsAccepted]                              INT            NULL,
    [ACDCallsAnswered]                              INT            NULL,
    [ChatContactsAccepted]                          INT            NULL,
    [ChatContactsAnswered]                          INT            NULL,
    [EmailContactsAccepted]                         INT            NULL,
    [EmailContactsAnswered]                         INT            NULL,
    [AvgWaitTimeBeforeAnswered]                     DATETIME       NULL,
    [AvgWaitTimeInQueueOfCallsRequestedCallback]    DATETIME       NULL,
    [LongestWaitTimeBeforeAnswered]                 DATETIME       NULL,
    [LongestWaitTimeInQueueOfCallRequestedCallback] DATETIME       NULL,
    [AvgWaitTimeBeforeAnsweredOfChatContacts]       DATETIME       NULL,
    [CmltvWaitTimeBeforeAnsweredOfChatContacts]     DATETIME       NULL,
    [OutboundACDCallsAsAConsequenceOfCallback]      INT            NULL,
    [GroupID]                                       INT            NULL,
    [GroupName]                                     NVARCHAR (114) NOT NULL,
    [TSFForIncomingACDCalls]                        INT            NULL,
    [LongestWaitTimeBeforeAnsweredChatContacts]     DATETIME       NULL,
    [PCTACDCallsAbandonedOfAcceptedCalls]           INT            NULL,
    [AvgTalkTimeACDCalls]                           DATETIME       NULL,
    [AvgNumberLoggedinAgents]                       INT            NULL,
    [MaximumNumberAgentsLoggedInSimultaneously]     INT            NULL,
    [ACDCallsAbandoned]                             INT            NULL,
    [ACDCallsRequestedCallbackWhileWaitingInQueue]  INT            NULL,
    [ACDCallsOverflowedInAndAnswered]               INT            NULL,
    [NumberOfCallsAnsweredWithinTASA]               INT            NULL,
    [CumulativeTalkTimeOfIncomingACDCalls]          DATETIME       NULL,
    [CumulativeWaitTimeBeforeAnsweredOfACDIncoming] DATETIME       NULL,
    [AvgWaitTimeBeforeAnsweredEmailContacts]        DATETIME       NULL,
    [LongestQueueTimeBeforeAnsweredEmailContacts]   DATETIME       NULL,
    [AvgInteractionTimeEmailContacts]               DATETIME       NULL,
    [CmltvTalkTimeACDCalls]                         DATETIME       NULL,
    [GlobalAggCmltvInteractionTimeEmailContacts]    DATETIME       NULL,
    [TSFEmailContacts]                              FLOAT (53)     NULL,
    [CmltvIntTimeEmailContacts]                     DATETIME       NULL,
    CONSTRAINT [PK_MiCC_Group] PRIMARY KEY CLUSTERED ([ReportRecordId] ASC)
);

