CREATE TABLE [dbo].[MiCC_GROUP_RAW] (
    [FKTimeInterval]    TINYINT          NOT NULL,
    [DateKey]           INT              NOT NULL,
    [TimeKey]           INT              NOT NULL,
    [QueueKey]          UNIQUEIDENTIFIER NOT NULL,
    [QueueDialableID]   NVARCHAR (320)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [QueueNodeID]       INT              NOT NULL,
    [QueueReporting]    NVARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [QueueName]         NVARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [QueueFullNameName] NVARCHAR (114)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [Offered]           INT              NULL,
    [Answered]          INT              NOT NULL,
    [QueueDuration]     INT              NULL,
    [WorkTimerDuration] INT              NULL,
    [DeviceACDDuration] INT              NULL,
    [ShortAbandon]      INT              NULL,
    [LongAbandon]       INT              NULL,
    [Interflow]         INT              NOT NULL,
    [Requeue]           INT              NOT NULL,
    [Unavailable]       INT              NOT NULL,
    [AnswerBy1]         INT              NULL,
    [AnswerBy2]         INT              NULL,
    [AnswerBy3]         INT              NULL,
    [AnswerBy4]         INT              NULL,
    [TimeToAnswer]      INT              NOT NULL,
    [TimeToAbandon]     INT              NULL,
    [TimeToInterflow]   INT              NOT NULL,
    [ServiceCount]      INT              NULL
);

