CREATE TABLE [dbo].[OPPORTUNITY_UAT] (
    [Created]                  DATETIME        CONSTRAINT [DF_OPPORTUNITY_UAT_Created] DEFAULT (getdate()) NOT NULL,
    [OpportunityID]            VARCHAR (50)    NOT NULL,
    [AccountID]                VARCHAR (50)    NULL,
    [AccountName]              VARCHAR (500)   NULL,
    [AccountPartnerReferredID] VARCHAR (50)    NULL,
    [Age]                      VARCHAR (500)   NULL,
    [AmountWon]                DECIMAL (18, 2) NULL,
    [CloseDate]                DATETIME        NULL,
    [ContractType]             VARCHAR (500)   NULL,
    [DealMasterAgent]          VARCHAR (500)   NULL,
    [DealSize]                 VARCHAR (500)   NULL,
    [EstimatedMRR]             DECIMAL (18, 2) NULL,
    [EstimatedNRR]             DECIMAL (18, 2) NULL,
    [ExpectedMRRRevenue]       DECIMAL (18, 2) NULL,
    [ExpectedNRRRevenue]       DECIMAL (18, 2) NULL,
    [InferWonAmount]           DECIMAL (18, 2) NULL,
    [isSecondary]              VARCHAR (500)   NULL,
    [LastModified]             DATETIME        NULL,
    [LeadSource]               VARCHAR (500)   NULL,
    [LeadPartner]              VARCHAR (100)   NULL,
    [MRRAmount]                DECIMAL (18, 2) NULL,
    [Name]                     VARCHAR (500)   NULL,
    [NextStep]                 VARCHAR (500)   NULL,
    [NRRAmount]                DECIMAL (18, 2) NULL,
    [NumOfProfiles]            VARCHAR (500)   NULL,
    [OriginalLeadSource]       VARCHAR (500)   NULL,
    [OwnerID]                  VARCHAR (50)    NULL,
    [OwnerRole]                VARCHAR (500)   NULL,
    [PartnerRep]               VARCHAR (500)   NULL,
    [Probability]              VARCHAR (500)   NULL,
    [RecordType]               VARCHAR (100)   NULL,
    [ReferredbyPartnerID]      VARCHAR (50)    NULL,
    [ReferringPartner]         VARCHAR (500)   NULL,
    [ReferringPartnerSTID]     VARCHAR (50)    NULL,
    [SfdcCreateDateUTC]        DATETIME        NULL,
    [SfdcLastUpdateDateUTC]    DATETIME        NULL,
    [ShoreTelID]               VARCHAR (50)    NULL,
    [SkyLegacyID]              VARCHAR (50)    NULL,
    [Stage]                    VARCHAR (500)   NULL,
    [StageCurrent]             VARCHAR (500)   NULL,
    [TPFMRR]                   DECIMAL (18, 2) NULL,
    [Type]                     VARCHAR (100)   NULL,
    [Won]                      VARCHAR (500)   NULL,
    [OpportunityNumber]        VARCHAR (100)   NULL,
    [CampaignDept]             VARCHAR (100)   NULL,
    [LeadCategory]             VARCHAR (500)   NULL,
    [NumOfConnectBundles]      VARCHAR (500)   NULL,
    [SubType]                  VARCHAR (500)   NULL,
    [CountryCode]              VARCHAR (50)    NULL,
    [ShoreTelTerritory]        VARCHAR (50)    NULL,
    [CurrencyIsoCode]          VARCHAR (50)    NULL,
    CONSTRAINT [PK_OPPORTUNITY_UAT] PRIMARY KEY CLUSTERED ([OpportunityID] ASC)
);

