CREATE TABLE [dbo].[OPPORTUNITY_LOCATIONS] (
    [Created]      DATETIME     CONSTRAINT [DF_OPPORTUNITY_LOCATIONS_Created] DEFAULT (getdate()) NULL,
    [Id]           VARCHAR (25) NOT NULL,
    [PrimaryOppId] VARCHAR (25) NULL,
    CONSTRAINT [PK_OPPORTUNITY_LOCATIONS] PRIMARY KEY CLUSTERED ([Id] ASC)
);

