CREATE TABLE [dbo].[POS_TXN_Temp] (
    [Id]                                   INT            NOT NULL,
    [Created]                              DATETIME       NOT NULL,
    [INOW_DataFile_ID]                     NVARCHAR (255) NULL,
    [TransactionNumber]                    NVARCHAR (255) NOT NULL,
    [LineNumber]                           VARCHAR (5)    NULL,
    [SKU]                                  NVARCHAR (53)  NULL,
    [Quantity]                             FLOAT (53)     NULL,
    [Informational]                        NVARCHAR (255) NULL,
    [Serial_Number]                        NVARCHAR (255) NULL,
    [VAR_PO]                               NVARCHAR (255) NULL,
    [VAD_SO]                               NVARCHAR (100) NULL,
    [VAD_Ship_Date]                        DATETIME       NULL,
    [VAR_ID]                               NVARCHAR (15)  NULL,
    [Placeholder]                          NVARCHAR (255) NULL,
    [Sold_To_INOW_ID]                      NVARCHAR (255) NULL,
    [End_Customer_Contact_Name]            NVARCHAR (255) NULL,
    [End_Customer_Contact_Phone_Number]    NVARCHAR (255) NULL,
    [End_Customer_Contact_EMail]           NVARCHAR (255) NULL,
    [End_Customer_IT_Contact_Name]         NVARCHAR (255) NULL,
    [End_Customer_IT_Contact_Phone_Number] NVARCHAR (255) NULL,
    [End_Customer_IT_Contact_EMail]        NVARCHAR (255) NULL,
    [Transaction_Type]                     NVARCHAR (50)  NULL,
    [End_Customer_Lead_ID]                 NVARCHAR (50)  NULL,
    [End_Customer_ID]                      NVARCHAR (50)  NULL,
    [VAD_PO]                               NVARCHAR (255) NULL,
    [DiscountID_1]                         NVARCHAR (255) NULL,
    [DiscountAmount_1]                     FLOAT (53)     NULL,
    [DiscountID_2]                         NVARCHAR (255) NULL,
    [DiscountAmount_2]                     FLOAT (53)     NULL,
    [DiscountID_3]                         NVARCHAR (255) NULL,
    [DiscountAmount_3]                     FLOAT (53)     NULL,
    [Description]                          NVARCHAR (255) NULL,
    [VAD_PurchasePrice_Reported]           FLOAT (53)     NULL,
    [VAD_ExtPurchasePrice_Reported]        FLOAT (53)     NULL,
    [VAD_Net_Price]                        FLOAT (53)     NULL,
    [VAD_Net_Price_Ext]                    FLOAT (53)     NULL,
    [Currency]                             NVARCHAR (15)  NULL,
    [List_Price_Reported]                  FLOAT (53)     NULL,
    [VAD_ID]                               NVARCHAR (15)  NULL,
    [Matched_SKU]                          NVARCHAR (15)  NULL,
    [Matched_List_Price]                   FLOAT (53)     NULL,
    [VAD_PurchasePrice_Calculated]         FLOAT (53)     NULL,
    [Applied_Discount_Program]             NVARCHAR (100) NULL,
    [VAD_Net_Price_Calculated]             FLOAT (53)     NULL,
    [DELETED]                              FLOAT (53)     NULL,
    [REPORT_DATE]                          VARCHAR (50)   NULL,
    [FileName]                             VARCHAR (100)  NOT NULL,
    [DropShip]                             VARCHAR (50)   NULL,
    [EndCusPo]                             VARCHAR (50)   NULL,
    [Duplicate]                            VARCHAR (15)   NULL,
    [ship_to_name]                         VARCHAR (100)  NULL,
    [ship_to_id]                           VARCHAR (100)  NULL,
    [bill_to_name]                         VARCHAR (100)  NULL,
    [bill_to_id]                           VARCHAR (100)  NULL
);

