CREATE TABLE [dbo].[RESELLER] (
    [Created]                        DATETIME        CONSTRAINT [DF_RESELLER_Created] DEFAULT (getdate()) NULL,
    [SfdcCreatedUTC]                 DATETIME        NULL,
    [SfdcLastUpdatedUTC]             DATETIME        NULL,
    [SfdcId]                         VARCHAR (50)    NOT NULL,
    [Partner_Csn]                    VARCHAR (50)    NULL,
    [ImpactNumber]                   VARCHAR (50)    NULL,
    [NAME]                           VARCHAR (100)   NOT NULL,
    [ChampLevel]                     VARCHAR (50)    NULL,
    [Type]                           VARCHAR (50)    NULL,
    [Parent_Csn]                     VARCHAR (50)    NULL,
    [ParentSfdcId]                   VARCHAR (50)    NULL,
    [Region]                         VARCHAR (50)    NULL,
    [SupportPrice]                   DECIMAL (18, 3) NULL,
    [AuthToSell]                     VARCHAR (50)    NULL,
    [Address]                        VARCHAR (255)   NULL,
    [City]                           VARCHAR (100)   NULL,
    [State]                          VARCHAR (100)   NULL,
    [Zipcode]                        VARCHAR (50)    NULL,
    [Phone]                          VARCHAR (50)    NULL,
    [Country]                        VARCHAR (100)   NULL,
    [SubType]                        VARCHAR (50)    NULL,
    [SuperRegional]                  VARCHAR (5)     NULL,
    [StartDate]                      DATETIME        NULL,
    [QmsInternalDiscount]            DECIMAL (18)    NULL,
    [QMSNewPartnerPromotionDiscount] DECIMAL (18)    NULL,
    [QMSpartnerCompanyLogin]         VARCHAR (50)    NULL,
    [QMSResellerOnHold]              VARCHAR (5)     NULL,
    [BusinessPlanDate]               DATETIME        NULL,
    [OwnerId]                        VARCHAR (50)    NULL,
    [AXArea]                         VARCHAR (50)    NULL,
    [LaunchedDate]                   DATETIME        NULL,
    [MobPreSales]                    VARCHAR (100)   NULL,
    [MobPostSales]                   VARCHAR (100)   NULL,
    [MobReferences]                  VARCHAR (100)   NULL,
    [CustomDemoKits]                 DECIMAL (18)    NULL,
    [Theatre]                        VARCHAR (50)    NULL,
    [OwnerEmail]                     VARCHAR (100)   NULL,
    [Status]                         VARCHAR (50)    NULL,
    [CoeAccount]                     VARCHAR (50)    NULL,
    [LastSyncDate]                   DATETIME        NULL,
    [P1N]                            VARCHAR (5)     NULL,
    [S3N]                            VARCHAR (5)     NULL,
    [OpReg]                          VARCHAR (5)     NULL,
    [ParentSTID]                     VARCHAR (50)    NULL,
    [Currency]                       VARCHAR (50)    NULL,
    [SubRegion]                      VARCHAR (50)    NULL,
    [CustomerType]                   VARCHAR (100)   NULL,
    [M5DBAccountID]                  VARCHAR (50)    NULL,
    [StateCode]                      VARCHAR (50)    NULL,
    [CountryCode]                    VARCHAR (50)    NULL,
    [CommitmentLevel]                VARCHAR (100)   NULL,
    [PartnerType]                    VARCHAR (100)   NULL,
    [PartnerStage]                   VARCHAR (100)   NULL,
    [TrustedIVAR]                    VARCHAR (50)    NULL,
    [RegionalPriceGroup]             VARCHAR (100)   NULL,
    [IVARCurrencyCode]               VARCHAR (100)   NULL,
    [IVARExchangeRate]               DECIMAL (18, 2) NULL,
    [CSDMA]                          VARCHAR (50)    NULL,
    [CloudChampionLevel]             VARCHAR (100)   NULL,
    [CloudCompLevel]                 VARCHAR (5)     NULL,
    [CountryTier]                    VARCHAR (5)     NULL,
    [ParentId]                       VARCHAR (50)    NULL,
    [STTerritory]                    VARCHAR (100)   NULL,
    CONSTRAINT [PK_RESELLER] PRIMARY KEY CLUSTERED ([SfdcId] ASC)
);


GO
GRANT SELECT
    ON OBJECT::[dbo].[RESELLER] TO [CANDY\brobison]
    AS [dbo];

