CREATE TABLE [dbo].[RMA_AX_DETAIL] (
    [OrderDate]             DATETIME         NULL,
    [RequestedShipDate]     DATETIME         NULL,
    [CustomerPo]            NVARCHAR (50)    COLLATE Latin1_General_CI_AS_KS NULL,
    [QmsQuoteNumber]        NVARCHAR (25)    COLLATE Latin1_General_CI_AS_KS NULL,
    [SalesOrder]            NVARCHAR (20)    COLLATE Latin1_General_CI_AS_KS NOT NULL,
    [OrigSalesOrder]        NVARCHAR (20)    COLLATE Latin1_General_CI_AS_KS NOT NULL,
    [OrderType]             NVARCHAR (10)    COLLATE Latin1_General_CI_AS_KS NULL,
    [Invoice]               NVARCHAR (20)    COLLATE Latin1_General_CI_AS_KS NOT NULL,
    [InvoiceDate]           DATETIME         NOT NULL,
    [BillTo]                NVARCHAR (40)    COLLATE Latin1_General_CI_AS_KS NULL,
    [CUSTGROUP]             NVARCHAR (30)    COLLATE Latin1_General_CI_AS_KS NULL,
    [BillToName]            NVARCHAR (100)   COLLATE Latin1_General_CI_AS_KS NULL,
    [BillToPartnerType]     NVARCHAR (60)    COLLATE Latin1_General_CI_AS_KS NULL,
    [CustShipTo]            NVARCHAR (40)    COLLATE Latin1_General_CI_AS_KS NULL,
    [EndCust]               NVARCHAR (40)    COLLATE Latin1_General_CI_AS_KS NULL,
    [EndCustName]           NVARCHAR (100)   COLLATE Latin1_General_CI_AS_KS NULL,
    [CustSoldTo]            NVARCHAR (40)    COLLATE Latin1_General_CI_AS_KS NULL,
    [InvoiceLineNum]        NUMERIC (28, 12) NOT NULL,
    [SoLineNum]             INT              NOT NULL,
    [StockCode]             NVARCHAR (40)    COLLATE Latin1_General_CI_AS_KS NOT NULL,
    [ItemGroupId]           NVARCHAR (30)    COLLATE Latin1_General_CI_AS_KS NULL,
    [ItemGroupName]         NVARCHAR (100)   COLLATE Latin1_General_CI_AS_KS NULL,
    [AxRevType]             INT              NULL,
    [SKU]                   NVARCHAR (20)    COLLATE Latin1_General_CI_AS_KS NULL,
    [Rev]                   NVARCHAR (30)    COLLATE Latin1_General_CI_AS_KS NULL,
    [ItemDesc]              NVARCHAR (1000)  COLLATE Latin1_General_CI_AS_KS NOT NULL,
    [CURRENCYCODE]          NVARCHAR (3)     COLLATE Latin1_General_CI_AS_KS NOT NULL,
    [PRICEUNIT]             NUMERIC (28, 12) NOT NULL,
    [QTY]                   NUMERIC (28, 12) NOT NULL,
    [PromoPrice]            NUMERIC (28, 12) NOT NULL,
    [DMMREFPRICE]           NUMERIC (28, 12) NOT NULL,
    [NetSalesUSD]           NUMERIC (28, 12) NOT NULL,
    [NetSalesLocalCurrency] NUMERIC (28, 12) NOT NULL,
    [ProfitCenter]          NVARCHAR (30)    COLLATE Latin1_General_CI_AS_KS NOT NULL,
    [Country]               NVARCHAR (30)    COLLATE Latin1_General_CI_AS_KS NOT NULL,
    [SalesArea]             NVARCHAR (30)    COLLATE Latin1_General_CI_AS_KS NULL,
    [LEDGERACCOUNT]         NVARCHAR (40)    COLLATE Latin1_General_CI_AS_KS NOT NULL,
    [Dept]                  NVARCHAR (30)    COLLATE Latin1_General_CI_AS_KS NOT NULL,
    [Purpose]               NVARCHAR (30)    COLLATE Latin1_General_CI_AS_KS NOT NULL,
    [ShipCity]              NVARCHAR (100)   COLLATE Latin1_General_CI_AS_KS NULL,
    [ShipPostalCode]        NVARCHAR (10)    COLLATE Latin1_General_CI_AS_KS NULL,
    [ShipState]             NVARCHAR (30)    COLLATE Latin1_General_CI_AS_KS NULL,
    [ShipCounty]            NVARCHAR (30)    COLLATE Latin1_General_CI_AS_KS NULL,
    [ShipCountry]           NVARCHAR (30)    COLLATE Latin1_General_CI_AS_KS NULL,
    [DiscountBase]          NUMERIC (28, 12) NULL,
    [DiscountVolume]        NUMERIC (28, 12) NULL,
    [DiscountCsat]          NUMERIC (28, 12) NULL,
    [DiscountVpa]           NUMERIC (28, 12) NULL,
    [DiscountType]          NVARCHAR (10)    COLLATE Latin1_General_CI_AS_KS NULL,
    [DiscountConcession]    NUMERIC (28, 12) NULL,
    [DiscountDemo]          NUMERIC (28, 12) NULL,
    [DiscountNewPartner]    NUMERIC (28, 12) NULL,
    [DiscountDollar]        INT              NULL,
    [SEMLINENUM]            INT              NOT NULL,
    [INVENTDIMID]           NVARCHAR (20)    COLLATE Latin1_General_CI_AS_KS NULL,
    [Serial]                NVARCHAR (20)    COLLATE Latin1_General_CI_AS_KS NULL,
    [SalesPoolId]           NVARCHAR (30)    COLLATE Latin1_General_CI_AS_KS NULL,
    [IVARName]              NVARCHAR (100)   COLLATE Latin1_General_CI_AS_KS NULL,
    [IVARId]                NVARCHAR (40)    COLLATE Latin1_General_CI_AS_KS NULL,
    [EndCustArea]           NVARCHAR (30)    COLLATE Latin1_General_CI_AS_KS NULL,
    [SemSbeParent]          NVARCHAR (20)    COLLATE Latin1_General_CI_AS_KS NULL,
    [SemSbeComp]            INT              NULL,
    [INVENTTRANSID]         NVARCHAR (20)    COLLATE Latin1_General_CI_AS_KS NULL,
    [BusinessLine]          NVARCHAR (255)   COLLATE Latin1_General_CI_AS_KS NULL,
    [Category]              NVARCHAR (255)   COLLATE Latin1_General_CI_AS_KS NULL,
    [MarketFamily]          VARCHAR (50)     COLLATE Latin1_General_CI_AS_KS NULL
);


GO
GRANT SELECT
    ON OBJECT::[dbo].[RMA_AX_DETAIL] TO [TacEngRole]
    AS [dbo];

