CREATE TABLE [dbo].[SFDC_DSAT] (
    [Created]                                  DATETIME       CONSTRAINT [DF_SFDC_DSAT_Created] DEFAULT (getdate()) NULL,
    [Id]                                       NVARCHAR (255) NOT NULL,
    [Defect_Management__c]                     NVARCHAR (255) NULL,
    [Did_Mitel_meet_SLA_s__c]                  NVARCHAR (255) NULL,
    [DSAT_Analysis__c]                         NVARCHAR (255) NULL,
    [DSAT_due_to_defect__c]                    NVARCHAR (255) NULL,
    [DSAT_Outside_Factors__c]                  NVARCHAR (255) NULL,
    [Primary_Comment__c]                       TEXT           NULL,
    [Is_DSAT_due_to_outside_factors__c]        NVARCHAR (255) NULL,
    [Level_of_Partner_Engagement__c]           NVARCHAR (255) NULL,
    [Manager_Lead_Feeback__c]                  TEXT           NULL,
    [Name]                                     NVARCHAR (255) NULL,
    [Primary_DSAT_Sub_Trigger_Cause__c]        NVARCHAR (255) NULL,
    [Primary_DSAT_Trigger_Cause__c]            NVARCHAR (255) NULL,
    [Reason_For_No_Contact_Details__c]         NVARCHAR (255) NULL,
    [Reason_For_No_Contact__c]                 NVARCHAR (255) NULL,
    [RecordType]                               NVARCHAR (255) NULL,
    [Status__c]                                NVARCHAR (255) NULL,
    [System_functional_since_Activation__c]    NVARCHAR (255) NULL,
    [Training_Need_1__c]                       NVARCHAR (255) NULL,
    [Training_Need_2__c]                       NVARCHAR (255) NULL,
    [Traning_Required__c]                      NVARCHAR (255) NULL,
    [Was_a_Partner_involved_in_the_project__c] NVARCHAR (255) NULL,
    [Reached_out_to_Customer_Partner__c]       NVARCHAR (255) NULL,
    [OwnerId]                                  NVARCHAR (255) NULL,
    [CreatedBy]                                NVARCHAR (255) NULL,
    [LastModifiedBy]                           NVARCHAR (255) NULL,
    [CreatedDate]                              DATETIME       NULL,
    [LastModifiedDate]                         DATETIME       NULL,
    CONSTRAINT [PK_SFDC_DSAT] PRIMARY KEY CLUSTERED ([Id] ASC)
);

