CREATE TABLE [dbo].[SFDC_TASKFEED_TASK] (
    [CreatedDate]                                          DATETIME      NULL,
    [Id]                                                   VARCHAR (18)  NOT NULL,
    [Name]                                                 VARCHAR (80)  NULL,
    [taskfeed1__Pc_Subtasks_Complete__c]                   FLOAT (53)    NULL,
    [taskfeed1__Account__c]                                VARCHAR (18)  NULL,
    [taskfeed1__Active__c]                                 FLOAT (53)    NULL,
    [taskfeed1__Active_Date__c]                            DATETIME      NULL,
    [taskfeed1__Blocked__c]                                FLOAT (53)    NULL,
    [taskfeed1__Board__c]                                  VARCHAR (18)  NULL,
    [taskfeed1__Board_Type__c]                             VARCHAR (50)  NULL,
    [Case__c]                                              VARCHAR (18)  NULL,
    [taskfeed1__Category__c]                               VARCHAR (18)  NULL,
    [taskfeed1__Checklist_Items__c]                        FLOAT (53)    NULL,
    [taskfeed1__Checklist_Items_Template__c]               TEXT          NULL,
    [taskfeed1__Complete__c]                               FLOAT (53)    NULL,
    [taskfeed1__Complete_Date__c]                          DATETIME      NULL,
    [taskfeed1__Completed_Checklist_Items__c]              FLOAT (53)    NULL,
    [taskfeed1__Contributor_Aliases__c]                    VARCHAR (72)  NULL,
    [taskfeed1__Contributor_Ids__c]                        VARCHAR (255) NULL,
    [taskfeed1__Contributor_Manager_Ids__c]                VARCHAR (255) NULL,
    [taskfeed1__Contributor_Role_Initials__c]              VARCHAR (20)  NULL,
    [taskfeed1__Contributor_Role_Placeholders_Template__c] VARCHAR (255) NULL,
    [taskfeed1__Contributor_Roles__c]                      VARCHAR (255) NULL,
    [taskfeed1__Contributors__c]                           FLOAT (53)    NULL,
    [taskfeed1__Contributor_Unassigned_Roles__c]           VARCHAR (255) NULL,
    [taskfeed1__Created_By_Me__c]                          FLOAT (53)    NULL,
    [taskfeed1__Days_Remaining__c]                         FLOAT (53)    NULL,
    [taskfeed1__Decay__c]                                  FLOAT (53)    NULL,
    [taskfeed1__Decay_Warning_Amber__c]                    FLOAT (53)    NULL,
    [taskfeed1__Decay_Warning_Red__c]                      FLOAT (53)    NULL,
    [taskfeed1__Detail__c]                                 TEXT          NULL,
    [taskfeed1__Due_Date__c]                               DATETIME      NULL,
    [taskfeed1__Duration__c]                               FLOAT (53)    NULL,
    [taskfeed1__End_Date__c]                               DATETIME      NULL,
    [taskfeed1__End_Date_Baseline__c]                      DATETIME      NULL,
    [taskfeed1__End_Variance__c]                           FLOAT (53)    NULL,
    [taskfeed1__Estimated_Hours__c]                        FLOAT (53)    NULL,
    [taskfeed1__Internal__c]                               FLOAT (53)    NULL,
    [taskfeed1__Is_Parent__c]                              FLOAT (53)    NULL,
    [taskfeed1__Is_Subtask__c]                             FLOAT (53)    NULL,
    [taskfeed1__Lead_Lag__c]                               FLOAT (53)    NULL,
    [taskfeed1__Lock_Due_Date__c]                          DATETIME      NULL,
    [taskfeed1__Move_Due_Date_with_End_Date__c]            FLOAT (53)    NULL,
    [taskfeed1__My_Task__c]                                FLOAT (53)    NULL,
    [taskfeed1__My_Teams_Task__c]                          FLOAT (53)    NULL,
    [taskfeed1__Completed_Subtasks__c]                     FLOAT (53)    NULL,
    [taskfeed1__Subtasks__c]                               FLOAT (53)    NULL,
    [taskfeed1__Open__c]                                   VARCHAR (255) NULL,
    [taskfeed1__Opportunity__c]                            VARCHAR (18)  NULL,
    [taskfeed1__Order__c]                                  FLOAT (53)    NULL,
    [taskfeed1__Board_Order__c]                            FLOAT (53)    NULL,
    [taskfeed1__Owner__c]                                  VARCHAR (18)  NULL,
    [taskfeed1__Parent_Reference__c]                       VARCHAR (255) NULL,
    [taskfeed1__Parent__c]                                 VARCHAR (18)  NULL,
    [taskfeed1__Predecessor_Reference__c]                  VARCHAR (255) NULL,
    [taskfeed1__Predecessor_Task__c]                       VARCHAR (18)  NULL,
    [taskfeed1__Predecessor_Task_Complete__c]              FLOAT (53)    NULL,
    [taskfeed1__Ready__c]                                  FLOAT (53)    NULL,
    [taskfeed1__Ready_Date__c]                             DATETIME      NULL,
    [taskfeed1__Reference2__c]                             VARCHAR (255) NULL,
    [taskfeed1__Remaining_Hours__c]                        FLOAT (53)    NULL,
    [taskfeed1__Repeated_Task__c]                          FLOAT (53)    NULL,
    [taskfeed1__Set_Baseline__c]                           FLOAT (53)    NULL,
    [taskfeed1__Stage__c]                                  VARCHAR (50)  NULL,
    [taskfeed1__Start_Date__c]                             DATETIME      NULL,
    [taskfeed1__Start_DateTime__c]                         DATETIME      NULL,
    [taskfeed1__Start_Date_Baseline__c]                    DATETIME      NULL,
    [taskfeed1__Start_Variance__c]                         FLOAT (53)    NULL,
    [taskfeed1__Recorded_Hours__c]                         FLOAT (53)    NULL,
    [taskfeed1__Total_Feed_Posts__c]                       FLOAT (53)    NULL,
    [taskfeed1__Version__c]                                FLOAT (53)    NULL,
    [taskfeed1__Version_Date__c]                           DATETIME      NULL,
    [isDeleted]                                            INT           CONSTRAINT [DF_SFDC_TASKFEED_TASK_isDeleted] DEFAULT ((0)) NULL,
    [taskfeed1__List__c]                                   VARCHAR (18)  NULL,
    [ListStatus]                                           VARCHAR (25)  NULL,
    CONSTRAINT [PK_SFDC_TASKFEED_TASK] PRIMARY KEY CLUSTERED ([Id] ASC)
);

