CREATE TABLE [dbo].[SFDC_TASKFEED_BOARD] (
    [Created]                                 DATETIME      NULL,
    [Id]                                      VARCHAR (18)  NOT NULL,
    [Name]                                    VARCHAR (80)  NULL,
    [Project_Number__c]                       VARCHAR (18)  NULL,
    [OwnerId]                                 VARCHAR (18)  NULL,
    [taskfeed1__Pc_Complete__c]               FLOAT (53)    NULL,
    [taskfeed1__Account__c]                   VARCHAR (18)  NULL,
    [taskfeed1__Decays_Warning_Amber__c]      FLOAT (53)    NULL,
    [taskfeed1__Decays_Warning_Red__c]        FLOAT (53)    NULL,
    [Delay_Reason__c]                         VARCHAR (50)  NULL,
    [taskfeed1__Duration__c]                  FLOAT (53)    NULL,
    [taskfeed1__End_Date__c]                  DATETIME      NULL,
    [taskfeed1__End_Date_Baseline__c]         DATETIME      NULL,
    [taskfeed1__End_Variance__c]              FLOAT (53)    NULL,
    [taskfeed1__Is_Complete__c]               FLOAT (53)    NULL,
    [Location__c]                             VARCHAR (18)  NULL,
    [taskfeed1__Number_of_Completed_Tasks__c] FLOAT (53)    NULL,
    [taskfeed1__Number_of_Lists__c]           FLOAT (53)    NULL,
    [taskfeed1__Number_of_Tasks__c]           FLOAT (53)    NULL,
    [taskfeed1__Opportunity__c]               VARCHAR (18)  NULL,
    [taskfeed1__Set_Baseline__c]              FLOAT (53)    NULL,
    [taskfeed1__Stage__c]                     VARCHAR (50)  NULL,
    [taskfeed1__Start_Date__c]                DATETIME      NULL,
    [taskfeed1__Start_Date_Baseline__c]       DATETIME      NULL,
    [taskfeed1__Start_Variance__c]            FLOAT (53)    NULL,
    [taskfeed1__Status_Overview__c]           VARCHAR (50)  NULL,
    [taskfeed1__Task_Limit_Count__c]          FLOAT (53)    NULL,
    [taskfeed1__Type__c]                      VARCHAR (50)  NULL,
    [boss_location_id__c]                     VARCHAR (8)   NULL,
    [M5DB_Account_ID__c]                      VARCHAR (8)   NULL,
    [isDeleted]                               INT           NULL,
    [Delay_Reason_Details__c]                 TEXT          NULL,
    [taskfeed1__Color__c]                     VARCHAR (10)  NULL,
    [LastModifiedDate]                        DATETIME      NULL,
    [Notes]                                   VARCHAR (MAX) NULL,
    [TF_External_Sharing]                     VARCHAR (25)  NULL,
    [PRAScore]                                VARCHAR (15)  NULL,
    CONSTRAINT [PK_SFDC_TASKFEED_BOARD] PRIMARY KEY CLUSTERED ([Id] ASC)
);

