CREATE TABLE [dbo].[SFDC_PRODUCT_DUPCHECK] (
    [Created]     DATETIME      CONSTRAINT [DF_SFDC_PRODUCT_DUPCHECK_Created] DEFAULT (getdate()) NULL,
    [Id]          VARCHAR (20)  NOT NULL,
    [Sku]         VARCHAR (50)  NULL,
    [Description] VARCHAR (500) NULL,
    [Deleted]     NVARCHAR (15) CONSTRAINT [DF_SFDC_PRODUCT_DUPCHECK_Deleted] DEFAULT (N'false') NULL,
    CONSTRAINT [PK_SFDC_PRODUCT_DUPCHECK] PRIMARY KEY CLUSTERED ([Id] ASC)
);

