CREATE TABLE [dbo].[SFDC_PRICEBOOK_ENTRY] (
    [PriceBookEntryId] VARCHAR (50)  NOT NULL,
    [PriceBookName]    VARCHAR (255) CONSTRAINT [DF_SFDC_PRICEBOOK_ENTRY_PriceBookName] DEFAULT ('Standard Price Book') NULL,
    [SKU]              VARCHAR (50)  NULL,
    CONSTRAINT [PK_SFDC_PRICEBOOK_ENTRY] PRIMARY KEY CLUSTERED ([PriceBookEntryId] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_SFDC_PRICEBOOK_ENTRY]
    ON [dbo].[SFDC_PRICEBOOK_ENTRY]([PriceBookName] ASC, [SKU] ASC);

