CREATE TABLE [dbo].[SKY_SFDC_USER_QUEUE] (
    [Created] DATETIME CONSTRAINT [DF_SKY_SFDC_USER_QUEUE_Created] DEFAULT (getdate()) NOT NULL,
    [Id]      INT      NOT NULL,
    [Msg]     TEXT     NULL,
    CONSTRAINT [PK_SKY_SFDC_USER_QUEUE] PRIMARY KEY CLUSTERED ([Id] ASC)
);

