CREATE TABLE [dbo].[SKY_SFDC_SERVICE_AUDIT] (
    [Id]    INT          IDENTITY (1, 1) NOT NULL,
    [CiId]  VARCHAR (50) NOT NULL,
    [SvcId] VARCHAR (50) NULL,
    [Error] TEXT         NULL,
    CONSTRAINT [PK_SKY_SFDC_SERVICE_AUDIT] PRIMARY KEY CLUSTERED ([Id] ASC)
);

