CREATE TABLE [dbo].[SKY_NPS_SVY_RAW] (
    [Created] DATETIME CONSTRAINT [DF_SKY_NPS_SVY_RAW_Created] DEFAULT (getdate()) NULL,
    [Id]      INT      NOT NULL,
    [Field2]  TEXT     NULL,
    [Field3]  TEXT     NULL,
    [Field4]  TEXT     NULL,
    [Field5]  TEXT     NULL,
    [Field6]  TEXT     NULL,
    [Field7]  TEXT     NULL,
    [Field8]  TEXT     NULL,
    [Field9]  TEXT     NULL,
    [Field10] TEXT     NULL,
    [Field11] TEXT     NULL,
    [Field12] TEXT     NULL,
    [Field13] TEXT     NULL,
    [Field14] TEXT     NULL,
    [Field15] TEXT     NULL,
    [Field16] TEXT     NULL,
    [Field17] TEXT     NULL,
    [Field18] TEXT     NULL,
    [Field19] TEXT     NULL,
    [Field20] TEXT     NULL,
    [Field21] TEXT     NULL,
    [Field22] TEXT     NULL,
    [Field23] TEXT     NULL,
    [Field24] TEXT     NULL,
    [Field25] TEXT     NULL,
    [Field26] TEXT     NULL,
    [Field27] TEXT     NULL,
    [Field28] TEXT     NULL,
    [Field29] TEXT     NULL,
    [Field30] TEXT     NULL,
    [Field31] TEXT     NULL,
    [Field32] TEXT     NULL,
    [Field33] TEXT     NULL,
    [Field34] TEXT     NULL,
    [Field35] TEXT     NULL,
    [Field36] TEXT     NULL,
    [Field37] TEXT     NULL,
    [Field38] TEXT     NULL,
    [Field39] TEXT     NULL,
    [Field40] TEXT     NULL,
    [Field41] TEXT     NULL,
    [Field42] TEXT     NULL,
    [Field43] TEXT     NULL,
    [Field44] TEXT     NULL,
    [Field45] TEXT     NULL,
    [Field46] TEXT     NULL,
    [Field47] TEXT     NULL,
    [Field48] TEXT     NULL,
    [Field49] TEXT     NULL,
    [Field50] TEXT     NULL,
    [Field51] TEXT     NULL,
    [Field52] TEXT     NULL,
    [Field53] TEXT     NULL,
    [Field54] TEXT     NULL,
    [Field55] TEXT     NULL,
    [Field56] TEXT     NULL,
    [Field57] TEXT     NULL,
    [Field58] TEXT     NULL,
    [Field59] TEXT     NULL,
    [Field60] TEXT     NULL,
    [Field61] TEXT     NULL,
    [Field62] TEXT     NULL,
    [Field63] TEXT     NULL,
    [Field64] TEXT     NULL,
    [Field65] TEXT     NULL,
    [Field66] TEXT     NULL,
    [Field67] TEXT     NULL,
    [Field68] TEXT     NULL,
    [Field69] TEXT     NULL,
    [Field70] TEXT     NULL,
    [Field71] TEXT     NULL,
    [Field72] TEXT     NULL,
    [Field73] TEXT     NULL,
    [Field74] TEXT     NULL,
    [Field75] TEXT     NULL,
    [Field76] TEXT     NULL,
    [Field77] TEXT     NULL,
    [Field78] TEXT     NULL,
    [Field79] TEXT     NULL,
    [Field80] TEXT     NULL,
    [Field81] TEXT     NULL,
    [Field82] TEXT     NULL,
    [Field83] TEXT     NULL,
    [Field84] TEXT     NULL,
    [Field85] TEXT     NULL,
    [Field86] TEXT     NULL,
    [Field87] TEXT     NULL,
    [Field88] TEXT     NULL,
    [Field89] TEXT     NULL,
    [Field90] TEXT     NULL,
    [Field91] TEXT     NULL,
    [Field92] TEXT     NULL,
    [Field93] TEXT     NULL,
    [Field94] TEXT     NULL,
    [Field95] TEXT     NULL,
    [Field96] TEXT     NULL,
    [Field97] TEXT     NULL,
    [Error]   TEXT     NULL,
    CONSTRAINT [PK_SKY_NPS_SVY_RAW] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
GRANT SELECT
    ON OBJECT::[dbo].[SKY_NPS_SVY_RAW] TO [CsatData]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[SKY_NPS_SVY_RAW] TO [SKY_SFDC]
    AS [dbo];

