CREATE TABLE [dbo].[SKY_SVC_ERROR] (
    [Created]             DATETIME       NULL,
    [Id]                  INT            IDENTITY (1, 1) NOT NULL,
    [CiId]                VARCHAR (50)   NOT NULL,
    [M5DBServiceId]       FLOAT (53)     NULL,
    [ServiceId]           NVARCHAR (255) NULL,
    [LichenServiceId]     FLOAT (53)     NULL,
    [Accountid]           NVARCHAR (255) NULL,
    [LocationId]          NVARCHAR (255) NULL,
    [Class]               NVARCHAR (255) NULL,
    [Name]                VARCHAR (255)  NULL,
    [Status]              NVARCHAR (255) NULL,
    [OrderId]             FLOAT (53)     NULL,
    [Invoiced]            FLOAT (53)     NULL,
    [MRR]                 FLOAT (53)     NULL,
    [NRC]                 FLOAT (53)     NULL,
    [ProductId]           FLOAT (53)     NULL,
    [DateCreatedOriginal] VARCHAR (50)   NULL,
    [DateFoc]             VARCHAR (50)   NULL,
    [DateLiveActual]      VARCHAR (50)   NULL,
    [DateClosed]          VARCHAR (50)   NULL,
    [DateBillingStart]    VARCHAR (50)   NULL,
    [DateBillingStopped]  VARCHAR (50)   NULL,
    [DateOrdered]         VARCHAR (50)   NULL,
    [CloseOrderId]        FLOAT (53)     NULL,
    [CarrierName]         NVARCHAR (255) NULL,
    [CarrierId]           NVARCHAR (255) NULL,
    [LastModifiedBy]      NVARCHAR (255) NULL,
    [Owner]               NVARCHAR (255) NULL,
    [ErrStatus]           CHAR (1)       NULL,
    [ErrorTxt]            TEXT           NULL
);

