CREATE TABLE [dbo].[SSC_CUSTLIST] (
    [VAD_ID]                       VARCHAR (50)    NULL,
    [VAR_ID]                       VARCHAR (50)    NULL,
    [VAR]                          VARCHAR (100)   NULL,
    [CustomerId]                   VARCHAR (50)    NULL,
    [CustomerName]                 VARCHAR (100)   NOT NULL,
    [ADDR]                         VARCHAR (300)   NULL,
    [ADDR_LINE_2]                  INT             NULL,
    [CITY]                         VARCHAR (100)   NULL,
    [STATE]                        VARCHAR (50)    NULL,
    [ZIPCODE]                      VARCHAR (50)    NULL,
    [COUNTRY]                      VARCHAR (100)   NULL,
    [SupportType]                  NVARCHAR (255)  NULL,
    [ExpireDate]                   DATETIME        NULL,
    [AgreeNum]                     INT             NULL,
    [discountType]                 VARCHAR (50)    NULL,
    [preApprovedDiscount]          DECIMAL (18, 2) NULL,
    [receivingPartnerDiscPercent]  DECIMAL (18, 2) NULL,
    [origPartnerDiscCreditPercent] DECIMAL (18, 2) NULL,
    [VarAddr]                      VARCHAR (255)   NULL,
    [VarAddr2]                     INT             NULL,
    [VarCity]                      VARCHAR (100)   NULL,
    [VarState]                     VARCHAR (50)    NULL,
    [VarZip]                       VARCHAR (50)    NULL,
    [VarCountry]                   VARCHAR (100)   NULL,
    [Build]                        VARCHAR (50)    NULL,
    [SupportSKU]                   VARCHAR (50)    NULL,
    [PriContactFirstName]          VARCHAR (100)   NULL,
    [PriContactLastName]           VARCHAR (100)   NULL,
    [PriContactEmail]              VARCHAR (50)    NULL
);

