CREATE TABLE [dbo].[TABLEAU_B_SFDC_LEADS] (
    [CampaignName]               VARCHAR (200) NULL,
    [CampaignStatus]             VARCHAR (50)  NULL,
    [CampaignType]               VARCHAR (50)  NULL,
    [CampaignActivityType]       VARCHAR (50)  NULL,
    [CampaignSource]             VARCHAR (50)  NULL,
    [ProductSuite]               VARCHAR (50)  NULL,
    [Team]                       VARCHAR (150) NULL,
    [LeadOwner]                  VARCHAR (200) NULL,
    [LeadOwnerRoleName]          VARCHAR (255) NULL,
    [LeadOwnerManager]           VARCHAR (200) NULL,
    [CreatedDate]                DATETIME      NULL,
    [LeadSetBy]                  VARCHAR (200) NULL,
    [BANTDate]                   DATETIME      NULL,
    [LeadSource]                 VARCHAR (200) NULL,
    [LeadScore]                  VARCHAR (50)  NULL,
    [LeadStatus]                 VARCHAR (200) NULL,
    [CustomerSegment]            VARCHAR (50)  NULL,
    [LeadName]                   VARCHAR (200) NULL,
    [City]                       VARCHAR (200) NULL,
    [STATE]                      VARCHAR (200) NULL,
    [Country]                    VARCHAR (200) NULL,
    [LeadId]                     VARCHAR (200) NULL,
    [Company]                    VARCHAR (255) NULL,
    [IsConverted]                BIT           NULL,
    [ConvertedDate]              DATETIME      NULL,
    [OpportunityName]            VARCHAR (255) NULL,
    [OpportunityOwner]           VARCHAR (200) NULL,
    [OpportunityOwnerRole]       VARCHAR (255) NULL,
    [OpportunityStage]           VARCHAR (50)  NULL,
    [OpportunityIsClosed]        VARCHAR (50)  NULL,
    [OpportunityCloseDate]       DATETIME      NULL,
    [CloudTCV]                   VARCHAR (50)  NULL,
    [MemberFirstAssociatedDate]  DATETIME      NULL,
    [MemberId]                   VARCHAR (20)  NOT NULL,
    [LeadRating]                 VARCHAR (50)  NULL,
    [LeadRegion]                 VARCHAR (50)  NULL,
    [LeadSubRegion]              VARCHAR (50)  NULL,
    [LeadAge]                    FLOAT (53)    NULL,
    [LeadStatusAge]              FLOAT (53)    NULL,
    [PrimaryPartner]             VARCHAR (255) NULL,
    [PrimaryDistributor]         VARCHAR (255) NULL,
    [SubAgent]                   VARCHAR (255) NULL,
    [OpportunityType]            VARCHAR (50)  NULL,
    [DealType]                   VARCHAR (50)  NULL,
    [ProductSuiteCategory]       VARCHAR (255) NULL,
    [OpportunityTerritory]       VARCHAR (50)  NULL,
    [ProductInterest]            VARCHAR (255) NULL,
    [BookingAmount]              FLOAT (53)    NULL,
    [TimeToTouch]                VARCHAR (50)  NULL,
    [LeadDisqualificationReason] VARCHAR (150) NULL,
    [OpportunityId]              VARCHAR (25)  NULL,
    [LinkType]                   VARCHAR (7)   NOT NULL,
    [OppCreatedBy]               VARCHAR (150) NULL,
    [ForecastCategory]           VARCHAR (100) NULL,
    [DistyOppValue]              FLOAT (53)    NULL,
    [BookingAmount_Converted]    FLOAT (53)    NULL,
    [DistyOppValue_Converted]    FLOAT (53)    NULL,
    [Description]                VARCHAR (MAX) NULL,
    [ReportedChannelPartner]     VARCHAR (255) NULL,
    [Email]                      VARCHAR (250) NULL
);

