CREATE TABLE [dbo].[TABLEAU_B_SFDC_BIZ_ATTR_TOUCHPOINT] (
    [ID]                                             VARCHAR (18)  NOT NULL,
    [BIZIBLE2__ACCOUNT__C]                           VARCHAR (18)  NULL,
    [BIZIBLE2__AD_CAMPAIGN_ID__C]                    VARCHAR (60)  NULL,
    [BIZIBLE2__AD_CAMPAIGN_NAME__C]                  VARCHAR (108) NULL,
    [BIZIBLE2__AD_CONTENT__C]                        VARCHAR (190) NULL,
    [BIZIBLE2__AD_DESTINATION_URL__C]                VARCHAR (255) NULL,
    [BIZIBLE2__AD_GROUP_ID__C]                       BIGINT        NULL,
    [BIZIBLE2__AD_GROUP_NAME__C]                     VARCHAR (34)  NULL,
    [BIZIBLE2__AD_ID__C]                             VARCHAR (60)  NULL,
    [BIZIBLE2__ATTRIBUTION_CUSTOM_MODEL_2__C]        REAL          NULL,
    [BIZIBLE2__ATTRIBUTION_CUSTOM_MODEL__C]          REAL          NULL,
    [BIZIBLE2__ATTRIBUTION_FIRST_TOUCH__C]           REAL          NULL,
    [BIZIBLE2__ATTRIBUTION_LEAD_CONVERSION_TOUCH__C] REAL          NULL,
    [BIZIBLE2__ATTRIBUTION_U_SHAPED__C]              REAL          NULL,
    [BIZIBLE2__ATTRIBUTION_W_SHAPED__C]              REAL          NULL,
    [BIZIBLE2__BROWSER__C]                           VARCHAR (15)  NULL,
    [BIZIBLE2__CONTACT__C]                           VARCHAR (18)  NULL,
    [BIZIBLE2__COUNT_CUSTOM_MODEL_2__C]              REAL          NULL,
    [BIZIBLE2__COUNT_CUSTOM_MODEL__C]                REAL          NULL,
    [BIZIBLE2__COUNT_FIRST_TOUCH__C]                 REAL          NULL,
    [BIZIBLE2__COUNT_LEAD_CREATION_TOUCH__C]         REAL          NULL,
    [BIZIBLE2__COUNT_U_SHAPED__C]                    REAL          NULL,
    [BIZIBLE2__COUNT_W_SHAPED__C]                    REAL          NULL,
    [BIZIBLE2__FORM_URL_RAW__C]                      VARCHAR (255) NULL,
    [BIZIBLE2__FORM_URL__C]                          VARCHAR (130) NULL,
    [BIZIBLE2__GEO_CITY__C]                          VARCHAR (39)  NULL,
    [BIZIBLE2__GEO_COUNTRY__C]                       VARCHAR (27)  NULL,
    [BIZIBLE2__GEO_REGION__C]                        VARCHAR (47)  NULL,
    [BIZIBLE2__KEYWORD_ID__C]                        VARCHAR (59)  NULL,
    [BIZIBLE2__KEYWORD_MATCHTYPE__C]                 VARCHAR (6)   NULL,
    [BIZIBLE2__KEYWORD_TEXT__C]                      VARCHAR (51)  NULL,
    [BIZIBLE2__LANDING_PAGE_RAW__C]                  VARCHAR (255) NULL,
    [BIZIBLE2__LANDING_PAGE__C]                      VARCHAR (165) NULL,
    [BIZIBLE2__MARKETING_CHANNEL_PATH__C]            VARCHAR (21)  NULL,
    [BIZIBLE2__MARKETING_CHANNEL__C]                 VARCHAR (19)  NULL,
    [BIZIBLE2__MEDIUM__C]                            VARCHAR (32)  NULL,
    [BIZIBLE2__OPPORTUNITY__C]                       VARCHAR (18)  NULL,
    [BIZIBLE2__PLACEMENT_ID__C]                      VARCHAR (255) NULL,
    [BIZIBLE2__PLACEMENT_NAME__C]                    VARCHAR (255) NULL,
    [BIZIBLE2__PLATFORM__C]                          VARCHAR (14)  NULL,
    [BIZIBLE2__REFERRER_PAGE_RAW__C]                 VARCHAR (255) NULL,
    [BIZIBLE2__REFERRER_PAGE__C]                     VARCHAR (255) NULL,
    [BIZIBLE2__REVENUE_CUSTOM_MODEL_2__C]            REAL          NULL,
    [BIZIBLE2__REVENUE_CUSTOM_MODEL__C]              REAL          NULL,
    [BIZIBLE2__REVENUE_FIRST_TOUCH__C]               REAL          NULL,
    [BIZIBLE2__REVENUE_LEAD_CONVERSION__C]           REAL          NULL,
    [BIZIBLE2__REVENUE_U_SHAPED__C]                  REAL          NULL,
    [BIZIBLE2__REVENUE_W_SHAPED__C]                  REAL          NULL,
    [BIZIBLE2__SEARCH_PHRASE__C]                     VARCHAR (96)  NULL,
    [BIZIBLE2__SEGMENT__C]                           VARCHAR (91)  NULL,
    [BIZIBLE2__SF_CAMPAIGN__C]                       VARCHAR (18)  NULL,
    [BIZIBLE2__SITE_ID__C]                           VARCHAR (255) NULL,
    [BIZIBLE2__SITE_NAME__C]                         VARCHAR (255) NULL,
    [BIZIBLE2__TOUCHPOINT_DATE__C]                   VARCHAR (50)  NULL,
    [BIZIBLE2__TOUCHPOINT_POSITION__C]               VARCHAR (255) NULL,
    [BIZIBLE2__TOUCHPOINT_SOURCE__C]                 VARCHAR (60)  NULL,
    [BIZIBLE2__TOUCHPOINT_TYPE__C]                   VARCHAR (10)  NULL,
    [BIZIBLE2__UNIQUEID__C]                          VARCHAR (83)  NULL,
    [CURRENCYISOCODE]                                VARCHAR (3)   NULL,
    [NAME]                                           VARCHAR (15)  NULL,
    [OWNERID]                                        VARCHAR (18)  NULL
);

