CREATE TABLE [dbo].[Test_MiCC_Group] (
    [Source]                                        VARCHAR (4)    NOT NULL,
    [Created]                                       DATETIME       NULL,
    [ReportRecordId]                                NVARCHAR (50)  NULL,
    [ReportDate]                                    DATETIME       NULL,
    [ACDCallsAccepted]                              FLOAT (53)     NULL,
    [ACDCallsAnswered]                              FLOAT (53)     NULL,
    [ChatContactsAccepted]                          FLOAT (53)     NULL,
    [ChatContactsAnswered]                          FLOAT (53)     NULL,
    [EmailContactsAccepted]                         FLOAT (53)     NULL,
    [EmailContactsAnswered]                         FLOAT (53)     NULL,
    [AvgWaitTimeBeforeAnswered]                     DATETIME       NULL,
    [AvgWaitTimeInQueueOfCallsRequestedCallback]    DATETIME       NULL,
    [LongestWaitTimeBeforeAnswered]                 DATETIME       NULL,
    [LongestWaitTimeInQueueOfCallRequestedCallback] DATETIME       NULL,
    [AvgWaitTimeBeforeAnsweredOfChatContacts]       DATETIME       NULL,
    [CmltvWaitTimeBeforeAnsweredOfChatContacts]     DATETIME       NULL,
    [OutboundACDCallsAsAConsequenceOfCallback]      FLOAT (53)     NULL,
    [GroupID]                                       FLOAT (53)     NULL,
    [GroupName]                                     NVARCHAR (255) NULL,
    [TSFForIncomingACDCalls]                        FLOAT (53)     NULL,
    [LongestWaitTimeBeforeAnsweredChatContacts]     DATETIME       NULL,
    [PCTACDCallsAbandonedOfAcceptedCalls]           FLOAT (53)     NULL,
    [AvgTalkTimeACDCalls]                           DATETIME       NULL,
    [AvgNumberLoggedinAgents]                       FLOAT (53)     NULL,
    [MaximumNumberAgentsLoggedInSimultaneously]     FLOAT (53)     NULL,
    [ACDCallsAbandoned]                             FLOAT (53)     NULL,
    [ACDCallsRequestedCallbackWhileWaitingInQueue]  FLOAT (53)     NULL,
    [ACDCallsOverflowedInAndAnswered]               FLOAT (53)     NULL,
    [NumberOfCallsAnsweredWithinTASA]               FLOAT (53)     NULL,
    [CumulativeTalkTimeOfIncomingACDCalls]          DATETIME       NULL,
    [CumulativeWaitTimeBeforeAnsweredOfACDIncoming] DATETIME       NULL,
    [AvgWaitTimeBeforeAnsweredEmailContacts]        DATETIME       NULL,
    [LongestQueueTimeBeforeAnsweredEmailContacts]   DATETIME       NULL,
    [AvgInteractionTimeEmailContacts]               DATETIME       NULL,
    [CmltvTalkTimeACDCalls]                         DATETIME       NULL,
    [GlobalAggCmltvInteractionTimeEmailContacts]    DATETIME       NULL,
    [TSFEmailContacts]                              FLOAT (53)     NULL,
    [CmltvIntTimeEmailContacts]                     DATETIME       NULL
);

