CREATE TABLE [dbo].[tmpTF] (
    [Type]                                        VARCHAR (8)    NOT NULL,
    [BossLocationId]                              NVARCHAR (255) NULL,
    [DelayReason]                                 NVARCHAR (255) NULL,
    [DelayReasonDetails]                          TEXT           NULL,
    [TF_ProjectNumber]                            NVARCHAR (255) NULL,
    [TF_StartDate]                                DATETIME       NULL,
    [TF_EndDate]                                  DATETIME       NULL,
    [TF_Stage]                                    NVARCHAR (255) NULL,
    [TF_PctComplete]                              FLOAT (53)     NULL,
    [TaskFeedProjectManager]                      VARCHAR (500)  NULL,
    [OpportunityId]                               NVARCHAR (255) NULL,
    [OpportunityNumber]                           VARCHAR (100)  NULL,
    [TF Color Number]                             VARCHAR (25)   NULL,
    [TF Tsk Project Start Date Start Date]        DATETIME       NULL,
    [TF Tsk Project Start Date Sch End Date]      DATETIME       NULL,
    [TF Tsk Project Start Date Complete Date]     DATETIME       NULL,
    [TF Tsk Project Start Date Status]            VARCHAR (25)   NULL,
    [TF Board Sfdc Id]                            NVARCHAR (255) NOT NULL,
    [TF Tsk BRD Sign-Off Start Date]              DATETIME       NULL,
    [TF Tsk BRD Sign-Off End Date]                DATETIME       NULL,
    [TF Tsk BRD Sign-Off Complete Date]           DATETIME       NULL,
    [TF Tsk BRD Sign-Off Status]                  VARCHAR (25)   NULL,
    [TF Tsk Trans To Support Start Date]          DATETIME       NULL,
    [TF Tsk Trans To Support Sch End Date]        DATETIME       NULL,
    [TF Tsk Trans To Support Complete Date]       DATETIME       NULL,
    [TF Tsk Trans To Support Status]              VARCHAR (25)   NULL,
    [TF Board Last Modified]                      DATETIME       NULL,
    [TF Tsk Cust Audit Approval Start Date]       DATETIME       NULL,
    [TF Tsk Cust Audit Approval End Date]         DATETIME       NULL,
    [TF Tsk Cust Audit Approval Complete Date]    DATETIME       NULL,
    [TF Tsk Cust Audit Approval Status]           VARCHAR (25)   NULL,
    [Accelerated Timeline Initiative Update Date] DATETIME       NULL,
    [Accelerated Timeline Initiative Description] VARCHAR (MAX)  NULL,
    [TF Tsk Port In Research Start Date]          DATETIME       NULL,
    [TF Tsk Port In Research End Date]            DATETIME       NULL,
    [TF Tsk Port In Research Complete Date]       DATETIME       NULL,
    [TF Tsk Port In Research Status]              VARCHAR (25)   NULL,
    [TF Tsk Order New Numbers Start Date]         DATETIME       NULL,
    [TF Tsk Order New Numbers End Date]           DATETIME       NULL,
    [TF Tsk Order New Numbers Complete Date]      DATETIME       NULL,
    [TF Tsk Order New Numbers Status]             VARCHAR (25)   NULL,
    [TF Tsk Order Hardware Start Date]            DATETIME       NULL,
    [TF Tsk Order Hardware End Date]              DATETIME       NULL,
    [TF Tsk Order Hardware Complete Date]         DATETIME       NULL,
    [TF Tsk Order Hardware Status]                VARCHAR (25)   NULL,
    [TF Tsk Port Submitted Start Date]            DATETIME       NULL,
    [TF Tsk Port Submitted End Date]              DATETIME       NULL,
    [TF Tsk Port Submitted Complete Date]         DATETIME       NULL,
    [TF Tsk Port Submitted Status]                VARCHAR (25)   NULL,
    [TF Tsk System Programming Start Date]        DATETIME       NULL,
    [TF Tsk System Programming End Date]          DATETIME       NULL,
    [TF Tsk System Programming Complete Date]     DATETIME       NULL,
    [TF Tsk System Programming Status]            VARCHAR (25)   NULL,
    [TF Tsk Ready To Test Start Date]             DATETIME       NULL,
    [TF Tsk Ready To Test End Date]               DATETIME       NULL,
    [TF Tsk Ready To Test Complete Date]          DATETIME       NULL,
    [TF Tsk Ready To Test Status]                 VARCHAR (25)   NULL,
    [TF Tsk Port Scheduled Start Date]            DATETIME       NULL,
    [TF Tsk Port Scheduled End Date]              DATETIME       NULL,
    [TF Tsk Port Scheduled Complete Date]         DATETIME       NULL,
    [TF Tsk Port Scheduled Status]                VARCHAR (25)   NULL,
    [TF Tsk Pre Go Live Testing Start Date]       DATETIME       NULL,
    [TF Tsk Pre Go Live Testing End Date]         DATETIME       NULL,
    [TF Tsk Pre Go Live Testing Compelte Date]    DATETIME       NULL,
    [TF Tsk Pre Go Live Testing Status]           VARCHAR (25)   NULL,
    [TaskfeedBoardType]                           NVARCHAR (255) NULL,
    [TF Tsk Net Readiness Start Date]             DATETIME       NULL,
    [TF Tsk Net Readiness End Date]               DATETIME       NULL,
    [TF Tsk Net Readiness Complete Date]          DATETIME       NULL,
    [TF Tsk Net Readiness Status]                 VARCHAR (25)   NULL,
    [rn]                                          BIGINT         NULL
);

