CREATE TABLE [rate].[CarrierUSDomestic] (
    [RateId]                      INT          NOT NULL,
    [Carrier]                     VARCHAR (10) NULL,
    [Region]                      VARCHAR (5)  NULL,
    [NPA]                         VARCHAR (5)  NULL,
    [NXX]                         VARCHAR (5)  NULL,
    [BLOCK_ID]                    VARCHAR (5)  NULL,
    [LATA]                        VARCHAR (50) NULL,
    [OCN]                         VARCHAR (50) NULL,
    [DIAL_STRING]                 VARCHAR (50) NULL,
    [DESTINATION]                 VARCHAR (50) NULL,
    [OLD_RATE]                    REAL         NULL,
    [BASE_OLD_RATE]               REAL         NULL,
    [OLD_RATE_EFFECTIVE_FROM]     DATETIME     NULL,
    [CURRENT_RATE]                REAL         NULL,
    [BASE_CURRENT_RATE]           REAL         NULL,
    [CURRENT_RATE_EFFECTIVE_FROM] DATETIME     NULL,
    [CURRENT_RATE_EFFECTIVE_TO]   DATETIME     NULL,
    [PENDING_RATE]                VARCHAR (32) NULL,
    [BASE_PENDING_RATE]           VARCHAR (32) NULL,
    [PENDING_RATE_EFFECTIVE_FROM] VARCHAR (50) NULL,
    [ACTIVE]                      BIT          NULL,
    [BILLING_MODEL]               SMALLINT     NULL,
    [BILLING_MODEL_STRING]        VARCHAR (16) NULL,
    [NOTIFICATION_SENT]           BIT          NULL,
    [AUTO_UPDATE_FLAG]            BIT          NULL,
    [IS_BLOCKED]                  BIT          NULL,
    [AUTO_UPDATE_FLAG_STATUS]     VARCHAR (32) NULL,
    [IS_BLOCKED_STATUS]           VARCHAR (10) NULL,
    [IS_DEACTIVATED]              BIT          NULL,
    [NOT_FOR_ROUTING]             BIT          NULL,
    [IS_FUTURE_OFFER]             BIT          NULL,
    [USER_STAMP]                  VARCHAR (50) NULL,
    [USER_TIME_LOG]               DATETIME     NULL,
    [OFFER_IS_ACTIVE]             VARCHAR (32) NULL,
    [CARRIER_CODES_ROUTING]       VARCHAR (16) NULL,
    [STATUS]                      VARCHAR (32) NULL
);

