CREATE TABLE [Santana].[additionalUserData_cleaned_7] (
    [cluster]                   VARCHAR (MAX) NULL,
    [subscriber_id]             VARCHAR (MAX) NULL,
    [tn]                        BIGINT        NULL,
    [cos_name]                  VARCHAR (MAX) NULL,
    [speed_line_config]         VARCHAR (MAX) NULL,
    [zero_out_component]        VARCHAR (MAX) NULL,
    [feature_screen]            VARCHAR (MAX) NULL,
    [feature_screen_script]     VARCHAR (MAX) NULL,
    [feature_cf_uncond]         VARCHAR (MAX) NULL,
    [feature_cf_noans]          VARCHAR (MAX) NULL,
    [feature_cf_noans_numrings] VARCHAR (MAX) NULL,
    [email_notification]        VARCHAR (MAX) NULL,
    [email_wav]                 VARCHAR (MAX) NULL,
    [dont_keep_vm]              VARCHAR (MAX) NULL,
    [vm_subscriber_ids]         VARCHAR (MAX) NULL,
    [att_id]                    VARCHAR (MAX) NULL,
    [email_notification_addr]   VARCHAR (MAX) NULL,
    [email_wav_addr]            VARCHAR (MAX) NULL,
    [shared_line_config]        VARCHAR (MAX) NULL,
    [cf_uncond_addr]            VARCHAR (MAX) NULL,
    [cf_noans_addr]             VARCHAR (MAX) NULL,
    [outbound_callerid_addr]    VARCHAR (MAX) NULL,
    [hcr_record_all]            VARCHAR (MAX) NULL,
    [hcr_control]               VARCHAR (MAX) NULL,
    [aliases]                   VARCHAR (MAX) NULL
);

