
/****** Script for SelectTopNRows command from SSMS  ******/


CREATE view [dbo].[V_TABLEAU_B_SFDC_BIZIBLE_EXTRA_SANKEY] as
-- MW 09232020 For Marketing Sankey viz
SELECT 
		'First' as Source
		,[BookingAmount_Converted (OP)]
		,[Contact Email (OP)]
		,[Create Date (OP)]
		,[CreatedBy (OP)]
		,[Description (L)]
		,[DistyOppValue_Converted (OP)]
		,[Email (L)]
		,[Forecast Region (OP)]
		,[ID (BP)]
		,[Joint Marketing Funds (OP)]
		,[Lead Disqualification Reason (L)]
		,[Lead Owner (L)]
		,[Lead Owner Role Name (L)]
		,[Lead Region (L)]
		,[Lead Sub Region (L)]
		,[Marketing Channel (BAT)]
		,[Marketing Channel (BT)]
		,[Marketing Channel Path (BAT)]
		,[Marketing Channel Path (BT)]
		,[Opportunity ID (BAT)]
		,[Opportunity Name (OP)]
		,[Opportunity Type (OP)]
		,[Owner Name (OP)]
		,[Owner Role Name (OP)]
		,[Primary Won Lost Reason (OP)]
		,[Products (OP)]
		,[Record Type (OP)]
		,[Reported Channel Partner (L)]
		,[Segment (BT)]
		,[SIC1]
		,[SIC1Description]
		,[SIC2]
		,[SIC2Description]
		,[SIC3]
		,[SIC3Description]
		,[SIC4Description]
		,[SicCode (OP)]
		,[SICIndustry1]
		,[SICIndustry2]
		,[Stage (OP)]
		,[Touchpoint Date (BAT)]
		,[Touchpoint Date (BT)]
		,[Touchpoint Position (BAT)]
		,[Touchpoint Position (BT)]
		,[Vertical (OP)]
		,[Opportunity ID (OP)] 
  FROM [dbo].[V_TABLEAU_B_SFDC_BIZIBLE_EXTRA]
  UNION ALL
  SELECT 
		'Second' as Source
		,[BookingAmount_Converted (OP)]
		,[Contact Email (OP)]
		,[Create Date (OP)]
		,[CreatedBy (OP)]
		,[Description (L)]
		,[DistyOppValue_Converted (OP)]
		,[Email (L)]
		,[Forecast Region (OP)]
		,[ID (BP)]
		,[Joint Marketing Funds (OP)]
		,[Lead Disqualification Reason (L)]
		,[Lead Owner (L)]
		,[Lead Owner Role Name (L)]
		,[Lead Region (L)]
		,[Lead Sub Region (L)]
		,[Marketing Channel (BAT)]
		,[Marketing Channel (BT)]
		,[Marketing Channel Path (BAT)]
		,[Marketing Channel Path (BT)]
		,[Opportunity ID (BAT)]
		,[Opportunity Name (OP)]
		,[Opportunity Type (OP)]
		,[Owner Name (OP)]
		,[Owner Role Name (OP)]
		,[Primary Won Lost Reason (OP)]
		,[Products (OP)]
		,[Record Type (OP)]
		,[Reported Channel Partner (L)]
		,[Segment (BT)]
		,[SIC1]
		,[SIC1Description]
		,[SIC2]
		,[SIC2Description]
		,[SIC3]
		,[SIC3Description]
		,[SIC4Description]
		,[SicCode (OP)]
		,[SICIndustry1]
		,[SICIndustry2]
		,[Stage (OP)]
		,[Touchpoint Date (BAT)]
		,[Touchpoint Date (BT)]
		,[Touchpoint Position (BAT)]
		,[Touchpoint Position (BT)]
		,[Vertical (OP)]
		,[Opportunity ID (OP)] 
  FROM [dbo].[V_TABLEAU_B_SFDC_BIZIBLE_EXTRA]
UNION ALL
SELECT 
		'Third' as Source
		,[BookingAmount_Converted (OP)]
		,[Contact Email (OP)]
		,[Create Date (OP)]
		,[CreatedBy (OP)]
		,[Description (L)]
		,[DistyOppValue_Converted (OP)]
		,[Email (L)]
		,[Forecast Region (OP)]
		,[ID (BP)]
		,[Joint Marketing Funds (OP)]
		,[Lead Disqualification Reason (L)]
		,[Lead Owner (L)]
		,[Lead Owner Role Name (L)]
		,[Lead Region (L)]
		,[Lead Sub Region (L)]
		,[Marketing Channel (BAT)]
		,[Marketing Channel (BT)]
		,[Marketing Channel Path (BAT)]
		,[Marketing Channel Path (BT)]
		,[Opportunity ID (BAT)]
		,[Opportunity Name (OP)]
		,[Opportunity Type (OP)]
		,[Owner Name (OP)]
		,[Owner Role Name (OP)]
		,[Primary Won Lost Reason (OP)]
		,[Products (OP)]
		,[Record Type (OP)]
		,[Reported Channel Partner (L)]
		,[Segment (BT)]
		,[SIC1]
		,[SIC1Description]
		,[SIC2]
		,[SIC2Description]
		,[SIC3]
		,[SIC3Description]
		,[SIC4Description]
		,[SicCode (OP)]
		,[SICIndustry1]
		,[SICIndustry2]
		,[Stage (OP)]
		,[Touchpoint Date (BAT)]
		,[Touchpoint Date (BT)]
		,[Touchpoint Position (BAT)]
		,[Touchpoint Position (BT)]
		,[Vertical (OP)]
		,[Opportunity ID (OP)] 
  FROM [dbo].[V_TABLEAU_B_SFDC_BIZIBLE_EXTRA]
