
CREATE VIEW dbo.V_Tableau_MRT
AS
SELECT [ID]
      ,[Status]
      ,[SubStatus]
      ,[ChangeList]
      ,[CorrectedInID]
      ,[CreatedBy]
      ,[CreatedByID]
      ,[CreatedDate]
      ,[DefectID]
      ,[DefectAbstract]
      ,[DeliveryVehicle]
      ,[DueDate]
      ,[Effort]
      ,[InKnowledgeBase]
      ,[LastModifiedBy]
      ,[LastModifiedByID]
      ,[LastModifiedDate]
      ,[MRTName]
      ,[QAAQAC]
      ,[RecordTypeID]
      ,[RejectedDate]
      ,[RelatedCases]
      ,[ResolvedDate]
      ,[ReviewedByID]
      ,[ReviewedDate]
      ,[Risk]
      ,[SEDefectNum]
      ,[TargetID]
      ,[TestEngineer]
      ,[TestEngineeremail]
      ,[VerifiedDate]
      ,[VerifiedIn]
  FROM [dbo].[MRT]
  where (MRTName LIKE '%Connect%' OR MRTName LIKE '%Mobility%' OR MRTName LIKE '%Cosmo%' OR MRTName LIKE '%Colorado%' OR MRTName LIKE '%Manhattan%' OR MRTName LIKE '%BOSS%' OR MRTName LIKE '%Highball%' OR MRTName LIKE '%Galileo%' OR MRTName LIKE '%TBD%' OR MRTName LIKE '%Link%' OR MRTName LIKE '%WB.2%' OR MRTName LIKE '%FRIS%' OR MRTName LIKE '%Fortuna%' OR MRTName LIKE '%Brazos%' OR MRTName LIKE '%IP400RR%' OR MRTName LIKE '%TwMobile%' OR MRTName LIKE '%TwWeb%' OR MRTName LIKE '%TwPlatform%' OR MRTName LIKE '%UCloud%' OR MRTName LIKE '%SCC%' OR MRTName LIKE '%3rd party%')
