CREATE VIEW [dbo].[V_Tableau_DefectManagement]
AS SELECT  [ID]
      ,[EngEngageNum]
      ,[Abstract]
      ,[Area]
      ,[Attachments]
      ,[Automation]
      ,[Build]
      ,[BuildID]
      ,[Challenge]
	 -- ,ClosedDate__c
      ,[CreatedBy]
      ,[CreatedByID]
      ,[CreatedByRole]
      ,[CreatedDate]
      ,[CriticalAccount]
      ,[DefectStatus]
      ,[Developer]
      ,[DeveloperID]
      ,[EngGroup]
      ,[ExtendedDescription]
      ,[FieldChallenge]
      ,[FieldIssues]
      ,[FoundID]
      ,[FoundName]
      ,[FoundVia]
      ,[Keywords]
      ,[LastModifiedBy]
      ,[LastModifiedByID]
      ,[LastModifiedDate]
      ,[MigratedFrom]
      ,[OpenMRTs]
      ,[Priority]
      ,[QAOwner]
      ,[QAOwnerID]
      ,[Reason]
      ,[RecordTypeID]
      ,[RelatedCaseID]
      ,[ResolutionDescription]
      ,[ResolvedMRTs]
      ,[SEDefectNum]
      ,[Severity]
      ,[SubArea]
	  --, Status__c
      ,[SubStatus]
      ,[TestCases]
      ,[TotalMRTs]
      ,[Type]
      ,[Version]
      ,[WorkOrder]
  FROM [dbo].[DefectManagement]

