


create view V_TEST_TAB AS
--test for tableau AWS. delete MW 11092020
SELECT [SFDC_TASKFEED_BOARD].[Created] AS [Created],
  [SFDC_TASKFEED_BOARD].[Id] AS [Id],
  [SFDC_TASKFEED_BOARD].[Name] AS [Name],
  [SFDC_TASKFEED_BOARD].[Project_Number__c] AS [Project_Number__c],
  [SFDC_TASKFEED_BOARD].[OwnerId] AS [OwnerId],
  [SFDC_TASKFEED_BOARD].[taskfeed1__Pc_Complete__c] AS [taskfeed1__Pc_Complete__c],
  [SFDC_TASKFEED_BOARD].[taskfeed1__Account__c] AS [taskfeed1__Account__c],
  [SFDC_TASKFEED_BOARD].[taskfeed1__Decays_Warning_Amber__c] AS [taskfeed1__Decays_Warning_Amber__c],
  [SFDC_TASKFEED_BOARD].[taskfeed1__Decays_Warning_Red__c] AS [taskfeed1__Decays_Warning_Red__c],
  [SFDC_TASKFEED_BOARD].[Delay_Reason__c] AS [Delay_Reason__c],
  [SFDC_TASKFEED_BOARD].[taskfeed1__Duration__c] AS [taskfeed1__Duration__c],
  [SFDC_TASKFEED_BOARD].[taskfeed1__End_Date__c] AS [taskfeed1__End_Date__c],
  [SFDC_TASKFEED_BOARD].[taskfeed1__End_Date_Baseline__c] AS [taskfeed1__End_Date_Baseline__c],
  [SFDC_TASKFEED_BOARD].[taskfeed1__End_Variance__c] AS [taskfeed1__End_Variance__c],
  [SFDC_TASKFEED_BOARD].[taskfeed1__Is_Complete__c] AS [taskfeed1__Is_Complete__c],
  [SFDC_TASKFEED_BOARD].[Location__c] AS [Location__c],
  [SFDC_TASKFEED_BOARD].[taskfeed1__Number_of_Completed_Tasks__c] AS [taskfeed1__Number_of_Completed_Tasks__c],
  [SFDC_TASKFEED_BOARD].[taskfeed1__Number_of_Lists__c] AS [taskfeed1__Number_of_Lists__c],
  [SFDC_TASKFEED_BOARD].[taskfeed1__Number_of_Tasks__c] AS [taskfeed1__Number_of_Tasks__c],
  [SFDC_TASKFEED_BOARD].[taskfeed1__Opportunity__c] AS [taskfeed1__Opportunity__c],
  [SFDC_TASKFEED_BOARD].[taskfeed1__Set_Baseline__c] AS [taskfeed1__Set_Baseline__c],
  [SFDC_TASKFEED_BOARD].[taskfeed1__Stage__c] AS [taskfeed1__Stage__c],
  [SFDC_TASKFEED_BOARD].[taskfeed1__Start_Date__c] AS [taskfeed1__Start_Date__c],
  [SFDC_TASKFEED_BOARD].[taskfeed1__Start_Date_Baseline__c] AS [taskfeed1__Start_Date_Baseline__c],
  [SFDC_TASKFEED_BOARD].[taskfeed1__Start_Variance__c] AS [taskfeed1__Start_Variance__c],
  [SFDC_TASKFEED_BOARD].[taskfeed1__Status_Overview__c] AS [taskfeed1__Status_Overview__c],
  [SFDC_TASKFEED_BOARD].[taskfeed1__Task_Limit_Count__c] AS [taskfeed1__Task_Limit_Count__c],
  [SFDC_TASKFEED_BOARD].[taskfeed1__Type__c] AS [taskfeed1__Type__c],
  [SFDC_TASKFEED_BOARD].[boss_location_id__c] AS [boss_location_id__c],
  [SFDC_TASKFEED_BOARD].[M5DB_Account_ID__c] AS [M5DB_Account_ID__c],
  [SFDC_TASKFEED_BOARD].[isDeleted] AS [isDeleted],
  CAST([SFDC_TASKFEED_BOARD].[Delay_Reason_Details__c] as nvarchar(1024)) AS [Delay_Reason_Details__c],
  [SFDC_TASKFEED_BOARD].[taskfeed1__Color__c] AS [taskfeed1__Color__c],
  [SFDC_TASKFEED_BOARD].[LastModifiedDate] AS [LastModifiedDate],
  [SFDC_TASKFEED_BOARD].[Notes] AS [Notes],
  [SFDC_TASKFEED_BOARD].[TF_External_Sharing] AS [TF_External_Sharing],
  [SFDC_TASKFEED_TASK].[CreatedDate] AS [CreatedDate],
  [SFDC_TASKFEED_TASK].[Id] AS [Id (SFDC_TASKFEED_TASK)],
  [SFDC_TASKFEED_TASK].[Name] AS [Name (SFDC_TASKFEED_TASK)],
  [SFDC_TASKFEED_TASK].[taskfeed1__Pc_Subtasks_Complete__c] AS [taskfeed1__Pc_Subtasks_Complete__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Account__c] AS [taskfeed1__Account__c (SFDC_TASKFEED_TASK)],
  [SFDC_TASKFEED_TASK].[taskfeed1__Active__c] AS [taskfeed1__Active__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Active_Date__c] AS [taskfeed1__Active_Date__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Blocked__c] AS [taskfeed1__Blocked__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Board__c] AS [taskfeed1__Board__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Board_Type__c] AS [taskfeed1__Board_Type__c],
  [SFDC_TASKFEED_TASK].[Case__c] AS [Case__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Category__c] AS [taskfeed1__Category__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Checklist_Items__c] AS [taskfeed1__Checklist_Items__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Checklist_Items_Template__c] AS [taskfeed1__Checklist_Items_Template__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Complete__c] AS [taskfeed1__Complete__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Complete_Date__c] AS [taskfeed1__Complete_Date__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Completed_Checklist_Items__c] AS [taskfeed1__Completed_Checklist_Items__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Contributor_Aliases__c] AS [taskfeed1__Contributor_Aliases__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Contributor_Ids__c] AS [taskfeed1__Contributor_Ids__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Contributor_Manager_Ids__c] AS [taskfeed1__Contributor_Manager_Ids__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Contributor_Role_Initials__c] AS [taskfeed1__Contributor_Role_Initials__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Contributor_Role_Placeholders_Template__c] AS [taskfeed1__Contributor_Role_Placeholders_Template__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Contributor_Roles__c] AS [taskfeed1__Contributor_Roles__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Contributors__c] AS [taskfeed1__Contributors__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Contributor_Unassigned_Roles__c] AS [taskfeed1__Contributor_Unassigned_Roles__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Created_By_Me__c] AS [taskfeed1__Created_By_Me__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Days_Remaining__c] AS [taskfeed1__Days_Remaining__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Decay__c] AS [taskfeed1__Decay__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Decay_Warning_Amber__c] AS [taskfeed1__Decay_Warning_Amber__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Decay_Warning_Red__c] AS [taskfeed1__Decay_Warning_Red__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Detail__c] AS [taskfeed1__Detail__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Due_Date__c] AS [taskfeed1__Due_Date__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Duration__c] AS [taskfeed1__Duration__c (SFDC_TASKFEED_TASK)],
  [SFDC_TASKFEED_TASK].[taskfeed1__End_Date__c] AS [taskfeed1__End_Date__c (SFDC_TASKFEED_TASK)],
  [SFDC_TASKFEED_TASK].[taskfeed1__End_Date_Baseline__c] AS [taskfeed1__End_Date_Baseline__c (SFDC_TASKFEED_TASK)],
  [SFDC_TASKFEED_TASK].[taskfeed1__End_Variance__c] AS [taskfeed1__End_Variance__c (SFDC_TASKFEED_TASK)],
  [SFDC_TASKFEED_TASK].[taskfeed1__Estimated_Hours__c] AS [taskfeed1__Estimated_Hours__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Internal__c] AS [taskfeed1__Internal__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Is_Parent__c] AS [taskfeed1__Is_Parent__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Is_Subtask__c] AS [taskfeed1__Is_Subtask__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Lead_Lag__c] AS [taskfeed1__Lead_Lag__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Lock_Due_Date__c] AS [taskfeed1__Lock_Due_Date__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Move_Due_Date_with_End_Date__c] AS [taskfeed1__Move_Due_Date_with_End_Date__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__My_Task__c] AS [taskfeed1__My_Task__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__My_Teams_Task__c] AS [taskfeed1__My_Teams_Task__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Completed_Subtasks__c] AS [taskfeed1__Completed_Subtasks__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Subtasks__c] AS [taskfeed1__Subtasks__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Open__c] AS [taskfeed1__Open__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Opportunity__c] AS [taskfeed1__Opportunity__c (SFDC_TASKFEED_TASK)],
  [SFDC_TASKFEED_TASK].[taskfeed1__Order__c] AS [taskfeed1__Order__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Board_Order__c] AS [taskfeed1__Board_Order__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Owner__c] AS [taskfeed1__Owner__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Parent_Reference__c] AS [taskfeed1__Parent_Reference__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Parent__c] AS [taskfeed1__Parent__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Predecessor_Reference__c] AS [taskfeed1__Predecessor_Reference__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Predecessor_Task__c] AS [taskfeed1__Predecessor_Task__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Predecessor_Task_Complete__c] AS [taskfeed1__Predecessor_Task_Complete__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Ready__c] AS [taskfeed1__Ready__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Ready_Date__c] AS [taskfeed1__Ready_Date__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Reference2__c] AS [taskfeed1__Reference2__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Remaining_Hours__c] AS [taskfeed1__Remaining_Hours__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Repeated_Task__c] AS [taskfeed1__Repeated_Task__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Set_Baseline__c] AS [taskfeed1__Set_Baseline__c (SFDC_TASKFEED_TASK)],
  [SFDC_TASKFEED_TASK].[taskfeed1__Stage__c] AS [taskfeed1__Stage__c (SFDC_TASKFEED_TASK)],
  [SFDC_TASKFEED_TASK].[taskfeed1__Start_Date__c] AS [taskfeed1__Start_Date__c (SFDC_TASKFEED_TASK)],
  [SFDC_TASKFEED_TASK].[taskfeed1__Start_DateTime__c] AS [taskfeed1__Start_DateTime__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Start_Date_Baseline__c] AS [taskfeed1__Start_Date_Baseline__c (SFDC_TASKFEED_TASK)],
  [SFDC_TASKFEED_TASK].[taskfeed1__Start_Variance__c] AS [taskfeed1__Start_Variance__c (SFDC_TASKFEED_TASK)],
  [SFDC_TASKFEED_TASK].[taskfeed1__Recorded_Hours__c] AS [taskfeed1__Recorded_Hours__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Total_Feed_Posts__c] AS [taskfeed1__Total_Feed_Posts__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Version__c] AS [taskfeed1__Version__c],
  [SFDC_TASKFEED_TASK].[taskfeed1__Version_Date__c] AS [taskfeed1__Version_Date__c],
  [SFDC_TASKFEED_TASK].[isDeleted] AS [isDeleted (SFDC_TASKFEED_TASK)],
  [SFDC_TASKFEED_TASK].[taskfeed1__List__c] AS [taskfeed1__List__c],
  [SFDC_TASKFEED_TASK].[ListStatus] AS [ListStatus]
FROM [dbo].[SFDC_TASKFEED_BOARD] [SFDC_TASKFEED_BOARD]
  LEFT JOIN [dbo].[SFDC_TASKFEED_TASK] [SFDC_TASKFEED_TASK] ON ([SFDC_TASKFEED_BOARD].[Id] = [SFDC_TASKFEED_TASK].[taskfeed1__Board__c])

