CREATE TABLE [Tax].[Import_Prod_Boss_201908] (
    [CustID]                   VARCHAR (50)   NULL,
    [Account Number]           VARCHAR (50)   NULL,
    [Customer Name]            NVARCHAR (250) NULL,
    [Parent Acct #]            VARCHAR (50)   NULL,
    [Parent Customer Name]     NVARCHAR (250) NULL,
    [BillCyclePeriodCode]      VARCHAR (50)   NULL,
    [Bill Cycle]               VARCHAR (50)   NULL,
    [Market]                   VARCHAR (50)   NULL,
    [AccountTypeID]            VARCHAR (50)   NULL,
    [Account Type]             VARCHAR (50)   NULL,
    [Tax Acct Type]            VARCHAR (50)   NULL,
    [Invoice Group]            VARCHAR (50)   NULL,
    [Invoice Date]             VARCHAR (50)   NULL,
    [Invoice Number]           VARCHAR (50)   NULL,
    [UsgSvcID]                 VARCHAR (50)   NULL,
    [Service Number]           VARCHAR (50)   NULL,
    [Service Name]             NVARCHAR (250) NULL,
    [Service Address]          NVARCHAR (500) NULL,
    [Service City]             VARCHAR (50)   NULL,
    [Service State]            VARCHAR (50)   NULL,
    [Service Zip]              VARCHAR (50)   NULL,
    [Service Country]          VARCHAR (50)   NULL,
    [NonUsgSvcID]              VARCHAR (50)   NULL,
    [SKU]                      VARCHAR (50)   NULL,
    [Product]                  VARCHAR (50)   NULL,
    [Quantity]                 VARCHAR (50)   NULL,
    [Charge Start Date]        VARCHAR (50)   NULL,
    [Charge End Date]          VARCHAR (50)   NULL,
    [DistanceID]               VARCHAR (50)   NULL,
    [Product Distance Type]    VARCHAR (50)   NULL,
    [TaxClassID]               VARCHAR (50)   NULL,
    [Product Tax Class]        VARCHAR (50)   NULL,
    [Usage Type Taxed]         VARCHAR (50)   NULL,
    [TaxID]                    VARCHAR (50)   NULL,
    [Tax On Intrastate]        VARCHAR (50)   NULL,
    [Tax On Interstate]        VARCHAR (50)   NULL,
    [Tax On International]     VARCHAR (50)   NULL,
    [Is Per LineTax]           VARCHAR (50)   NULL,
    [Is E911 Tax]              VARCHAR (50)   NULL,
    [Exemption Classification] NVARCHAR (250) NULL,
    [Flat Fee]                 NVARCHAR (250) NULL,
    [MIN Tier Amount]          VARCHAR (50)   NULL,
    [Tax State]                VARCHAR (50)   NULL,
    [Tax Name]                 VARCHAR (50)   NULL,
    [UsageTypeID]              VARCHAR (50)   NULL,
    [Taxable Charges]          VARCHAR (50)   NULL,
    [Tax Rate Used]            VARCHAR (50)   NULL,
    [Tax Due]                  VARCHAR (50)   NULL,
    [Total Charges]            VARCHAR (50)   NULL
);

