CREATE TABLE [PCSandbox].[BaseBillingWithPC_bkup_2020_08_01] (
    [CommissionType]                  VARCHAR (17)   NOT NULL,
    [Region]                          NVARCHAR (50)  NULL,
    [PCMonth]                         DATE           NULL,
    [AccountGUID]                     VARCHAR (50)   NULL,
    [AccountID]                       BIGINT         NULL,
    [ClientName]                      NVARCHAR (120) NULL,
    [PaymentPlan]                     NVARCHAR (255) NULL,
    [LocationGUID]                    VARCHAR (50)   NULL,
    [LocationID]                      INT            NOT NULL,
    [SubAgentGUID]                    NVARCHAR (692) NULL,
    [SubAgentId]                      NVARCHAR (128) NULL,
    [SubAgent]                        NVARCHAR (120) NULL,
    [RepName]                         NVARCHAR (120) NULL,
    [CreditingPartnerId]              INT            NULL,
    [CreditingPartner]                NVARCHAR (120) NULL,
    [ProductGUID]                     VARCHAR (50)   NULL,
    [ProductId]                       INT            NULL,
    [ProductName]                     NVARCHAR (120) NULL,
    [Description]                     NVARCHAR (512) NOT NULL,
    [CurrencyCode]                    CHAR (3)       NULL,
    [ChargeType]                      NVARCHAR (50)  NULL,
    [Charge LC]                       MONEY          NOT NULL,
    [Charge]                          MONEY          NULL,
    [CommissionableBillingsAmount LC] MONEY          NULL,
    [CommissionableBillingsAmount]    MONEY          NULL,
    [SalesComm LC]                    MONEY          NULL,
    [SalesComm]                       MONEY          NULL
);

