CREATE TABLE [dbo].[AX_Invoice_SKU] (
    [linenum]               NUMERIC (28, 12) NOT NULL,
    [salesid]               NVARCHAR (20)    NULL,
    [SKU]                   NVARCHAR (20)    NULL,
    [ItemDesc]              NVARCHAR (100)   NULL,
    [OrderType]             NVARCHAR (10)    NULL,
    [shpqty]                NUMERIC (28, 12) NULL,
    [SOLDTO]                NVARCHAR (100)   NULL,
    [ShipCity]              NVARCHAR (100)   NULL,
    [ShipPostalCode]        NVARCHAR (10)    NULL,
    [ShipState]             NVARCHAR (30)    NULL,
    [ShipCounty]            NVARCHAR (30)    NULL,
    [ShipCountry]           NVARCHAR (30)    NULL,
    [ExtendedNetPrice]      NUMERIC (38, 6)  NULL,
    [ShipDate]              DATETIME         NULL,
    [CustomerPo]            NVARCHAR (50)    NULL,
    [Customer#]             FLOAT (53)       NULL,
    [invoicedate]           DATETIME         NOT NULL,
    [invoiceid]             NVARCHAR (20)    NOT NULL,
    [DiscountPercentage]    NUMERIC (28, 12) NULL,
    [EndCust]               FLOAT (53)       NULL,
    [EndCustName]           NVARCHAR (100)   NULL,
    [Terms]                 NVARCHAR (30)    NULL,
    [UnitListPrice]         NUMERIC (38, 10) NULL,
    [IsBundle]              INT              NULL,
    [LineStatus]            INT              NULL,
    [SupportListPrice]      NUMERIC (28, 12) NULL,
    [ExtendedNetPriceLocal] NUMERIC (28, 12) NULL,
    [CurrencyCode]          NVARCHAR (3)     NULL
);

