CREATE TABLE [dbo].[B_SFDC_PARTNERS] (
    [SAPNumber]                FLOAT (53)     NULL,
    [ID 18]                    NVARCHAR (255) NULL,
    [Account Record Type]      NVARCHAR (255) NULL,
    [Type]                     NVARCHAR (255) NULL,
    [Global Partner Program]   FLOAT (53)     NULL,
    [Status]                   NVARCHAR (255) NULL,
    [Distribution Number]      FLOAT (53)     NULL,
    [Exclusive]                FLOAT (53)     NULL,
    [Strategic Account]        FLOAT (53)     NULL,
    [Purchasing Portfolio]     NVARCHAR (255) NULL,
    [Account Group]            NVARCHAR (255) NULL,
    [Customer Group]           NVARCHAR (255) NULL,
    [Heritage ID]              NVARCHAR (255) NULL,
    [Account Name]             NVARCHAR (255) NULL,
    [Partner Locator Name]     NVARCHAR (255) NULL,
    [Primary Contact]          NVARCHAR (255) NULL,
    [Distributor Relationship] NVARCHAR (255) NULL,
    [Partner Standing]         NVARCHAR (255) NULL,
    [Partner Level]            NVARCHAR (255) NULL,
    [Joint Marketing Funds]    NVARCHAR (255) NULL,
    [Account Owner]            NVARCHAR (255) NULL,
    [Website]                  NVARCHAR (255) NULL,
    [Billing Address Line 1]   NVARCHAR (255) NULL,
    [Billing City]             NVARCHAR (255) NULL,
    [Billing State/Province]   NVARCHAR (255) NULL,
    [Billing Zip/Postal Code]  NVARCHAR (255) NULL,
    [Billing Country]          NVARCHAR (255) NULL,
    [Phone]                    NVARCHAR (255) NULL,
    [Created Date]             NVARCHAR (255) NULL
);

