CREATE TABLE [dbo].[CGDiscounts] (
    [DISCOUNT]   NVARCHAR (13)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [PRODUCT]    NVARCHAR (13)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [RECORDMODE] NVARCHAR (1)    COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [TIER_TYPE]  NVARCHAR (10)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [TIERS]      NVARCHAR (30)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [AMT_TYPE]   NVARCHAR (10)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [DIS_TYPE]   NVARCHAR (10)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [AMOUNT_C]   NVARCHAR (30)   COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [PERC]       NUMERIC (17, 5) NOT NULL
);

