CREATE TABLE [dbo].[DYNAMICS_INTEGRATION_ATTRIB] (
    [Created] DATETIME       CONSTRAINT [DF_DYNAMICS_INTEGRATION_ATTRIB_Created] DEFAULT (getdate()) NULL,
    [Id]      INT            IDENTITY (1, 1) NOT NULL,
    [AuthKey] VARCHAR (5000) NULL,
    CONSTRAINT [PK_DYNAMICS_INTEGRATION_ATTRIB] PRIMARY KEY CLUSTERED ([Id] ASC)
);

