CREATE TABLE [dbo].[HOA_MASTERcommissions_20140701_20150213] (
    [DataSource]              VARCHAR (30)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [QmsOrderNumber]          NVARCHAR (25)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SalesOrder]              NVARCHAR (20)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [OrigSalesOrder]          NVARCHAR (20)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [OrderDate]               DATETIME2 (7)    NULL,
    [InvoiceDate]             DATETIME2 (7)    NULL,
    [Invoice]                 NVARCHAR (20)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [RequestedShipDate]       DATETIME2 (7)    NULL,
    [CustomerPo]              NVARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PartnerG]                CHAR (255)       COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Partner]                 NVARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ImpactNumber]            NVARCHAR (40)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CustBillToName]          CHAR (255)       COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CUSTGROUP]               NVARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CustGroupDesc]           CHAR (255)       COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CustSoldTo]              NVARCHAR (40)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CustSoldToName]          CHAR (255)       COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CustShipTo]              NVARCHAR (40)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CustShipToName]          CHAR (255)       COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [EndCust]                 NVARCHAR (40)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [EndCustName]             CHAR (255)       COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [REVtype]                 NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [TYPE]                    NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [GMFamily]                NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [EndCustBuild]            CHAR (10)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SoLineNum]               FLOAT (53)       NULL,
    [InvoiceLineNum]          FLOAT (53)       NULL,
    [Sku]                     CHAR (20)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ListPrice]               FLOAT (53)       NULL,
    [PromoPrice]              FLOAT (53)       NULL,
    [StdCost]                 FLOAT (53)       NULL,
    [StockCode]               CHAR (30)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [StockCodeDesc]           NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Qty]                     NUMERIC (38, 12) NULL,
    [NetSalesUSD]             NUMERIC (38, 12) NULL,
    [NetSalesLocalCurrency]   NUMERIC (38, 12) NULL,
    [StdCogs]                 FLOAT (53)       NULL,
    [StdMgn]                  FLOAT (53)       NULL,
    [StdCogsComp]             FLOAT (53)       NULL,
    [StdMgnComp]              FLOAT (53)       NULL,
    [StdMgnCompUplifted]      FLOAT (53)       NULL,
    [CURRENCYCODE]            NVARCHAR (3)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ExchangeRate]            FLOAT (53)       NULL,
    [ProfitCenter]            NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [OrderType]               NVARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ProductClass]            CHAR (30)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [OrigSalesArea]           CHAR (30)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SalesArea]               NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [RVP]                     NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [RD]                      NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [RegionArea]              NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Channel]                 CHAR (1)         COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [FiscalQuarterCommission] CHAR (7)         COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CalendarMonthCommission] CHAR (8)         COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Fyear]                   NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Fquarter]                NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Cyear]                   FLOAT (53)       NULL,
    [Cquarter]                NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CalendarMonth]           NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Country]                 NVARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ShipCountry]             NVARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ShipState]               NVARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ShipCounty]              NVARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ShipCity]                NVARCHAR (60)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ShipPostalCode]          NVARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [MAP]                     CHAR (10)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [GOV]                     CHAR (10)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [GOVclass]                CHAR (10)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Cpartner]                CHAR (30)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Cpartner02]              CHAR (30)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Cpartner03]              CHAR (30)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Cpartner04]              CHAR (30)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Cpartner05]              CHAR (30)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Cpartner06]              CHAR (30)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Cpartner07]              CHAR (30)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Cpartner08]              CHAR (30)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DBfamily]                NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CountryTerritory]        NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [RegionSub]               NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SubRegion]               NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [MobilityFamily]          NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ECCfamily]               NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [BillingsComp]            FLOAT (53)       NULL,
    [CogsComp]                FLOAT (53)       NULL,
    [MgnComp]                 FLOAT (53)       NULL,
    [MgnCompUplifted]         FLOAT (53)       NULL,
    [CompRate]                FLOAT (53)       NULL,
    [WeightedRate]            FLOAT (53)       NULL,
    [ECarea]                  NVARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [VARacct]                 NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [VARname]                 NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [MOB]                     NVARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ProgramType]             CHAR (100)       COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Mobility]                CHAR (100)       COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ECC]                     CHAR (100)       COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ChannelRole]             CHAR (10)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ASM]                     CHAR (100)       COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);

