CREATE TABLE [dbo].[INTEGRATION_CONTROL] (
    [Created]     DATETIME     CONSTRAINT [DF_INTEGRATION_CONTROL_Created] DEFAULT (getdate()) NULL,
    [ProcessName] VARCHAR (50) NOT NULL,
    [Status]      VARCHAR (50) CONSTRAINT [DF_INTEGRATION_CONTROL_Status] DEFAULT ('Running') NULL,
    CONSTRAINT [PK_INTEGRATION_CONTROL] PRIMARY KEY CLUSTERED ([ProcessName] ASC)
);

