CREATE TABLE [dbo].[Leadspace-Customers] (
    [Leadspace Row Labels]          NVARCHAR (255) NULL,
    [Worldwide]                     INT            NULL,
    [United States]                 INT            NULL,
    [Canada]                        INT            NULL,
    [Australia]                     INT            NULL,
    [Argentina]                     INT            NULL,
    [Belgium]                       INT            NULL,
    [Brazil]                        INT            NULL,
    [China]                         INT            NULL,
    [France]                        INT            NULL,
    [Germany]                       INT            NULL,
    [India]                         INT            NULL,
    [Japan]                         INT            NULL,
    [Afghanistan]                   INT            NULL,
    [Albania]                       INT            NULL,
    [Algeria]                       INT            NULL,
    [Angola]                        INT            NULL,
    [Anguilla]                      INT            NULL,
    [Armenia]                       INT            NULL,
    [Aruba]                         INT            NULL,
    [Austria]                       INT            NULL,
    [Azerbaijan]                    INT            NULL,
    [Bahamas]                       INT            NULL,
    [Bahrain]                       INT            NULL,
    [Bangladesh]                    INT            NULL,
    [Barbados]                      INT            NULL,
    [Belarus]                       INT            NULL,
    [Belize]                        INT            NULL,
    [Benin]                         INT            NULL,
    [Bermuda]                       INT            NULL,
    [Bolivia]                       FLOAT (53)     NULL,
    [Botswana]                      FLOAT (53)     NULL,
    [Brunei]                        FLOAT (53)     NULL,
    [Bulgaria]                      FLOAT (53)     NULL,
    [Burkina Faso]                  NVARCHAR (255) NULL,
    [Cambodia]                      FLOAT (53)     NULL,
    [Cameroon]                      FLOAT (53)     NULL,
    [Cape Verde]                    FLOAT (53)     NULL,
    [Cayman Islands]                FLOAT (53)     NULL,
    [Chad]                          FLOAT (53)     NULL,
    [Chile]                         FLOAT (53)     NULL,
    [Colombia]                      FLOAT (53)     NULL,
    [Costa Rica]                    FLOAT (53)     NULL,
    [Croatia]                       FLOAT (53)     NULL,
    [Cyprus]                        FLOAT (53)     NULL,
    [Czech Republic]                FLOAT (53)     NULL,
    [Denmark]                       FLOAT (53)     NULL,
    [Djibouti]                      FLOAT (53)     NULL,
    [Dominica]                      FLOAT (53)     NULL,
    [Ecuador]                       FLOAT (53)     NULL,
    [Egypt]                         FLOAT (53)     NULL,
    [El Salvador]                   FLOAT (53)     NULL,
    [Estonia]                       FLOAT (53)     NULL,
    [Ethiopia]                      FLOAT (53)     NULL,
    [Faroe Islands]                 FLOAT (53)     NULL,
    [Fiji]                          NVARCHAR (255) NULL,
    [Finland]                       FLOAT (53)     NULL,
    [French Guiana]                 FLOAT (53)     NULL,
    [French Polynesia]              FLOAT (53)     NULL,
    [Gabon]                         FLOAT (53)     NULL,
    [Ghana]                         FLOAT (53)     NULL,
    [Greece]                        FLOAT (53)     NULL,
    [Greenland]                     FLOAT (53)     NULL,
    [Grenada]                       FLOAT (53)     NULL,
    [Guadeloupe]                    FLOAT (53)     NULL,
    [Guatemala]                     FLOAT (53)     NULL,
    [Guinea]                        FLOAT (53)     NULL,
    [Guyana]                        FLOAT (53)     NULL,
    [Haiti]                         FLOAT (53)     NULL,
    [Honduras]                      FLOAT (53)     NULL,
    [Hong Kong]                     FLOAT (53)     NULL,
    [Hungary]                       FLOAT (53)     NULL,
    [Iceland]                       FLOAT (53)     NULL,
    [Indonesia]                     FLOAT (53)     NULL,
    [Iran]                          FLOAT (53)     NULL,
    [Iraq]                          FLOAT (53)     NULL,
    [Ireland]                       FLOAT (53)     NULL,
    [Israel]                        FLOAT (53)     NULL,
    [Italy]                         FLOAT (53)     NULL,
    [Jamaica]                       FLOAT (53)     NULL,
    [Jordan]                        FLOAT (53)     NULL,
    [Kazakhstan]                    FLOAT (53)     NULL,
    [Kenya]                         FLOAT (53)     NULL,
    [Kuwait]                        FLOAT (53)     NULL,
    [Kyrgyzstan]                    FLOAT (53)     NULL,
    [Latvia]                        FLOAT (53)     NULL,
    [Lebanon]                       FLOAT (53)     NULL,
    [Libya]                         FLOAT (53)     NULL,
    [Lithuania]                     FLOAT (53)     NULL,
    [Luxembourg]                    FLOAT (53)     NULL,
    [Macao]                         FLOAT (53)     NULL,
    [Macedonia]                     FLOAT (53)     NULL,
    [Madagascar]                    FLOAT (53)     NULL,
    [Malawi]                        FLOAT (53)     NULL,
    [Malaysia]                      FLOAT (53)     NULL,
    [Maldives]                      FLOAT (53)     NULL,
    [Mali]                          FLOAT (53)     NULL,
    [Malta]                         FLOAT (53)     NULL,
    [Marshall Islands]              FLOAT (53)     NULL,
    [Martinique]                    FLOAT (53)     NULL,
    [Mauritania]                    FLOAT (53)     NULL,
    [Mauritius]                     FLOAT (53)     NULL,
    [Mexico]                        FLOAT (53)     NULL,
    [Moldova]                       FLOAT (53)     NULL,
    [Monaco]                        FLOAT (53)     NULL,
    [Montserrat]                    FLOAT (53)     NULL,
    [Morocco]                       FLOAT (53)     NULL,
    [Mozambique]                    FLOAT (53)     NULL,
    [Myanmar]                       FLOAT (53)     NULL,
    [Namibia]                       FLOAT (53)     NULL,
    [Nepal]                         FLOAT (53)     NULL,
    [Netherlands]                   FLOAT (53)     NULL,
    [Netherlands Antilles]          FLOAT (53)     NULL,
    [New Zealand]                   FLOAT (53)     NULL,
    [Nicaragua]                     FLOAT (53)     NULL,
    [Nigeria]                       FLOAT (53)     NULL,
    [Norway]                        FLOAT (53)     NULL,
    [Oman]                          FLOAT (53)     NULL,
    [Pakistan]                      FLOAT (53)     NULL,
    [Panama]                        FLOAT (53)     NULL,
    [Paraguay]                      FLOAT (53)     NULL,
    [Peru]                          FLOAT (53)     NULL,
    [Philippines]                   FLOAT (53)     NULL,
    [Poland]                        FLOAT (53)     NULL,
    [Portugal]                      FLOAT (53)     NULL,
    [Qatar]                         FLOAT (53)     NULL,
    [Reunion]                       FLOAT (53)     NULL,
    [Romania]                       FLOAT (53)     NULL,
    [San Marino]                    FLOAT (53)     NULL,
    [Saudi Arabia]                  FLOAT (53)     NULL,
    [Scotland]                      FLOAT (53)     NULL,
    [Senegal]                       FLOAT (53)     NULL,
    [Singapore]                     FLOAT (53)     NULL,
    [Slovakia]                      FLOAT (53)     NULL,
    [Slovenia]                      FLOAT (53)     NULL,
    [Solomon Islands]               NVARCHAR (255) NULL,
    [South Africa]                  FLOAT (53)     NULL,
    [Spain]                         FLOAT (53)     NULL,
    [Sri Lanka]                     FLOAT (53)     NULL,
    [Suriname]                      FLOAT (53)     NULL,
    [Sweden]                        FLOAT (53)     NULL,
    [Switzerland]                   FLOAT (53)     NULL,
    [Syria]                         FLOAT (53)     NULL,
    [Taiwan]                        FLOAT (53)     NULL,
    [Tanzania]                      FLOAT (53)     NULL,
    [Thailand]                      FLOAT (53)     NULL,
    [Togo]                          FLOAT (53)     NULL,
    [Tunisia]                       FLOAT (53)     NULL,
    [Turkey]                        FLOAT (53)     NULL,
    [Uganda]                        FLOAT (53)     NULL,
    [Ukraine]                       FLOAT (53)     NULL,
    [Uruguay]                       FLOAT (53)     NULL,
    [Uzbekistan]                    FLOAT (53)     NULL,
    [Venezuela]                     FLOAT (53)     NULL,
    [Vietnam]                       FLOAT (53)     NULL,
    [Wales]                         FLOAT (53)     NULL,
    [Yemen]                         FLOAT (53)     NULL,
    [Zambia]                        FLOAT (53)     NULL,
    [ShoreTel SFDC Alphanumeric ID] NVARCHAR (255) NULL,
    [ShoreTel numeric ID]           INT            NULL,
    [Partner of Record ONSITE]      NVARCHAR (255) NULL,
    [POR ShoreTel ID]               INT            NULL
);

