CREATE TABLE [dbo].[mVwHANA_CGAccounts] (
    [Account Manager Key]                VARCHAR (8)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Sales Organization Key]             NVARCHAR (4)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Sales Organization Name]            NVARCHAR (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Price Group Key]                    NVARCHAR (2)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Payment Terms Key]                  NVARCHAR (4)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Customer Group Key]                 NVARCHAR (2)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Customer Group Name]                NVARCHAR (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Incoterms 1]                        NVARCHAR (3)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Incoterms 2]                        NVARCHAR (28) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Payment Terms Name]                 NVARCHAR (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Price Group Name]                   NVARCHAR (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [High Level Vertical]                NVARCHAR (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Vertical]                           NVARCHAR (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SIC Code 1 Key]                     NVARCHAR (4)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SIC Code 2 Name]                    NVARCHAR (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SIC Code 2 Key]                     NVARCHAR (4)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SIC Code 3 Name]                    NVARCHAR (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SIC Code 3 Key]                     NVARCHAR (4)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SIC Code 1 Name]                    NVARCHAR (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SIC Code 4 Name]                    NVARCHAR (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Customer Name]                      NVARCHAR (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Customer Name 2]                    NVARCHAR (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Customer Name 3]                    NVARCHAR (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Street Address]                     NVARCHAR (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [City]                               NVARCHAR (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Country Key]                        NVARCHAR (3)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Created On]                         NVARCHAR (8)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Telephone Number]                   NVARCHAR (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [State ]                             NVARCHAR (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Country Name]                       NVARCHAR (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DUNS Number]                        NVARCHAR (9)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Customer Account Group Key]         NVARCHAR (4)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Customer Account Group Name]        NVARCHAR (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Channel Type Key]                   NVARCHAR (3)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Channel Type Name]                  NVARCHAR (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Company Size Key]                   NVARCHAR (2)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Managed System]                     NVARCHAR (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Managed System ID]                  NVARCHAR (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Blue SFDC ID]                       NVARCHAR (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Orange SFDC ID]                     NVARCHAR (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SIC Code 4 Key]                     NVARCHAR (4)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Mitel User Group]                   NVARCHAR (1)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Partner Level Key]                  NVARCHAR (2)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Partner Level Name]                 NVARCHAR (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Sub Territory Key]                  NVARCHAR (4)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Sub Territory Name]                 NVARCHAR (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Managed By Key]                     NVARCHAR (2)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Managed By Name]                    NVARCHAR (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Customer Name 4]                    NVARCHAR (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Company Size Name]                  NVARCHAR (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Postal Code ]                       NVARCHAR (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Postal Code CD]                     NVARCHAR (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Created By]                         NVARCHAR (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CostGuard UK ID]                    NVARCHAR (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CostGuard US ID]                    NVARCHAR (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CostGuard DE ID]                    NVARCHAR (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [BOSS EU ID]                         NVARCHAR (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [BOSS AU ID]                         NVARCHAR (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [BOSS US ID]                         NVARCHAR (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Credit Block]                       NVARCHAR (3)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Marked for Deletion]                VARCHAR (3)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Reseller Partner Key]               VARCHAR (10)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Index]                              VARCHAR (15)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Reseller Partner Channel Type Key]  NVARCHAR (3)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Reseller Partner Channel Type Name] NVARCHAR (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Distributor of Record Key]          VARCHAR (10)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Billing Block Key]                  NVARCHAR (2)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Order Block Key]                    NVARCHAR (2)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Price List Key]                     NVARCHAR (2)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Customer Number]                    NVARCHAR (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [KNVV Count]                         INT           NULL,
    [KNA1 Count]                         INT           NULL,
    [Region]                             NVARCHAR (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Sales Area]                         NVARCHAR (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Sub Theatre]                        NVARCHAR (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Sub Region]                         NVARCHAR (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Territory]                          NVARCHAR (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Theatre]                            NVARCHAR (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Channel Hierarchy Level 1]          NVARCHAR (8)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Channel Hierarchy Level 2]          NVARCHAR (8)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Customer Hierarchy Level 1 Key]     NVARCHAR (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Customer Hierarchy Level 2 Key]     NVARCHAR (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Customer Hierarchy Level 3 Key]     NVARCHAR (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Customer Hierarchy Level 1 Name]    VARCHAR (60)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Customer Hierarchy Level 2 Name]    VARCHAR (60)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Customer Hierarchy Level 3 Name]    VARCHAR (60)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Account Manager Name]               NVARCHAR (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Billing Block Name]                 NVARCHAR (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Price List Name]                    NVARCHAR (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Order Block Name]                   NVARCHAR (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Reseller Partner Name]              NVARCHAR (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Distributor of Record Name]         NVARCHAR (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);

