CREATE TABLE [dbo].[POS_ALL_ARCHIVE] (
    [CustomerPo]              NVARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [QmsOrderNumber]          NVARCHAR (25)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SalesOrder]              NVARCHAR (20)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [OrigSalesOrder]          NVARCHAR (20)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [OrderDate]               DATETIME         NULL,
    [InvoiceDate]             DATETIME         NULL,
    [Invoice]                 NVARCHAR (20)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [RequestedShipDate]       DATETIME         NULL,
    [PartnerG]                CHAR (255)       COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Partner]                 NVARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ImpactNumber]            NVARCHAR (40)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [EndCust]                 NVARCHAR (40)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [EndCustName]             CHAR (255)       COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [REVtype]                 NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [TYPE]                    NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [GMFamily]                NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [EndCustBuild]            CHAR (10)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Sku]                     CHAR (20)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [StockCode]               CHAR (30)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [StockCodeDesc]           NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Qty]                     NUMERIC (38, 12) NULL,
    [OrderType]               NVARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [OrigSalesArea]           CHAR (30)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SalesArea]               NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [RVP]                     NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [RD]                      NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [RegionArea]              NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [FiscalQuarterCommission] CHAR (7)         COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CalendarMonthCommission] CHAR (8)         COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Country]                 NVARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ShipCountry]             NVARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ShipState]               NVARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ShipCounty]              NVARCHAR (30)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ShipCity]                NVARCHAR (60)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ShipPostalCode]          NVARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [MAP]                     CHAR (10)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [GOV]                     CHAR (10)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [GOVclass]                CHAR (10)        COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [DBfamily]                NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CountryTerritory]        NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [RegionSub]               NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SubRegion]               NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [BillingsComp]            FLOAT (53)       NULL,
    [MgnCompUplifted]         FLOAT (53)       NULL,
    [ECarea]                  NVARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [MOB]                     NVARCHAR (10)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [MgnComp]                 FLOAT (53)       NULL,
    [Cquarter]                NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Fquarter]                NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NetSalesUSD]             NUMERIC (38, 12) NULL,
    [CalendarMonth]           NVARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);

