CREATE TABLE [dbo].[SALESTABLE] (
    [CURRENCYCODE]        NVARCHAR (3)  NOT NULL,
    [CUSTACCOUNT]         NVARCHAR (40) NOT NULL,
    [PURCHORDERFORMNUM]   NVARCHAR (50) NOT NULL,
    [SALESID]             NVARCHAR (20) NOT NULL,
    [salestype]           INT           NOT NULL,
    [SEMENDCUST]          NVARCHAR (40) NOT NULL,
    [SEMPOSTINGORDERTYPE] NVARCHAR (10) NOT NULL
);

