CREATE TABLE [dbo].[SAP_BILLINGS] (
    [Created]               DATETIME       CONSTRAINT [DF_SAP_BILLINGS_Created] DEFAULT (getdate()) NULL,
    [RecId]                 VARCHAR (101)  NOT NULL,
    [OrderDate]             DATETIME       NULL,
    [RequestedShipDate]     DATETIME       NULL,
    [CustomerPo]            VARCHAR (50)   NULL,
    [QmsQuoteNumber]        VARCHAR (50)   NULL,
    [SalesOrder]            VARCHAR (50)   NULL,
    [OrigSalesOrder]        VARCHAR (50)   NULL,
    [OrderType]             VARCHAR (50)   NULL,
    [Invoice]               VARCHAR (50)   NULL,
    [InvoiceDate]           DATETIME       NULL,
    [BillTo]                VARCHAR (50)   NULL,
    [CUSTGROUP]             VARCHAR (50)   NULL,
    [BillToName]            VARCHAR (50)   NULL,
    [EndCust]               VARCHAR (50)   NULL,
    [EndCustName]           VARCHAR (50)   NULL,
    [InvoiceLineNum]        VARCHAR (50)   NULL,
    [ItemGroupName]         VARCHAR (50)   NULL,
    [AxRevType]             VARCHAR (50)   NULL,
    [SKU]                   VARCHAR (8000) NULL,
    [ItemDesc]              VARCHAR (50)   NULL,
    [CURRENCYCODE]          VARCHAR (50)   NULL,
    [PRICEUNIT]             VARCHAR (50)   NULL,
    [QTY]                   FLOAT (53)     NULL,
    [NetSalesUSD]           FLOAT (53)     NULL,
    [ProfitCenter]          VARCHAR (50)   NULL,
    [Country]               VARCHAR (50)   NULL,
    [ShipCity]              VARCHAR (50)   NULL,
    [ShipPostalCode]        VARCHAR (50)   NULL,
    [ShipState]             VARCHAR (50)   NULL,
    [ShipCounty]            VARCHAR (50)   NULL,
    [ShipCountry]           VARCHAR (50)   NULL,
    [IVARName]              VARCHAR (50)   NULL,
    [IVARId]                VARCHAR (50)   NULL,
    [SemSbeParent]          VARCHAR (50)   NULL,
    [ShippingDateRequested] VARCHAR (50)   NULL,
    [ShippingDateConfirmed] VARCHAR (50)   NULL,
    [InvoiceDateUTC]        VARCHAR (50)   NULL,
    [InvoiceDateTimeUTC]    VARCHAR (50)   NULL,
    [EndCustCreateDate]     VARCHAR (50)   NULL,
    [SemQmsList]            VARCHAR (50)   NULL,
    [ReturnReasonCodeId]    VARCHAR (50)   NULL,
    [ReturnFlag]            VARCHAR (50)   NULL,
    [ReturnQty]             VARCHAR (50)   NULL,
    CONSTRAINT [PK_SAP_BILLINGS] PRIMARY KEY CLUSTERED ([RecId] ASC)
);

