CREATE TABLE [dbo].[SAP_ORDERS_RAW] (
    [VBAK-VBELN]    VARCHAR (50)  NULL,
    [VBAK-ERDAT]    VARCHAR (50)  NULL,
    [VBPA-KUNNR_BP] VARCHAR (50)  NULL,
    [VBPA-KUNNR_Z5] VARCHAR (50)  NULL,
    [VBAK-BSARK]    VARCHAR (50)  NULL,
    [VBAK-VDATU]    VARCHAR (50)  NULL,
    [VBAK-WAERK]    VARCHAR (50)  NULL,
    [VBKD-BSTKD]    VARCHAR (150) NULL
);

