CREATE TABLE [dbo].[SFDC_PARTNERS] (
    [Created]                        DATETIME2 (7)   NULL,
    [SfdcId]                         NVARCHAR (255)  COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [SE_ID]                          VARCHAR (15)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ImpactNumber]                   NVARCHAR (255)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [AccountName]                    NVARCHAR (255)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SubType]                        NVARCHAR (255)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SuperRegional]                  VARCHAR (5)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [StartDate]                      DATETIME2 (7)   NULL,
    [Base]                           NUMERIC (18)    NULL,
    [Volume]                         NUMERIC (18)    NULL,
    [Skills]                         NUMERIC (18)    NULL,
    [TotalDisc]                      NUMERIC (18)    NULL,
    [Exclusivity]                    NUMERIC (18)    NULL,
    [CoeAccount]                     VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [POSRebate]                      NUMERIC (18)    NULL,
    [QMSInternalDiscount]            NUMERIC (18)    NULL,
    [QMSNewPartnerPromotionDiscount] NUMERIC (18)    NULL,
    [QMSpartnerCompanyLogin]         VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [QMSResellerOnHold]              VARCHAR (5)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SupportPrice]                   NUMERIC (18, 2) NULL,
    [BusinessPlanDate]               DATETIME2 (7)   NULL,
    [ChampLevel]                     VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [AuthToSell]                     VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [OwnerId]                        VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ASMId]                          VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ASRId]                          VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [AXArea]                         VARCHAR (15)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [LaunchedDate]                   DATETIME2 (7)   NULL,
    [MobPreSales]                    VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [MobPostSales]                   VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [MobReferences]                  VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CustomDemoKits]                 INT             NOT NULL,
    [Country]                        VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Theatre]                        VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [AxTerritory]                    VARCHAR (15)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [OwnerEmail]                     VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CloudChampLevel]                VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Discount_P1__c]                 NUMERIC (18, 2) NULL,
    [Discount_P1N__c]                NUMERIC (18, 2) NULL,
    [Discount_P2N__c]                NUMERIC (18, 2) NULL,
    [Discount_P3__c]                 NUMERIC (18, 2) NULL,
    [Discount_P3N__c]                NUMERIC (18, 2) NULL,
    [Discount_C1N__c]                NUMERIC (18, 2) NULL,
    [Discount_G1N__c]                NUMERIC (18, 2) NULL,
    [Discount_S1N__c]                NUMERIC (18, 2) NULL,
    [Discount_S2N__c]                NUMERIC (18, 2) NULL,
    [Discount_S3N__c]                NUMERIC (18, 2) NULL,
    [Discount_S4N__c]                NUMERIC (18, 2) NULL,
    [AXCreatedDate]                  DATETIME2 (7)   NULL,
    [SSCA]                           VARCHAR (15)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SSCE]                           VARCHAR (15)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CloudUCPractice]                VARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PartnerOfRecord]                VARCHAR (50)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CloudPartnerType]               VARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PBMRegion]                      VARCHAR (255)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [PartnerCloudDemoProfiles]       VARCHAR (15)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CloudBusinessModel]             VARCHAR (100)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [rn]                             BIGINT          NULL
);

