CREATE TABLE [dbo].[SFDC_CUSTOMERS] (
    [Created]                                  DATETIME        NOT NULL,
    [SfdcCreateDateUTC]                        DATETIME        NULL,
    [SfdcLastUpdateDateUTC]                    DATETIME        NULL,
    [SfdcId]                                   VARCHAR (50)    COLLATE Latin1_General_BIN NOT NULL,
    [End_User_Csn]                             VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [ImpactNumber]                             VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [NAME]                                     VARCHAR (100)   COLLATE Latin1_General_BIN NOT NULL,
    [Partner_Csn]                              VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [PartnerSfdcId]                            VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [PartnerId]                                VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [SupportType]                              VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [Region]                                   VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [VersionFromSR]                            VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [DbNum]                                    VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [SicCode]                                  VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [DistyId]                                  VARCHAR (15)    COLLATE Latin1_General_BIN NULL,
    [DistySfdcId]                              VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [SupportPrice]                             NUMERIC (18, 2) NULL,
    [Country]                                  VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [Type]                                     VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [Address]                                  VARCHAR (300)   COLLATE Latin1_General_BIN NULL,
    [City]                                     VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [State]                                    VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [Zipcode]                                  VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [Phone]                                    VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [Status]                                   VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [AxCode]                                   VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [DiscountType]                             VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [LastSyncDate]                             DATETIME        NULL,
    [Opportunity_Registration_Expiration_Date] DATETIME        NULL,
    [Cust_Disc]                                NUMERIC (18, 2) NULL,
    [RecPartnerId]                             VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [RecPartnerName]                           VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [RecPartnerDisc]                           NUMERIC (18, 2) NULL,
    [OrigPartnerId]                            VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [OrigPartnerName]                          VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [OrigPartnerDisc]                          NUMERIC (18, 2) NULL,
    [GAPAccount]                               VARCHAR (10)    COLLATE Latin1_General_BIN NULL,
    [SECreatedDate]                            DATETIME        NULL,
    [STTerritory]                              VARCHAR (80)    COLLATE Latin1_General_BIN NULL,
    [OwnerName]                                VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [OwnerEmail]                               VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [ParentSTID]                               VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [PriContactLastName]                       VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [PriContactFirstName]                      VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [PriContactEmail]                          VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [PriContactPhone]                          VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [Theater]                                  VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [DistributorDiscount]                      NUMERIC (18, 2) NULL,
    [SupportSKU]                               VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [SupportEndDate]                           DATETIME        NULL,
    [GOVAccount]                               VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [GOVClass]                                 VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [CustomerType]                             VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [M5DBAccountID]                            VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [StateCode]                                VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [CountryCode]                              VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [CSM]                                      VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [ReferredbyPartnerID]                      VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [Instance]                                 VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [AccountTeam]                              VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [IvarRecDisc]                              NUMERIC (18, 2) NULL,
    [Industry]                                 VARCHAR (MAX)   COLLATE Latin1_General_BIN NULL,
    [FirstInvoice]                             DATETIME        NULL,
    [DbNumOfEmployees]                         VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [CloudProfiles]                            NUMERIC (18)    NULL,
    [ConnectCloudProfilesRollup]               NUMERIC (18)    NULL,
    [LegacyCloudProfilesRollup]                NUMERIC (18)    NULL,
    [OnsitePoints]                             NUMERIC (18)    NULL,
    [PartnerCSM]                               VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [PartnerOfRecordCloud]                     VARCHAR (25)    COLLATE Latin1_General_BIN NULL,
    [AtRiskNow]                                NUMERIC (18)    NULL,
    [OnsitePointsRollup]                       NUMERIC (18)    NULL,
    [SAPNumber]                                VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [Platform]                                 VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [CLOUDPartnerType]                         VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [ActiveMRR_Boss]                           FLOAT (53)      NULL,
    [OtherERPNumber]                           VARCHAR (25)    COLLATE Latin1_General_BIN NULL,
    [isMCSS]                                   INT             NULL,
    [CommitmentDate]                           DATETIME        NULL,
    [MCSS1stReminderDate]                      DATETIME        NULL,
    [MCSS2ndReminderDate]                      DATETIME        NULL,
    [MCSSSurveyExpirationDate]                 DATETIME        NULL,
    [MCSSSurveySent]                           DATETIME        NULL,
    [MCSSSurveyStatus]                         VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [CSD_MA]                                   VARCHAR (150)   COLLATE Latin1_General_BIN NULL,
    [NodeEmployeeCount]                        NUMERIC (18)    NULL,
    [CCProfiles_boss]                          FLOAT (53)      NULL,
    [UCaaSAccountOwner]                        VARCHAR (150)   COLLATE Latin1_General_BIN NULL,
    [RecordType]                               VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [BOSS_Support_Partner__c]                  VARCHAR (25)    COLLATE Latin1_General_BIN NULL,
    [MiCloud_Connect_Business_Model__c]        VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [PartnerDisplayName__c]                    VARCHAR (125)   COLLATE Latin1_General_BIN NULL,
    [PartnerSupportEmailAddress__c]            VARCHAR (150)   COLLATE Latin1_General_BIN NULL,
    [PartnerSupportInformation__c]             VARCHAR (255)   COLLATE Latin1_General_BIN NULL,
    [PartnerSupportPhoneNumber__c]             VARCHAR (40)    COLLATE Latin1_General_BIN NULL,
    [PartnerSupportWebPage__c]                 VARCHAR (255)   COLLATE Latin1_General_BIN NULL,
    [Support_Partner_Enabled__c]               VARCHAR (5)     COLLATE Latin1_General_BIN NULL
);

