CREATE TABLE [dbo].[tmpHanaBill] (
    [Sold-to party]                      NVARCHAR (10)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Sales Organization]                 NVARCHAR (4)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Sold to Country (M)]                NVARCHAR (3)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Sold to State/Province (M)]         NVARCHAR (3)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Sold to Region (M)]                 NVARCHAR (40)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Sold to Sales Area (M)]             NVARCHAR (40)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Sold to Hierarchy Level 1 (M)]      NVARCHAR (10)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Sold to Hierarchy Level 2 (M)]      NVARCHAR (10)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Sold to Hierarchy Level 3 (M)]      NVARCHAR (10)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Ship to party]                      NVARCHAR (10)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Change Indicator for Ship to]       NVARCHAR (2)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Ship to City]                       NVARCHAR (35)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Ship to Country]                    NVARCHAR (3)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Ship to Postal Code]                NVARCHAR (10)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Ship to State/Province]             NVARCHAR (3)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Ship to Street]                     NVARCHAR (35)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Ship to Region (M)]                 NVARCHAR (40)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Ship to Sales Area (M)]             NVARCHAR (40)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Ship to Hierarchy Level 1 (M)]      NVARCHAR (10)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Ship to Hierarchy Level 2 (M)]      NVARCHAR (10)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Ship to Hierarchy Level 3 (M)]      NVARCHAR (10)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Created On]                         NVARCHAR (8)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Date - Day]                         NVARCHAR (8)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Date - Year / Month]                NVARCHAR (6)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Date - Year / Quarter]              NVARCHAR (5)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Date - Year]                        NVARCHAR (4)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Date - Month]                       NVARCHAR (2)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Date - Quarter]                     NVARCHAR (1)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Date - Day of Week]                 NVARCHAR (1)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Date - Week]                        NVARCHAR (2)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Billing End Date]                   NVARCHAR (8)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [End Customer Account Manager (T)]   NVARCHAR (8)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [End Customer Number]                NVARCHAR (10)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [End Customer City]                  NVARCHAR (35)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [End Customer Country]               NVARCHAR (3)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [End Customer Location Name]         NVARCHAR (35)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [End Customer Postal Code]           NVARCHAR (10)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [End Customer State/Province]        NVARCHAR (3)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [End Customer Street]                NVARCHAR (35)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Change Indicator for End User]      NVARCHAR (2)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [End Customer Source]                NVARCHAR (2)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [End Customer Sub-Territory (T)]     NVARCHAR (4)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [End Customer Name]                  NVARCHAR (35)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [End Customer Channel Type]          NVARCHAR (3)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [End Customer Hierarchy Level 1 (M)] NVARCHAR (10)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [End Customer Hierarchy Level 2 (M)] NVARCHAR (10)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [End Customer Hierarchy Level 3 (M)] NVARCHAR (10)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Bill to party]                      NVARCHAR (10)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Bill to Country (M)]                NVARCHAR (3)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Material]                           NVARCHAR (18)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Material Group]                     NVARCHAR (9)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Material Group 1]                   NVARCHAR (3)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Material Group 2]                   NVARCHAR (3)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Material Group 4]                   NVARCHAR (3)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Material Group 5]                   NVARCHAR (3)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Material Category (M)]              NVARCHAR (2)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Material Product Hierarchy (M)]     NVARCHAR (40)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Material Availability Date]         NVARCHAR (8)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Higher-Level Item]                  NVARCHAR (6)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Billing Item]                       NVARCHAR (6)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Billing Document]                   NVARCHAR (10)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Billing Type]                       NVARCHAR (4)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Company Code]                       NVARCHAR (4)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Created By]                         NVARCHAR (12)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Customer Group]                     NVARCHAR (2)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Operator Code]                      NVARCHAR (3)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Portfolio]                          NVARCHAR (3)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Billing Document Category]          NVARCHAR (2)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SD Document Currency]               NVARCHAR (5)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Sales Document]                     NVARCHAR (10)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Billing Item Category]              NVARCHAR (4)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Order Reason]                       NVARCHAR (3)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Payer]                              NVARCHAR (10)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Sales Employee]                     NVARCHAR (8)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Sales Document Item]                NVARCHAR (6)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Sales Document Type]                NVARCHAR (4)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [ASHOP Number]                       NVARCHAR (20)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Channel Account Manager (T)]        NVARCHAR (8)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Distributor Account Manager (T)]    NVARCHAR (8)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SFDC Quote Number]                  NVARCHAR (30)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CRM SWA Quote Number]               NVARCHAR (30)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CPQ Tracking ID]                    NVARCHAR (32)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Purchase Order Type]                NVARCHAR (4)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SFDC Unique Deal ID]                NVARCHAR (14)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Purchase Order No.]                 NVARCHAR (35)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [USG Contract Number]                NVARCHAR (25)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [BillingInvoicing Plan Type]         NVARCHAR (2)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Product Hierarchy]                  NVARCHAR (18)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Standard Cost (USD)]                NUMERIC (17, 2) NULL,
    [Net Value (USD)]                    NUMERIC (17, 2) NULL,
    [Billing Date]                       NVARCHAR (8)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Changed On]                         NVARCHAR (8)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Goods Issue Date]                   NVARCHAR (8)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Acceptance Date]                    NVARCHAR (8)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Billing Start Date]                 NVARCHAR (8)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Prior Day]                          NVARCHAR (1)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Month To Date (MTD)]                NVARCHAR (3)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Quarter To Date (QTD)]              NVARCHAR (3)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Year To Date (YTD)]                 NVARCHAR (8)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Sales Document Category]            NVARCHAR (2)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Billings Std D/C (Doc)]             NUMERIC (17, 2) NULL,
    [Billings Addl D/C (Doc)]            NUMERIC (17, 2) NULL,
    [Billings Freight (Doc)]             NUMERIC (17, 2) NULL,
    [Billings Addl D/C (USD)]            NUMERIC (17, 2) NULL,
    [Billings Freight (USD)]             NUMERIC (17, 2) NULL,
    [Billings Std Cost (Doc)]            NUMERIC (17, 2) NULL,
    [Billings Std Cost (USD)]            NUMERIC (17, 2) NULL,
    [Material Price Group (T)]           NVARCHAR (2)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Material Price Group (M)]           NVARCHAR (2)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Customer Price Group (T)]           NVARCHAR (2)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [Y4 Selling Agent]                   NVARCHAR (10)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [GR Processing Type]                 VARCHAR (18)    COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SWA Order Type]                     NVARCHAR (20)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SIC Source]                         NVARCHAR (10)   COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);

