CREATE TABLE [dbo].[WorkflowTasks] (
    [Created]                                   DATETIME       CONSTRAINT [DF_WorkflowTasks_Created] DEFAULT (getdate()) NULL,
    [WorkItemInstanceID]                        FLOAT (53)     NOT NULL,
    [Action]                                    NVARCHAR (255) NULL,
    [ActionID]                                  FLOAT (53)     NULL,
    [ActionType]                                NVARCHAR (255) NULL,
    [ActionTypeID]                              FLOAT (53)     NULL,
    [AssignedUser]                              NVARCHAR (255) NULL,
    [CreateDate]                                DATETIME       NULL,
    [CreateUser]                                NVARCHAR (255) NULL,
    [DueDate]                                   DATETIME       NULL,
    [DurationSeconds]                           FLOAT (53)     NULL,
    [DurationType]                              NVARCHAR (255) NULL,
    [DurationTypeID]                            FLOAT (53)     NULL,
    [EndDate]                                   DATETIME       NULL,
    [Environment]                               NVARCHAR (255) NULL,
    [EnvironmentID]                             FLOAT (53)     NULL,
    [LastModifiedDate]                          DATETIME       NULL,
    [LastModifiedUser]                          NVARCHAR (255) NULL,
    [Rank]                                      FLOAT (53)     NULL,
    [RootWorkflowInstance]                      NVARCHAR (255) NULL,
    [RootWorkflowInstanceID]                    FLOAT (53)     NULL,
    [StartDate]                                 DATETIME       NULL,
    [StepInstance]                              NVARCHAR (255) NULL,
    [StepInstanceID]                            FLOAT (53)     NULL,
    [Title]                                     NVARCHAR (255) NULL,
    [WorkItemID]                                FLOAT (53)     NULL,
    [WorkItemStatus]                            NVARCHAR (255) NULL,
    [WorkItemStatusID]                          FLOAT (53)     NULL,
    [WorkflowInstance]                          NVARCHAR (255) NULL,
    [WorkflowInstanceID]                        FLOAT (53)     NULL,
    [AssignedUserGroup]                         NVARCHAR (255) NULL,
    [AssignedUserGroupID]                       NVARCHAR (255) NULL,
    [AutoAssignmentType]                        NVARCHAR (255) NULL,
    [AutoAssignmentTypeID]                      FLOAT (53)     NULL,
    [EffortDurationType]                        NVARCHAR (255) NULL,
    [EffortDurationTypeID]                      FLOAT (53)     NULL,
    [EffortSeconds]                             FLOAT (53)     NULL,
    [AssignmentSetInstance]                     NVARCHAR (255) NULL,
    [AssignmentSetInstanceAssignedUser]         NVARCHAR (255) NULL,
    [AssignmentSetInstanceAssignedUserGroup]    NVARCHAR (255) NULL,
    [AssignmentSetInstanceAssignedUserGroupID]  FLOAT (53)     NULL,
    [AssignmentSetInstanceAutoAssignmentType]   NVARCHAR (255) NULL,
    [AssignmentSetInstanceAutoAssignmentTypeID] FLOAT (53)     NULL,
    [AssignmentSetInstanceID]                   FLOAT (53)     NULL,
    [ProjectedAssignedUser]                     NVARCHAR (255) NULL,
    [ProjectedAssignedUserGroup]                NVARCHAR (255) NULL,
    [ProjectedAssignedUserGroupID]              FLOAT (53)     NULL,
    [Coordinator]                               NVARCHAR (255) NULL,
    [IsAssignedUser]                            NVARCHAR (255) NULL,
    [EffortDays]                                FLOAT (53)     NULL,
    [ActualDurationSeconds]                     FLOAT (53)     NULL,
    [ActualDurationDays]                        FLOAT (53)     NULL,
    [IsOverdue]                                 BIT            NOT NULL,
    [OverdueSeconds]                            FLOAT (53)     NULL,
    [OverdueDays]                               FLOAT (53)     NULL,
    CONSTRAINT [PK_WorkflowTasks] PRIMARY KEY CLUSTERED ([WorkItemInstanceID] ASC)
);

