CREATE TABLE [dbo].[WorkflowInstance] (
    [Created]                              DATETIME       CONSTRAINT [DF_WorkflowInstance_Created] DEFAULT (getdate()) NULL,
    [WorkflowInstanceID]                   FLOAT (53)     NOT NULL,
    [BaselineCompletionDate]               DATETIME       NULL,
    [CompleteDate]                         DATETIME       NULL,
    [Coordinator]                          NVARCHAR (255) NULL,
    [CreateDate]                           DATETIME       NULL,
    [CreateUser]                           NVARCHAR (255) NULL,
    [Environment]                          NVARCHAR (255) NULL,
    [EnvironmentID]                        FLOAT (53)     NULL,
    [ExtendedInformationID]                FLOAT (53)     NULL,
    [IsTestMode]                           BIT            NOT NULL,
    [LastModifiedDate]                     DATETIME       NULL,
    [LastModifiedUser]                     NVARCHAR (255) NULL,
    [Name]                                 NVARCHAR (255) NULL,
    [ParentWorkflowInstance]               NVARCHAR (255) NULL,
    [ParentWorkflowInstanceID]             NVARCHAR (255) NULL,
    [RequestedDueDate]                     DATETIME       NULL,
    [RootWorkflowInstance]                 NVARCHAR (255) NULL,
    [RootWorkflowInstanceID]               NVARCHAR (255) NULL,
    [StartDate]                            DATETIME       NULL,
    [UniqueID]                             NVARCHAR (255) NULL,
    [Workflow]                             NVARCHAR (255) NULL,
    [WorkflowID]                           FLOAT (53)     NULL,
    [WorkflowStatus]                       NVARCHAR (255) NULL,
    [WorkflowStatusID]                     FLOAT (53)     NULL,
    [WorkflowType]                         NVARCHAR (255) NULL,
    [WorkflowTypeDataDefinitionGroupID]    NVARCHAR (255) NULL,
    [WorkflowTypeID]                       FLOAT (53)     NULL,
    [WorkflowVersion]                      FLOAT (53)     NULL,
    [WorkflowVersionDataDefinitionGroupID] NVARCHAR (255) NULL,
    [WorkflowVersionID]                    FLOAT (53)     NULL,
    [RequestedWorkflowStatus]              NVARCHAR (255) NULL,
    [RequestedWorkflowStatusID]            NVARCHAR (255) NULL,
    [AutoResumeDate]                       DATETIME       NULL,
    [RootAutoResumeDate]                   DATETIME       NULL,
    CONSTRAINT [PK_WorkflowInstance] PRIMARY KEY CLUSTERED ([WorkflowInstanceID] ASC)
);

