CREATE LOGIN [app_Sky_ro]
    WITH PASSWORD = N'uvwufyvsjvr|{qqwlqb|nmm~msFT7_&#$!~<xgXxi|oljtwO', SID = 0xF1BFD4076488F242B41B0E9A82D0DD4F, DEFAULT_DATABASE = [SkyDB], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

