CREATE view [support].[vw_SalesforceSentiment1]	as
select c.CaseNumber,
c.CaseId,
c.AccountId,
c.AccountName,
c.Theatre,
c.CaseOwnerRole,
d.TransactionDate,
d.Agent,
d.Email,
d.Role,
c.CreatedDate,
d.Score,
d.Magnitude,
d.Emotion,
c.CustomerType,
c.Reason,
c.SubReason,
c.CaseAge,
c.SLA,
c.FCR_New as 'FCR',
c.CSAT,
c.AccountTeam,
c.Origin,
c.Status,
c.ClosedDate,
c.RelatedIncident,
c.ATEscalation,
c.Instance,
c.AtRisk,
c.Feature,
c.SubFeature,
c.ActiveMRR,
d.TranscriptId as 'ID',
'Chat' as TransactionType
from support.Chat_Sentiment3 c join support.Chat_Details d on c.CaseNumber=d.CaseNumber

Union All

Select a.CaseNumber,
a.CaseId,
a.AccountId,
a.AccountName,
a.Theatre,
a.CaseOwnerRole,
b.Date,
b.AgentName,
b.Email,
b.Role,
a.CreatedDate,
b.EmailSentiment,
b.EmailMagnitude,
b.EmailEmotion,
a.CustomerType,
a.Reason,
a.SubReason,
a.CaseAge,
a.SLA,
a.FCR_New as 'FCR',
a.CSAT,
a.AccountTeam,
a.Origin,
a.Status,
a.ClosedDate,
a.RelatedIncident,
a.ATEscalation,
a.Instance,
a.AtRisk,
a.Feature,
a.SubFeature,
a.ActiveMRR,
b.CommentId as 'ID',
'Case Comment' as TransactionType

from support.Email_Emotion1 a join support.Email_Emotion2 b on a.CaseNumber=b.CaseNumber

Union All

Select e.CaseNumber,
e.CaseId,
e.AccountId,
e.AccountName,
e.Theatre,
e.CaseOwnerRole,
f.MessageDate,
f.FromName,
f.FromAddress,
'Customer',
e.CreatedDate,
f.EmailSentiment,
f.EmailMagnitude,
f.EmailEmotion,
e.CustomerType,
e.Reason,
e.SubReason,
e.CaseAge,
e.SLA,
e.FCR_New as 'FCR',
e.CSAT,
e.AccountTeam,
e.Origin,
e.Status,
e.ClosedDate,
e.RelatedIncident,
e.ATEscalation,
e.Instance,
e.AtRisk,
e.Feature,
e.SubFeature,
e.ActiveMRR,
f.EmailId as 'ID',
'Email' as TransactionType

from support.Email_Sentiment e join support.Email_Details f on e.CaseNumber=f.CaseNumber