CREATE TABLE [Tableau].[mVwGlobalPipeline_EU] (
    [Region]                                      VARCHAR (2)     NOT NULL,
    [Ac Name]                                     NVARCHAR (100)  NULL,
    [IsBillable]                                  INT             NULL,
    [Ac Team]                                     NVARCHAR (32)   NULL,
    [Platform]                                    NVARCHAR (20)   NULL,
    [OneTimeCharge]                               NUMERIC (38, 6) NULL,
    [OneTimeCharge_LC]                            MONEY           NULL,
    [MonthlyCharge]                               NUMERIC (38, 6) NULL,
    [MonthlyCharge_LC]                            MONEY           NULL,
    [Prod Category]                               NVARCHAR (50)   NULL,
    [ProdSubCategory]                             NVARCHAR (50)   NULL,
    [Prod Name]                                   NVARCHAR (128)  NULL,
    [Prod ShortName]                              NVARCHAR (128)  NULL,
    [Order Sales Opp Number]                      VARCHAR (128)   NULL,
    [Class Group]                                 NVARCHAR (50)   NULL,
    [Revenue Component]                           NVARCHAR (50)   NULL,
    [IsCrossSellProduct]                          BIT             NULL,
    [ForecastDate]                                DATE            NULL,
    [DateSvcLiveActual]                           DATE            NULL,
    [OrderStatus]                                 NVARCHAR (20)   NULL,
    [OrderType]                                   NVARCHAR (50)   NULL,
    [MasterOrderType]                             NVARCHAR (50)   NULL,
    [BillingStage]                                VARCHAR (17)    NOT NULL,
    [Cluster]                                     NCHAR (100)     NULL,
    [FirstName]                                   NVARCHAR (120)  NULL,
    [LastName]                                    NVARCHAR (120)  NULL,
    [OrderId]                                     INT             NULL,
    [OrderDate]                                   DATETIME2 (4)   NULL,
    [SeatCount]                                   INT             NULL,
    [DateBillingStart]                            DATE            NULL,
    [ServiceId]                                   INT             NOT NULL,
    [DateSvcCreated]                              DATE            NULL,
    [Loc Name]                                    NVARCHAR (200)  NULL,
    [ServiceStatus]                               NVARCHAR (128)  NULL,
    [OrderCreatedBy]                              NVARCHAR (120)  NULL,
    [ProductId]                                   INT             NULL,
    [Order PM]                                    NVARCHAR (241)  NULL,
    [AvgLife Days]                                VARCHAR (10)    NULL,
    [OppCloseDate]                                DATE            NULL,
    [ContractStartDate]                           DATE            NULL,
    [ContractCreateDate]                          DATETIME2 (7)   NULL,
    [OpportunityNumber]                           VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [VoidDate]                                    DATE            NULL,
    [CCClusterName]                               NCHAR (100)     NULL,
    [CCPlatformName]                              NVARCHAR (20)   NULL,
    [SFDC_PM_Role]                                VARCHAR (1)     NOT NULL,
    [PM_Id]                                       VARCHAR (1)     NOT NULL,
    [ContractType]                                NVARCHAR (100)  NULL,
    [SMRClusterName]                              NCHAR (100)     NULL,
    [SMRPlatformName]                             NVARCHAR (20)   NULL,
    [AccountId]                                   VARCHAR (13)    NULL,
    [BOSSPMRole]                                  VARCHAR (18)    NULL,
    [ContractProfileAmount]                       INT             NULL,
    [OppProfileAmount]                            VARCHAR (10)    NULL,
    [ContractNumber]                              VARCHAR (128)   NULL,
    [LocationState]                               NVARCHAR (100)  NULL,
    [ServiceCluster]                              NCHAR (100)     NULL,
    [Master_PMName]                               VARCHAR (7)     NOT NULL,
    [Master_PMId]                                 INT             NULL,
    [ProjectOwnerName]                            VARCHAR (500)   COLLATE Latin1_General_BIN NULL,
    [ProjectDelayReason]                          VARCHAR (255)   COLLATE Latin1_General_BIN NULL,
    [ProjectDelayDescription]                     TEXT            COLLATE Latin1_General_BIN NULL,
    [MonthMRRLastInvoiced]                        DATE            NULL,
    [LocationId]                                  INT             NULL,
    [IsMCSSEnabled]                               INT             NULL,
    [TF_ProjectNumber]                            VARCHAR (18)    NULL,
    [TF_StartDate]                                DATETIME        NULL,
    [TF_EndDate]                                  DATETIME        NULL,
    [TF_Stage]                                    VARCHAR (50)    NULL,
    [TF_PctComplete]                              FLOAT (53)      NULL,
    [CustomerSegmentByProfileSize]                VARCHAR (3)     NOT NULL,
    [DS_ActivationStatusRollup]                   VARCHAR (12)    NOT NULL,
    [Staffing_WorkdayName]                        NVARCHAR (255)  NULL,
    [Staffing_OrderPM_BOSS]                       NVARCHAR (255)  NULL,
    [Staffing_OrderAssignee]                      NVARCHAR (255)  NULL,
    [Staffing_OrderAssigneeManager]               NVARCHAR (255)  NULL,
    [Staffing_OrderAssigneeGroup]                 NVARCHAR (255)  NULL,
    [Staffing_OrderAssigneeCenter]                NVARCHAR (255)  NULL,
    [Staffing_OrderAssigneeRegion]                NVARCHAR (255)  NULL,
    [Staffing_OrderAssigneeStatus]                NVARCHAR (255)  NULL,
    [Staffing_OrderAssigneePOD]                   NVARCHAR (255)  NULL,
    [Staffing_OrderAssigneeStartDate]             DATETIME        NULL,
    [Staffing_OrderAssigneeEndDate]               DATETIME        NULL,
    [Staffing_CalcPMMRRGoalfortheMonth]           MONEY           NULL,
    [PartnerName]                                 VARCHAR (100)   NULL,
    [CSD_MA]                                      VARCHAR (150)   NULL,
    [DateServiceClosed]                           DATE            NULL,
    [FirstInvoice]                                DATE            NULL,
    [TF Color Number]                             VARCHAR (10)    COLLATE Latin1_General_BIN NULL,
    [MigrationDate]                               DATE            NULL,
    [DS_ActivationStatusRollup_TEST]              VARCHAR (12)    NOT NULL,
    [DateBillingValidTo]                          DATE            NULL,
    [DateSvcSetToActive]                          DATE            NULL,
    [isPartnerAccount]                            VARCHAR (3)     NOT NULL,
    [TF Proj Percent Complete]                    FLOAT (53)      NULL,
    [TF Tsk Project Start Date Start Date]        DATETIME        NULL,
    [TF Tsk Project Start Date Sch End Date]      DATETIME        NULL,
    [TF Tsk Project Start Date Complete Date]     DATETIME        NULL,
    [Account is in SFDC]                          VARCHAR (3)     NOT NULL,
    [Customer Success Manager]                    VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [TF Tsk Project Start Date Status]            VARCHAR (25)    COLLATE Latin1_General_BIN NULL,
    [Opportunity Welcome Contact]                 VARCHAR (150)   NULL,
    [Opportunity NCAM]                            VARCHAR (150)   NULL,
    [Opportunity CAM]                             VARCHAR (150)   NULL,
    [Opportunity C-TAM]                           VARCHAR (150)   NULL,
    [Opportunity ISR]                             VARCHAR (500)   NULL,
    [Opportunity Sub Agent]                       VARCHAR (100)   NULL,
    [Opportunity Territory]                       NVARCHAR (255)  NULL,
    [TF Board Sfdc Id]                            VARCHAR (18)    NULL,
    [TF Tsk BRD Sign-Off Start Date]              DATETIME        NULL,
    [TF Tsk BRD Sign-Off End Date]                DATETIME        NULL,
    [TF Tsk BRD Sign-Off Complete Date]           DATETIME        NULL,
    [TF Tsk BRD Sign-Off Status]                  VARCHAR (25)    NULL,
    [TF Tsk Trans To Support Start Date]          DATETIME        NULL,
    [TF Tsk Trans To Support Sch End Date]        DATETIME        NULL,
    [TF Tsk Trans To Support Complete Date]       DATETIME        NULL,
    [TF Tsk Trans To Support Status]              VARCHAR (25)    NULL,
    [TF Board Last Modified]                      DATETIME        NULL,
    [ServiceCommitmentDate]                       DATETIME        NULL,
    [TF Tsk Cust Audit Approval Start Date]       DATETIME        NULL,
    [TF Tsk Cust Audit Approval End Date]         DATETIME        NULL,
    [TF Tsk Cust Audit Approval Complete Date]    DATETIME        NULL,
    [TF Tsk Cust Audit Approval Status]           VARCHAR (25)    NULL,
    [Accelerated Timeline Initiative Update Date] DATETIME        NULL,
    [Accelerated Timeline Initiative Description] VARCHAR (MAX)   NULL,
    [BusinessTermVersion]                         NUMERIC (9, 2)  NULL,
    [TF Tsk Port In Research Start Date]          DATETIME        NULL,
    [TF Tsk Port In Research End Date]            DATETIME        NULL,
    [TF Tsk Port In Research Complete Date]       DATETIME        NULL,
    [TF Tsk Port In Research Status]              VARCHAR (25)    NULL,
    [TF Tsk Order New Numbers Start Date]         DATETIME        NULL,
    [TF Tsk Order New Numbers End Date]           DATETIME        NULL,
    [TF Tsk Order New Numbers Complete Date]      DATETIME        NULL,
    [TF Tsk Order New Numbers Status]             VARCHAR (25)    NULL,
    [TF Tsk Order Hardware Start Date]            DATETIME        NULL,
    [TF Tsk Order Hardware End Date]              DATETIME        NULL,
    [TF Tsk Order Hardware Complete Date]         DATETIME        NULL,
    [TF Tsk Order Hardware Status]                VARCHAR (25)    NULL,
    [TF Tsk Port Submitted Start Date]            DATETIME        NULL,
    [TF Tsk Port Submitted End Date]              DATETIME        NULL,
    [TF Tsk Port Submitted Complete Date]         DATETIME        NULL,
    [TF Tsk Port Submitted Status]                VARCHAR (25)    NULL,
    [TF Tsk System Programming Start Date]        DATETIME        NULL,
    [TF Tsk System Programming End Date]          DATETIME        NULL,
    [TF Tsk System Programming Complete Date]     DATETIME        NULL,
    [TF Tsk System Programming Status]            VARCHAR (25)    NULL,
    [TF Tsk Ready To Test Start Date]             DATETIME        NULL,
    [TF Tsk Ready To Test End Date]               DATETIME        NULL,
    [TF Tsk Ready To Test Complete Date]          DATETIME        NULL,
    [TF Tsk Ready To Test Status]                 VARCHAR (25)    NULL,
    [TF Tsk Port Scheduled Start Date]            DATETIME        NULL,
    [TF Tsk Port Scheduled End Date]              DATETIME        NULL,
    [TF Tsk Port Scheduled Complete Date]         DATETIME        NULL,
    [TF Tsk Port Scheduled Status]                VARCHAR (25)    NULL,
    [TF Tsk Pre Go Live Testing Start Date]       DATETIME        NULL,
    [TF Tsk Pre Go Live Testing End Date]         DATETIME        NULL,
    [TF Tsk Pre Go Live Testing Compelte Date]    DATETIME        NULL,
    [TF Tsk Pre Go Live Testing Status]           VARCHAR (25)    NULL,
    [NoteId]                                      VARCHAR (25)    NULL,
    [NoteTitle]                                   VARCHAR (250)   NULL,
    [NoteModifiedDate]                            DATETIME        NULL,
    [NoteModifiedBy]                              VARCHAR (150)   NULL,
    [ContractId]                                  VARCHAR (18)    NULL,
    [MigrationOrderId]                            INT             NOT NULL,
    [MigrationOrderStatus]                        VARCHAR (1)     NOT NULL,
    [MigrationCloseOrderStatus]                   VARCHAR (1)     NOT NULL,
    [MigrationOrderDeprovisionDate]               DATETIME        NOT NULL,
    [OrderSalesContractId]                        VARCHAR (13)    NULL,
    [PortingOrderDate]                            DATETIME2 (4)   NULL,
    [LNPRequestDate]                              DATETIME        NULL,
    [FOCDate]                                     DATETIME        NULL,
    [TaskfeedBoardType]                           VARCHAR (50)    NULL,
    [TF Tsk Net Readiness Start Date]             DATETIME        NULL,
    [TF Tsk Net Readiness End Date]               DATETIME        NULL,
    [TF Tsk Net Readiness Complete Date]          DATETIME        NULL,
    [TF Tsk Net Readiness Status]                 VARCHAR (25)    NULL,
    [TF_Project_Board_Notes]                      VARCHAR (MAX)   NULL,
    [TF_External_Sharing]                         VARCHAR (25)    NULL,
    [OppRecordType]                               VARCHAR (100)   NULL,
    [OppType]                                     VARCHAR (100)   NULL,
    [OppStage]                                    VARCHAR (500)   NULL,
    [OppOwner]                                    VARCHAR (500)   NULL,
    [Partner of Record Cloud]                     VARCHAR (100)   NULL,
    [Partner of Record Onsite]                    VARCHAR (100)   NULL,
    [BOSS_Support_Partner__c]                     VARCHAR (25)    COLLATE Latin1_General_BIN NULL,
    [MiCloud_Connect_Business_Model__c]           VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [PartnerDisplayName__c]                       VARCHAR (125)   COLLATE Latin1_General_BIN NULL,
    [PartnerSupportEmailAddress__c]               VARCHAR (150)   COLLATE Latin1_General_BIN NULL,
    [PartnerSupportInformation__c]                VARCHAR (255)   COLLATE Latin1_General_BIN NULL,
    [PartnerSupportPhoneNumber__c]                VARCHAR (40)    COLLATE Latin1_General_BIN NULL,
    [PartnerSupportWebPage__c]                    VARCHAR (255)   COLLATE Latin1_General_BIN NULL,
    [Support_Partner_Enabled__c]                  VARCHAR (5)     COLLATE Latin1_General_BIN NULL,
    [Total #s to LNP]                             INT             NULL,
    [TF_MDBoard_Mod_Date]                         DATETIME        NULL,
    [TF_MDBoard_Delay_Reason]                     VARCHAR (50)    NULL,
    [TF_MDBoard_Notes]                            NVARCHAR (120)  NULL,
    [TF_MDBoard_Delay_Description]                TEXT            NULL,
    [TF_MDBoard_Project_Number]                   VARCHAR (18)    NULL,
    [TF_MDBoard_SFDCID]                           VARCHAR (18)    NULL,
    [Debooked Opportunity]                        VARCHAR (3)     COLLATE Latin1_General_BIN NULL,
    [PRA Score]                                   VARCHAR (15)    NULL,
    [Parent Profile]                              VARCHAR (255)   NULL,
    [OrderCloseDate]                              DATE            NULL
);

