/****** Script for SelectTopNRows command from SSMS  ******/
CREATE view Tax.[Vw_Boss_201908_Processed] as
SELECT [Env]
      ,convert(int, [CustID]) CUSTID
      ,[Account Number]
      ,[Customer Name]
      ,[Parent Acct #]
      ,[Parent Customer Name]
      ,[BillCyclePeriodCode]
      ,[Bill Cycle]
      ,[Market]
      ,[AccountTypeID]
      ,[Account Type]
      ,[Tax Acct Type]
      ,[Invoice Group]
      ,[Invoice Date]
      ,[Invoice Number]
      ,[UsgSvcID]
      ,[Service Number]
      ,[Service Name]
      ,[Service Address]
      ,[Service City]
      ,[Service State]
      ,[Service Zip]
      ,[Service Country]
      ,[NonUsgSvcID]
      ,[SKU]
      ,[Product]
      ,[Charge Start Date]
      ,[Charge End Date]
      ,[DistanceID]
      ,[Product Distance Type]
      ,[TaxClassID]
      ,[Product Tax Class]
      ,[Usage Type Taxed]
      ,[TaxID]
      ,[Tax On Intrastate]
      ,[Tax On Interstate]
      ,[Tax On International]
      ,[Is Per LineTax]
      ,[Is E911 Tax]
      ,[Exemption Classification]
      ,[Flat Fee]
      ,[MIN Tier Amount]
      ,[Tax State]
      ,[Tax Name]
      ,[UsageTypeID]
	  ,convert(int, [Quantity]) Quantity
      ,convert (money, [Taxable Charges]) [Taxable Charges]
      ,convert (float, [Tax Rate Used]) [Tax Rate Used]
      ,convert (money, [Tax Due]) [Tax Due]
      ,convert (money, [Total Charges])[Total Charges]
  FROM [Tax].[Vw_Boss_201908]
