 Create Procedure QMS_LoadConnectCustFromPhoneHome as 
IF OBJECT_ID('QMS_CUSTLIST_CONNECTCUSTOMER', 'U') IS NOT NULL
drop table QMS_CUSTLIST_CONNECTCUSTOMER
select * into QMS_CUSTLIST_CONNECTCUSTOMER
From V_QMS_CUSTLIST_CONNECTCUSTOMER