CREATE TABLE [hana].[mVwCustomerMaster] (
    [Account Manager Key]                VARCHAR (8)   NULL,
    [Account Manager Name]               NVARCHAR (40) NULL,
    [Blue SFDC ID]                       NVARCHAR (18) NULL,
    [BOSS AU ID]                         NVARCHAR (20) NULL,
    [BOSS EU ID]                         NVARCHAR (20) NULL,
    [BOSS US ID]                         NVARCHAR (20) NULL,
    [Channel Hierarchy Level 1]          NVARCHAR (8)  NULL,
    [Channel Hierarchy Level 2]          NVARCHAR (8)  NULL,
    [Channel Type Key]                   NVARCHAR (3)  NULL,
    [Channel Type Name]                  NVARCHAR (40) NULL,
    [City]                               NVARCHAR (35) NULL,
    [Company Size Name]                  NVARCHAR (60) NULL,
    [CostGuard DE ID]                    NVARCHAR (20) NULL,
    [CostGuard UK ID]                    NVARCHAR (20) NULL,
    [CostGuard US ID]                    NVARCHAR (20) NULL,
    [Country Key]                        NVARCHAR (3)  NULL,
    [Country Name]                       NVARCHAR (20) NULL,
    [Customer Account Group Name]        NVARCHAR (40) NULL,
    [Customer Hierarchy Level 1 Key]     NVARCHAR (10) NULL,
    [Customer Hierarchy Level 1 Name]    VARCHAR (60)  NULL,
    [Customer Hierarchy Level 2 Key]     NVARCHAR (10) NULL,
    [Customer Hierarchy Level 2 Name]    VARCHAR (60)  NULL,
    [Customer Name]                      NVARCHAR (35) NULL,
    [Customer Number]                    NVARCHAR (10) NOT NULL,
    [Distributor of Record Key]          VARCHAR (10)  NULL,
    [Distributor of Record Name]         NVARCHAR (40) NULL,
    [DUNS Number]                        NVARCHAR (9)  NULL,
    [End Customer Reporting Region (M)]  NVARCHAR (40) NULL,
    [High Level Vertical]                NVARCHAR (60) NULL,
    [KNA1 Count]                         INT           NULL,
    [Managed System]                     NVARCHAR (15) NULL,
    [Managed System ID]                  NVARCHAR (20) NULL,
    [Mitel User Group]                   NVARCHAR (1)  NULL,
    [Orange SFDC ID]                     NVARCHAR (18) NULL,
    [Partner Level Key]                  NVARCHAR (2)  NULL,
    [Partner Level Name]                 NVARCHAR (20) NULL,
    [Postal Code / ZIP]                  NVARCHAR (10) NULL,
    [Postal Code / ZIP (Short)]          NVARCHAR (10) NULL,
    [Region]                             NVARCHAR (40) NULL,
    [Reseller Partner Channel Type Key]  NVARCHAR (3)  NULL,
    [Reseller Partner Channel Type Name] NVARCHAR (40) NULL,
    [Reseller Partner Key]               VARCHAR (10)  NULL,
    [Reseller Partner Name]              NVARCHAR (40) NULL,
    [Sales Area]                         NVARCHAR (40) NULL,
    [SIC Code 1 Key]                     NVARCHAR (4)  NULL,
    [SIC Code 1 Name]                    NVARCHAR (60) NULL,
    [SIC Code 2 Key]                     NVARCHAR (4)  NULL,
    [SIC Code 2 Name]                    NVARCHAR (60) NULL,
    [SIC Code 3 Key]                     NVARCHAR (4)  NULL,
    [SIC Code 3 Name]                    NVARCHAR (60) NULL,
    [SIC Code 4 Key]                     NVARCHAR (4)  NULL,
    [SIC Code 4 Name]                    NVARCHAR (60) NULL,
    [State /Province Key]                NVARCHAR (3)  NULL,
    [State /Province Text]               NVARCHAR (20) NULL,
    [Street Address]                     NVARCHAR (35) NULL,
    [Sub Region]                         NVARCHAR (40) NULL,
    [Sub Territory Key]                  NVARCHAR (4)  NULL,
    [Sub Territory Name]                 NVARCHAR (40) NULL,
    [Sub Theatre]                        NVARCHAR (40) NULL,
    [Territory]                          NVARCHAR (50) NULL,
    [Theatre]                            NVARCHAR (40) NULL,
    [Vertical]                           NVARCHAR (60) NULL
);

