CREATE TABLE [crimson].[Address] (
    [address_id]            INT             NOT NULL,
    [line1]                 NVARCHAR (255)  NOT NULL,
    [line2]                 NVARCHAR (255)  NULL,
    [city]                  NVARCHAR (255)  NOT NULL,
    [state_abbrev]          NVARCHAR (2)    NOT NULL,
    [zip]                   NVARCHAR (255)  NOT NULL,
    [county]                NVARCHAR (255)  NULL,
    [latitude]              NUMERIC (28, 6) NULL,
    [longitude]             NUMERIC (28, 6) NULL,
    [location_point]        NVARCHAR (255)  NULL,
    [intersection]          NVARCHAR (255)  NULL,
    [barcode_digits]        NVARCHAR (255)  NULL,
    [congress_code]         NVARCHAR (255)  NULL,
    [county_name]           NVARCHAR (255)  NULL,
    [fragment_house]        NVARCHAR (255)  NULL,
    [fragment_pmbnumber]    NVARCHAR (255)  NULL,
    [fragment_pmbprefix]    NVARCHAR (255)  NULL,
    [fragment_postdir]      NVARCHAR (255)  NULL,
    [fragment_predir]       NVARCHAR (255)  NULL,
    [fragment_street]       NVARCHAR (255)  NULL,
    [fragment_suffix]       NVARCHAR (255)  NULL,
    [fragment_unit]         NVARCHAR (255)  NULL,
    [tract]                 NVARCHAR (255)  NULL,
    [block]                 NVARCHAR (255)  NULL,
    [area_code]             NVARCHAR (255)  NULL,
    [city_abbreviation]     NVARCHAR (255)  NULL,
    [city_type]             NVARCHAR (255)  NULL,
    [county_fips]           NVARCHAR (255)  NULL,
    [state_fips]            NVARCHAR (255)  NULL,
    [timezone]              NVARCHAR (255)  NULL,
    [daylight_savings]      VARCHAR (5)     NULL,
    [msa]                   NVARCHAR (255)  NULL,
    [md]                    NVARCHAR (255)  NULL,
    [cbsa]                  NVARCHAR (255)  NULL,
    [pmsa]                  NVARCHAR (255)  NULL,
    [dma]                   NVARCHAR (255)  NULL,
    [zip_latitude]          NUMERIC (28, 6) NULL,
    [zip_longitude]         NUMERIC (28, 6) NULL,
    [areahouseholdincome]   NUMERIC (28, 6) NULL,
    [countyhouseholdincome] NUMERIC (28, 6) NULL,
    [statehouseholdincome]  NUMERIC (28, 6) NULL,
    [geocode_level]         NVARCHAR (255)  NULL,
    [create_user_id]        INT             NOT NULL,
    [create_timestamp]      DATETIME2 (7)   NOT NULL,
    [last_mod_user_id]      INT             NOT NULL,
    [last_mod_timestamp]    DATETIME2 (7)   NOT NULL,
    [dpv]                   NVARCHAR (255)  NULL,
    [dpvnotes]              NVARCHAR (255)  NULL,
    [corrections]           NVARCHAR (255)  NULL,
    [country_code_value]    NVARCHAR (255)  NOT NULL
);

