CREATE TABLE [crimson].[BusinessEntity] (
    [business_entity_id]        INT              NOT NULL,
    [parent_business_entity_id] INT              NULL,
    [owning_business_entity_id] INT              NULL,
    [primary_location_id]       INT              NULL,
    [parent_external_id]        NVARCHAR (255)   NULL,
    [external_id]               NVARCHAR (255)   NULL,
    [tax_identification_number] NVARCHAR (255)   NULL,
    [informal_entity_name]      NVARCHAR (255)   NULL,
    [legal_entity_name]         NVARCHAR (255)   NOT NULL,
    [is_vendor]                 VARCHAR (5)      NULL,
    [is_client]                 VARCHAR (5)      NULL,
    [is_operating_company]      VARCHAR (5)      NULL,
    [email]                     NVARCHAR (80)    NULL,
    [phone]                     NVARCHAR (40)    NULL,
    [fax]                       NVARCHAR (255)   NULL,
    [tollfree_phone]            NVARCHAR (255)   NULL,
    [contact_last_name]         NVARCHAR (100)   NULL,
    [contact_first_name]        NVARCHAR (100)   NULL,
    [reporting_time_zone_value] NVARCHAR (255)   NULL,
    [org_structure_value]       NVARCHAR (255)   NULL,
    [effective_date]            DATE             NOT NULL,
    [accounting_code]           NVARCHAR (255)   NULL,
    [create_user_id]            INT              NOT NULL,
    [create_timestamp]          DATETIME2 (7)    NOT NULL,
    [last_mod_user_id]          INT              NOT NULL,
    [last_mod_timestamp]        DATETIME2 (7)    NOT NULL,
    [delete_user_id]            INT              NULL,
    [delete_timestamp]          DATETIME2 (7)    NULL,
    [sf_record_id]              NVARCHAR (100)   NULL,
    [business_entity_uuid]      UNIQUEIDENTIFIER NULL,
    [invoice_distribution]      NVARCHAR (255)   NULL
);

