CREATE TABLE [crimson].[Client] (
    [business_entity_id]                     INT             NOT NULL,
    [is_reseller]                            VARCHAR (5)     NOT NULL,
    [is_tax_exempt]                          VARCHAR (5)     NOT NULL,
    [account_type_value]                     NVARCHAR (255)  NOT NULL,
    [disable_over_limit]                     VARCHAR (5)     NOT NULL,
    [credit_limit]                           NUMERIC (28, 6) NULL,
    [warning_credit_limit]                   NUMERIC (28, 6) NULL,
    [last_bill_amount]                       NUMERIC (28, 6) NULL,
    [account_balance]                        NUMERIC (28, 6) NOT NULL,
    [auto_recharge_amount]                   NUMERIC (28, 6) NULL,
    [create_user_id]                         INT             NOT NULL,
    [create_timestamp]                       DATETIME2 (7)   NOT NULL,
    [last_mod_user_id]                       INT             NOT NULL,
    [last_mod_timestamp]                     DATETIME2 (7)   NOT NULL,
    [account_number]                         INT             NOT NULL,
    [unbilled_charges]                       NUMERIC (28, 6) NULL,
    [notified_near_limit_timestamp]          DATETIME2 (7)   NULL,
    [notified_over_limit_timestamp]          DATETIME2 (7)   NULL,
    [customer_profile_id]                    INT             NULL,
    [account_status_value]                   NVARCHAR (255)  NOT NULL,
    [auto_load_enabled]                      VARCHAR (5)     NOT NULL,
    [auto_load_start_timestamp]              DATETIME2 (7)   NULL,
    [auto_load_end_timestamp]                DATETIME2 (7)   NULL,
    [auto_load_threshold_amount]             NUMERIC (28, 6) NULL,
    [auto_load_target_balance]               NUMERIC (28, 6) NULL,
    [is_taxable]                             VARCHAR (5)     NOT NULL,
    [tax_exemption_code]                     NVARCHAR (255)  NULL,
    [generate_invoice_detail]                VARCHAR (5)     NOT NULL,
    [summary_invoice_template_id]            INT             NULL,
    [detail_invoice_template_id]             INT             NULL,
    [credit_limit_increase]                  NUMERIC (28, 6) NULL,
    [credit_limit_increase_expire_timestamp] DATETIME2 (7)   NULL,
    [account_status_reason_value]            NVARCHAR (255)  NULL,
    [account_status_timestamp]               DATETIME2 (7)   NULL,
    [is_test_account]                        VARCHAR (5)     NOT NULL,
    [currency_value]                         NVARCHAR (255)  NOT NULL
);

