CREATE TABLE [crimson].[Product] (
    [product_id]                           INT              NOT NULL,
    [business_entity_id]                   INT              NOT NULL,
    [external_product_id]                  NVARCHAR (32)    NULL,
    [accounting_product_id]                INT              NOT NULL,
    [product_name]                         NVARCHAR (255)   NOT NULL,
    [billing_type_value]                   NVARCHAR (255)   NOT NULL,
    [ui_description]                       NVARCHAR (4000)  NULL,
    [charging_model_value]                 NVARCHAR (255)   NOT NULL,
    [invoice_description]                  NVARCHAR (500)   NULL,
    [expanded_description]                 NVARCHAR (500)   NULL,
    [default_price]                        NUMERIC (28, 6)  NULL,
    [is_base_product]                      VARCHAR (5)      NOT NULL,
    [is_default]                           VARCHAR (5)      NOT NULL,
    [product_category_id]                  INT              NOT NULL,
    [unit_of_measure_value]                NVARCHAR (255)   NOT NULL,
    [contract_required]                    VARCHAR (5)      NOT NULL,
    [is_billable]                          VARCHAR (5)      NOT NULL,
    [can_discount]                         VARCHAR (5)      NOT NULL,
    [billing_minimum]                      INT              NOT NULL,
    [billing_increment]                    INT              NULL,
    [bill_minimum_unit_of_measure_value]   NVARCHAR (255)   NOT NULL,
    [bill_increment_unit_of_measure_value] NVARCHAR (255)   NOT NULL,
    [minimum_low_sell_price]               NUMERIC (28, 6)  NULL,
    [target_sell_price]                    NUMERIC (28, 6)  NULL,
    [available_for_sale]                   VARCHAR (5)      NOT NULL,
    [uses_rate_deck_pricing]               VARCHAR (5)      NOT NULL,
    [effective_user_id]                    INT              NOT NULL,
    [effective_timestamp]                  DATETIME2 (7)    NOT NULL,
    [expire_timestamp]                     DATETIME2 (7)    NULL,
    [create_user_id]                       INT              NOT NULL,
    [create_timestamp]                     DATETIME2 (7)    NOT NULL,
    [last_mod_user_id]                     INT              NOT NULL,
    [last_mod_timestamp]                   DATETIME2 (7)    NOT NULL,
    [product_uuid]                         UNIQUEIDENTIFIER NOT NULL,
    [bill_timing_value]                    NVARCHAR (255)   NOT NULL,
    [sf_record_id]                         NVARCHAR (255)   NULL,
    [sf_last_sync_timestamp]               DATETIME2 (7)    NULL,
    [default_product_rate_deck_id]         INT              NULL,
    [is_lease]                             VARCHAR (5)      NOT NULL,
    [cost]                                 NUMERIC (28, 6)  NULL,
    [bill_quantity_as_minimum]             VARCHAR (5)      NOT NULL,
    [includes_usage]                       VARCHAR (5)      NOT NULL,
    [included_usage_per_unit]              INT              NULL,
    [includes_unlimited_usage]             VARCHAR (5)      NOT NULL,
    [is_vendor_product]                    VARCHAR (5)      NOT NULL,
    [is_wholesale]                         VARCHAR (5)      NOT NULL,
    [shoretel_category]                    NVARCHAR (255)   NULL
);

