
create View [AX_Available_Inventory_to_BacklogStg]
as
SELECT INVENTSUM.ITEMID,
INVENTTABLE.ITEMNAME,
INVENTDIM.INVENTLOCATIONID,
INVENTSUM.AVAILPHYSICAL,
INVENTSUM.ONORDER,
INVENTSUM.RESERVPHYSICAL
FROM   ([SVLCORPAXDBDEV].[TRAIN].dbo.INVENTSUM INNER JOIN [SVLCORPAXDBDEV].[TRAIN].dbo.INVENTDIM ON (INVENTSUM.INVENTDIMID=INVENTDIM.INVENTDIMID) AND (INVENTSUM.DATAAREAID=INVENTDIM.DATAAREAID))
INNER JOIN [SVLCORPAXDBDEV].[TRAIN].dbo.INVENTTABLE ON (INVENTSUM.ITEMID=INVENTTABLE.ITEMID) AND (INVENTSUM.DATAAREAID=INVENTTABLE.DATAAREAID)
WHERE  STINVENTORYBACKLOG = 1