


CREATE View [dbo].[AX_Available_Inventory_to_Backlog]
as
SELECT INVENTSUM.ITEMID,
INVENTTABLE.ITEMNAME,
INVENTDIM.INVENTLOCATIONID,
INVENTSUM.AVAILPHYSICAL,
INVENTSUM.ONORDER,
INVENTSUM.RESERVPHYSICAL,
INVENTSUM.PHYSICALINVENT
FROM   ([SVLCORPAXDB1].[PROD].dbo.INVENTSUM INNER JOIN [SVLCORPAXDB1].[PROD].dbo.INVENTDIM ON (INVENTSUM.INVENTDIMID=INVENTDIM.INVENTDIMID) AND (INVENTSUM.DATAAREAID=INVENTDIM.DATAAREAID))
INNER JOIN [SVLCORPAXDB1].[PROD].dbo.INVENTTABLE ON (INVENTSUM.ITEMID=INVENTTABLE.ITEMID) AND (INVENTSUM.DATAAREAID=INVENTTABLE.DATAAREAID)
WHERE  STINVENTORYBACKLOG = 1

