



CREATE View [dbo].[AX_Backlog_GS2]
as
 
 SELECT 
 SALESTABLE.CREATEDDATETIME
 , SALESTABLE.SALESID
 , SALESTABLE.PURCHORDERFORMNUM
 , SALESTABLE.SEMENDCUST
 , SALESLINE.NAME
 , SALESLINE.SALESSTATUS
 , SALESLINE.QTYORDERED
 , SALESLINE.ITEMID
 , SALESLINE.CURRENCYCODE
 , SALESLINE.SHIPPINGDATECONFIRMED
 , SALESLINE.LINEAMOUNT
 , SALESLINE.REMAINSALESPHYSICAL
 , SALESTABLE.SEMPOSTINGORDERTYPE
 , SALESLINE.SHIPPINGDATEREQUESTED
 , SALESTABLE.SEMRESELLERNAME
 , SALESTABLE.EMAIL
 , SALESTABLE.INVOICEACCOUNT
  ,INVENTTABLE.ITEMGROUPID
  ,p.SALESPOOLID
    ,p.Name as 'Partner Name'
  --,CUSTTABLE.AccountNum
  --, ex.CURRENCYCODE
  ,e.EXCHRATE
   ,EC.Name as 'EndCustomer Name'
   ,INVENTTABLE.DIMENSION2_ as 'Dimension2'
  
 FROM   [SVLCORPAXDB1].PROD.dbo.SALESLINE SALESLINE
  INNER JOIN [SVLCORPAXDB1].PROD.dbo.SALESTABLE SALESTABLE
   ON SALESLINE.SALESID=SALESTABLE.SALESID
  JOIN [SVLCORPAXDB1].[PROD].dbo.INVENTTABLE
  on INVENTTABLE.ITEMID = SALESLINE.ITEMID
  left outer join SVLCORPAXDB1.PROD.dbo.CustTable p
   on    SALESTABLE.INVOICEACCOUNT = p.AccountNum 
        left outer join SVLCORPAXDB1.PROD.dbo.CustTable EC
   on    SALESTABLE.SEMENDCUST = EC.AccountNum 
   left outer join
	( 
	select  ex.CURRENCYCODE, ex.EXCHRATE from SVLCORPAXDB1.PROD.dbo.Exchrates ex
	join (select   CURRENCYCODE,  max(FROMDATE) as 'FROMDATE' from SVLCORPAXDB1.PROD.dbo.Exchrates group by CURRENCYCODE ) exc
	on exc.FROMDATE = ex.FROMDATE and exc.CURRENCYCODE = ex.CURRENCYCODE
	) e
	   on e.CURRENCYCODE = SALESLINE.CURRENCYCODE
        where
 SALESLINE.REMAINSALESPHYSICAL <> 0 
--  SALESLINE.SALESSTATUS = 1 
-- and
--INVENTTABLE.ITEMGROUPID in ('EXP', 'SRVC' , 'TRVL')
 --ORDER BY SALESLINE.NAME, SALESLINE.SHIPPINGDATECONFIRMED, SALESTABLE.SALESID






