


CREATE view [dbo].[SFDC_ASSET_DEV] as 

SELECT     
	CUSTINVOICETRANS.INVOICEID, 
	CUSTINVOICETRANS.SALESID, 
	SALESLINE.SEMLINENUM, 
	CUSTINVOICETRANS.ITEMID, 
	INVENTTABLE.NAMEALIAS, 
	CUSTINVOICETRANS.NAME, 
	CASE WHEN rtrim(sn.INVENTSERIALID) != '' THEN '1' ELSE CustInvoiceTrans.QTY END AS QTY, 
	--CustInvoiceTrans.QTY,
	--INVENTDIM.INVENTSERIALID,
	CASE --WHEN INVENTTABLE.NAMEALIAS = '30044' then 0
	-- mw 06172013 added sbe to sbe100
							WHEN INVENTTABLE.NAMEALIAS in ( '60121' , '93080' , '40005' , '10476' , '60157')  then 0
							WHEN INVENTTABLE.NAMEALIAS = '60006' then 0
								WHEN INVENTTABLE.NAMEALIAS = '60020' then '995'
	WHEN SALESLINE.SEMQMSLIST = '.01' then 0
						  ELSE SALESLINE.SEMQMSLIST END as SEMQMSLIST, 
	SALESTABLE.CUSTACCOUNT, 
	REPLACE(SALESTABLE.PURCHORDERFORMNUM, ',', '-') 
						  AS PO_NUM, 
	SALESTABLE.SEMENDCUST, 
	SALESTABLE.SEMPOSTINGORDERTYPE, 
	sn.INVENTSERIALID,
	SALESTABLE.CURRENCYCODE, 
	CUSTTABLE.NAME AS EndCus, 
	--SPL.Sbe AS IsSBE, 
	--CUSTINVOICETRANS.SALESID + '_' + CONVERT(varchar(5), SALESLINE.SEMLINENUM) + '_' + SUBSTRING(CONVERT(varchar(50), rand(), 0), 3, 5) AS INTEGRATION_ID, 
	-- integration is recid + recid of ser if serialized line
	CUSTINVOICETRANS.RECID + isnull(sn.RecId,'')  AS INTEGRATION_ID,
	SALESLINE.SemSbeParent,
	SALESLINE.SemSbeComp, -- Bundle Indicator
	CASE WHEN rtrim(sn.INVENTSERIALID) != ''		-- if its an bundled switch, then set this flag, will need to import serial number if sbe
			THEN 'S'						-- i am a serialized switch in a bundle
			ELSE 'C' END AS BomSubType
	
	--InventTable.SerialNumGroupId
	--CUSTTABLE.SEMCUSTSIEBELID,
	--***
/*  	CustPackingSlipJour.DELIVERYDATE as SHIP_DATE, 
	CustPackingSlipJour.DELIVERYDATE  as WARRANTY_START,
						  -- The way the support is suppose to work is that the initial order is for 13 months, but subsequent orders should be for 12 months.  Tom V.
						CASE WHEN SALESTABLE.SEMPOSTINGORDERTYPE = 'A' THEN DATEADD(month, 12, CustPackingSlipJour.DELIVERYDATE)
						ELSE DATEADD(month, 13, CustPackingSlipJour.DELIVERYDATE)  END AS WARRANTY_END */

FROM         
					SVLCORPAXDB1.PROD.dbo.CUSTINVOICETRANS  INNER JOIN
--INVENTTRANS  ON CUSTINVOICETRANS.INVENTTRANSID = INVENTTRANS.INVENTTRANSID
--AND CUSTINVOICETRANS.INVOICEID = INVENTTRANS.INVOICEID-- otherwwise there could be dupes
-- INNER JOIN
                   --   INVENTDIM  ON INVENTTRANS.INVENTDIMID = INVENTDIM.INVENTDIMID INNER JOIN
                      SVLCORPAXDB1.PROD.dbo.SALESLINE  ON CUSTINVOICETRANS.SALESID = SALESLINE.SALESID AND CUSTINVOICETRANS.SEMLINENUM = SALESLINE.SEMLINENUM INNER JOIN
                      SVLCORPAXDB1.PROD.dbo.INVENTTABLE  ON CUSTINVOICETRANS.ITEMID = INVENTTABLE.ITEMID INNER JOIN
                      SVLCORPAXDB1.PROD.dbo.SALESTABLE  ON CUSTINVOICETRANS.SALESID = SALESTABLE.SALESID 
														AND salestable.salestype= '3' INNER JOIN
                      SVLCORPAXDB1.PROD.dbo.CUSTTABLE  ON SALESTABLE.SEMENDCUST = CUSTTABLE.ACCOUNTNUM inner join
					  SFDC_ASSET_SHIPDATE sd on CUSTINVOICETRANS.SalesId = sd.SalesOrder left outer join
					  SFDC_ASSET_SERIALNUM sn on CUSTINVOICETRANS.InvoiceId = sn.INVOICEID AND CUSTINVOICETRANS.INVENTTRANSID = sn.INVENTTRANSID inner join
					  SFDC_PRODUCTS p on INVENTTABLE.NAMEALIAS = p.SKU collate database_default
										and p.SupportItem = 'Yes' --support Items only!
       WHERE     SALESTABLE.SEMPOSTINGORDERTYPE IN ('A' , 'I', 'M', 'GP' ,'MS', 'P' , 'N' )
AND CUSTINVOICETRANS.INVOICEID NOT LIKE 'CM-%'
 AND CUSTINVOICETRANS.invoicedate >= convert(CHAR(10),'07-17-2015', 101)

