


CREATE View [dbo].[V_AX_BACKLOG_SKYRENT]
--MW 01162017  Requested Tableau view for JR
as
 
 SELECT 
 SALESTABLE.CREATEDDATETIME
 , SALESTABLE.SALESID
 , SALESTABLE.PURCHORDERFORMNUM
 , SALESTABLE.SEMENDCUST
 , SALESLINE.NAME
 , SALESLINE.SALESSTATUS
 , SALESLINE.QTYORDERED
 , SALESLINE.ITEMID
 , SALESLINE.CURRENCYCODE
 , SALESLINE.SHIPPINGDATECONFIRMED
 , SALESLINE.LINEAMOUNT
 , SALESLINE.REMAINSALESPHYSICAL
 , SALESTABLE.SEMPOSTINGORDERTYPE
 , SALESLINE.SHIPPINGDATEREQUESTED
 , SALESTABLE.SEMRESELLERNAME
 , SALESTABLE.EMAIL,
  SALESTABLE.INVOICEACCOUNT,
  c.NAME as EndCustomerName,
  INVENTTABLE.ITEMNAME as ItemName,
  i.InventLocationId as Warehouse 
 FROM   [SVLCORPAXDB1].PROD.dbo.SALESLINE SALESLINE
  INNER JOIN [SVLCORPAXDB1].PROD.dbo.SALESTABLE SALESTABLE
   ON SALESLINE.SALESID=SALESTABLE.SALESID
  JOIN [SVLCORPAXDB1].[PROD].dbo.INVENTTABLE
  on INVENTTABLE.ITEMID = SALESLINE.ITEMID inner join
  SVLCORPAXDB1.PROD.dbo.CustTable c on  SALESTABLE.semendcust = c.AccountNum inner join
  SVLCORPAXDB1.PROD.dbo.INVENTDIM i on SalesLIne.InventDimId = i.InventDimId
   where
 SALESLINE.SALESSTATUS = 1 and SALESLINE.REMAINSALESPHYSICAL <> 0
AND
(SALESTABLE.SEMPOSTINGORDERTYPE like 'SKY-RENT%' OR
 SALESTABLE.SEMPOSTINGORDERTYPE like 'SKY-SALE%' OR
 SALESTABLE.SEMPOSTINGORDERTYPE like 'CLD-%')
AND
i.InventLocationId in ('NY','FG')
 --ORDER BY SALESLINE.NAME, SALESLINE.SHIPPINGDATECONFIRMED, SALESTABLE.SALESID




