
CREATE view [dbo].[V_AX_CUST_ADDRESS] as
-- MW 09292015 lookup for AX addresses
SELECT      a.CREATEDDATETIME, 
			a.ACCOUNTNUM As CustomerId, 
			ADDRESS.STREET,
			ADDRESS.CITY, 
			ADDRESS.STATE, 
			ADDRESS.ZIPCODE, 
			ADDRESS.CountryRegionId,
			a.SalesPoolId as AxCode,
		    ADDRESS.Phone,
			t.Theatre,
			row_number() over (partition by a.ACCOUNTNUM order by ADDRESS.RECID desc) rn
FROM        
                     SVLCORPAXDB1.PROD.dbo.CUSTTABLE AS a      INNER JOIN     
					 SVLCORPAXDB1.PROD.dbo.DIRPARTYTABLE  ON a.PARTYID = DIRPARTYTABLE.PARTYID INNER JOIN
					 SVLCORPAXDB1.PROD.dbo.DIRPARTYADDRESSRELATIONSHIP   ON DIRPARTYTABLE.PARTYID = DIRPARTYADDRESSRELATIONSHIP.PARTYID INNER JOIN
					 SVLCORPAXDB1.PROD.dbo.DIRPARTYADDRESSRELATIONSHI1066   ON 
						DIRPARTYADDRESSRELATIONSHIP.RECID = DIRPARTYADDRESSRELATIONSHI1066.PARTYADDRESSRELATIONSHIPRECID AND refcompanyid = 'glo' INNER JOIN
					 SVLCORPAXDB1.PROD.dbo.ADDRESS   ON DIRPARTYADDRESSRELATIONSHI1066.ADDRESSRECID = ADDRESS.RECID  left outer join
					 SFDC_TERRITORY t on a.SalesPoolId = t.AxCode collate database_default
WHERE       
 ADDRESS.type = 1 
