 


Create View V_HANA_CUSTOMERMASTER_SLIM as
-- MW 12022020 Cust Master - Slim
 select 
CST_SALESEMP as [Account Manager Key],
END_SLSEMP as [Account Manager Name],
CST_YSFBLUEID as [Blue SFDC ID],
BOSS_AU as [BOSS AU ID],
BOSS_EU as [BOSS EU ID],
BOSS_US as [BOSS US ID],
E_YCHNHR1 as [Channel Hierarchy Level 1],
E_YCHNHR2 as [Channel Hierarchy Level 2],
CST_YCHNTYPE as [Channel Type Key],
CST_YCHNTYPE___TXTMD as [Channel Type Name],
CST_0CITY as [City],
CST_YCOMPNYSZ___TXTLG as [Company Size Name],
COSTG_DE as [CostGuard DE ID],
COSTG_UK as [CostGuard UK ID],
COSTG_US as [CostGuard US ID],
CST_0COUNTRY as [Country Key],
CST_0COUNTRY___TXTSH as [Country Name],
CST_0ACCNT_GRP___TXTMD as [Customer Account Group Name],
CUST_L1 as [Customer Hierarchy Level 1 Key],
CUST_L1TXT as [Customer Hierarchy Level 1 Name],
CUST_L2 as [Customer Hierarchy Level 2 Key],
CUST_L2TXT as [Customer Hierarchy Level 2 Name],
CST_NAME as [Customer Name],
--CST_0NAME2 as [Customer Name 1],
CST_CUSTOMER as [Customer Number],
DISTRI_RECORD as [Distributor of Record Key],
DISTTR_TXT as [Distributor of Record Name],
CST_0DBDUNS_NUM as [DUNS Number],
END_YREPREGN as [End Customer Reporting Region (M)],
SIC_YMTLHLIND as [High Level Vertical],
KNA1_Count as [KNA1 Count],
CST_YMNGDSYST as [Managed System],
CST_YMNGSYSID as [Managed System ID],
--DEL_INDICATOR as [Marked for Deletion],
CST_YMTUSRGRP as [Mitel User Group],
CST_YSFORNGID as [Orange SFDC ID],
CST_YPTNRLVL as [Partner Level Key],
CST_YPTNRLVL___TXTSH as [Partner Level Name],
CST_POSTAL_CODE as [Postal Code / ZIP],
CST_0POSTAL_CD as [Postal Code / ZIP (Short)],
CUST_REG as [Region],
RESEL_CHN_TYPE as [Reseller Partner Channel Type Key],
RESEL_CHN_TYPTEXT as [Reseller Partner Channel Type Name],
CUST_RESELRPRTNR as [Reseller Partner Key],
RESEL_NAME as [Reseller Partner Name],
CUST_SAREA as [Sales Area],
--CUST_0SALESORG as [Sales Organization Key],
--CUST_0SALESORG___TXTLG as [Sales Organization Name],
SIC_YSICCODE1 as [SIC Code 1 Key],
SIC_YSICCODE1_DES as [SIC Code 1 Name],
SIC_YSICCODE2 as [SIC Code 2 Key],
SIC_YSICCODE2_DES as [SIC Code 2 Name],
SIC_YSICCODE3 as [SIC Code 3 Key],
SIC_YSICCODE3_DES as [SIC Code 3 Name],
CST_YSICCODE as [SIC Code 4 Key],
SIC_YSICCODE4_DES as [SIC Code 4 Name],
CST_0REGION as [State /Province Key],
CST_0REGION___TXTSH as [State /Province Text],
CST_0STREET as [Street Address],
CUST_SUBR as [Sub Region],
CST_YSALESOFF as [Sub Territory Key],
CST_YSALESOFF___TXTMD as [Sub Territory Name],
CUST_YSTHEATRE as [Sub Theatre],
CUST_TERRTRY as [Territory],
CUST_THEATR as [Theatre],
SIC_YMTLINDUS as [Vertical]
	FROM OPENQUERY (BWP,  'SELECT  * FROM    "ZMITEL_BOOKINGS.TABLEAU_VIEWS::YR_MD_CV_CUST"' )   
  





