




 


 CREATE view [dbo].[V_HANA_BILL_AGR] as 
 -- MW 10082020 For Export To Tableau
 
select 
	 YMTD as [Month To Date (MTD)],
YQTD as [Quarter To Date (QTD)],
YYTD as [Year To Date (YTD)],
ZENDCUSTNM as [End Customer Name],
YBILL_QUANTITY as [Billings Quantity],
YBILL_TOTVAL_INV as [Total Billings (Doc)],
YBILL_TOTVAL_INVU as [Total Billings (USD)],
YDOFMN as [Date - Day of Month],
YDOFQT as [Date - Day of Quarter],
YDOFYEAR as [Date - Day of Year],
YMOFQT as [Date - Month of Quarter],
YBILL_MATQUAN as [Billings Quantity (Calc)],
YMTLINDUS as [End Customer Vertical],
YMTLHLIND as [End Customer High Level Vertical],
"0BASE_UOM" as [Base Unit of Measure],
cast ("0CALDAY" as datetime) as [Date - Day],
"0CALMONTH" as [Date - Year / Month],
"0CALQUARTER" as [Date - Year / Quarter],
"0CALYEAR" as [Date - Year],
"0DOC_CURRCY" as [SD Document Currency],
C_YEUCUSTC as [End Customer City],
C_YEUCUSTLN as [End Customer Location Name],
C_YEUCUSTPC as [End Customer Postal Code],
C_YEUCUSTS as [End Customer Street],
SOLD_YREGN as [Sold to Region],
SOLD_YSAREA as [Sold to Sales Area],
SOLD_YSTHEATRE as [Sold to Sub-Theatre],
SOLD_YSUBREGN as [Sold to Sub-Region],
SOLD_YTERITRY as [Sold to Territory],
SOLD_YTHEATRE as [Sold to Theatre],
SOLD_SALESEMPLY as [Sold to Account Manager Key],
CAL_QUARTERWEEK as [Date - Quarter],
CAL_WEEK as [Date - Week],
CAL_YEARQTRWEEK as [Date - Y/Q/W],
END_L1 as [End Customer Hierarchy Level 1 Key],
SOLD_COUNTRY as [Sold to Country Key],
SOLD_REGION as [Sold to State],
SOLD_YPTNRLVL as [Sold to Partner Level Key],
SOLD_YCHNTYPE as [Sold to Channel Type],
SOLD_L1 as [Sold to Hierarchy Level 1 Key],
"MAT_KONDM" as [Material Price Group Key (T)],
"PRICE_GRP" as [Customer Price Group Key (T)],
YSICCODE1 as [End Customer SIC Code 1 Key],
YSICCODE2 as [End Customer SIC Code 2 Key],
YSICCODE3 as [End Customer SIC Code 3 Key],
YSICCODE as [End Customer SIC Code 4 Key],
YRESELL as [Reseller Partner Key],
"0PROD_HIER" as [Product Hierarchy Key],
"0SOLD_TO" as [Sold to Key],
C_YEUCUST as [End Customer Number],
"0SALESEMPLY" as [Sales Employee Key],
YCUSTY4 as [Y4 Selling Agent Key],
MAT_PROD_HIER as [Material Product Hierarchy Key (M)],
C_YEUCUSTCN as [End Customer Country Key],
C_YEUCUSTR as [End Customer State],
"0SALESORG" as [Sales Organization Key],
YREGN as [End Customer Region],
YSAREA as [End Customer Sales Area],
YSTHEATRE as [End Customer Sub-Theatre],
YSUBREGN as [End Customer Sub-Region],
YTERITRY as [End Customer Territory],
YTHEATRE as [End Customer Theatre],
MG_MAT_TXTS as [Material Price Group Name (T)],
PG_TXTS as [Customer Price Group Name (T)],
SO_TXTLG as [Sales Organization Name],
SIC1_TXTL as [End Customer SIC Code 1 Name],
SIC2_TXTL as [End Customer SIC Code 2 Name],
SIC3_TXTL as [End Customer SIC Code 3 Name],
SIC4_TXTL as [End Customer SIC Code 4 Name],
RSL_TXTL as [Reseller Partner Name],
SDC_TXTLG as [Sales Document Category Name],
--YPRDHRFLT_T as [Product Hierarchy Name],
SOLDTO_PARTY as [Sold to Name],
SOLDTO_CNTRY as [Sold to Country Name],
--SOLD_REGION_TX as [Sold to State],
SOLD_YPTRNLEVL_T as [Sold to Partner Level Name],
SOLD_L1_TXT as [Sold to Hierarchy Level 1 Name],
SOLD_ACCNT_MGR as [Sold to Account Manager Name],
END_ACNT_GRP_T as [End Customer Account Group Name],
END_CNTRY_T as [End Customer Country Name],
--END_REGN_T as [End Customer State],
END_YCHNTYP_T as [End Customer Channel Type Name],
END_LVL1TXT as [End Customer Hierarchy Level 1 Name],
SE_TXTMD as [Sales Employee Name],
Y4SELAGT_TXTMD as [Y4 Selling Agent Name],
MAT_PROD_HIE as [Material Product Hierarchy Name (M)],
YPRDHRL1__T1 as [Product Hierarchy Level 1 Name],
YPRDHRL2__T2 as [Product Hierarchy Level 2 Name],
YPRDHRL3__T3 as [Product Hierarchy Level 3 Name],
YPRDHRL4__T4 as [Product Hierarchy Level 4 Name],
YPRDHRL5__T5 as [Product Hierarchy Level 5 Name],
YPRDHRL6__T6 as [Product Hierarchy Level 6 Name],
YPRDHRL7__T7 as [Product Hierarchy Level 7 Name],
YPRDHRL8__T8 as [Product Hierarchy Level 8 Name],
YPRDHRL9__T9 as [Product Hierarchy Level 9 Name]

FROM OPENQUERY (BWP,  
	'SELECT    
*
	FROM    "_SYS_BIC"."ZMITEL_BOOKINGS.TABLEAU_VIEWS/YR_SD_CV_AGR_BL01"
--where "0CALYEAR" =  2020  '
	 )
 
 
