

 


  CREATE view [dbo].[V_HANA_CUSTOMERMASTER] as 
 -- MW 08062020 For Export To Tableau
 
 select  
		 
 CST_SALESEMP as [Account Manager Key]
,CUST_0SALESORG as [Sales Organization Key]
,CUST_0SALESORG___TXTLG as [Sales Organization Name]
,CUST_0PRICE_GRP as [Price Group Key]
,CUST_0PMNTTRMS as [Payment Terms Key]
,CUST_0CUST_GROUP as [Customer Group Key]
,CUST_0CUST_GROUP___TXTSH as [Customer Group Name]
,CUST_0INCOTERMS as [Incoterms 1]
,CUST_0INCOTERMS2 as [Incoterms 2]
,CUST_0PMNTTRMS___TXTMD as [Payment Terms Name]
,CUST_0PRICE_GRP___TXTSH as [Price Group Name]
,SIC_YMTLHLIND as [High Level Vertical]
,SIC_YMTLINDUS as [Vertical]
,SIC_YSICCODE1 as [SIC Code 1 Key]
,SIC_YSICCODE2_DES as [SIC Code 2 Name]
,SIC_YSICCODE2 as [SIC Code 2 Key]
,SIC_YSICCODE3_DES as [SIC Code 3 Name]
,SIC_YSICCODE3 as [SIC Code 3 Key]
,SIC_YSICCODE1_DES as [SIC Code 1 Name]
,SIC_YSICCODE4_DES as [SIC Code 4 Name]
,CST_NAME as [Customer Name]
,CST_0NAME2 as [Customer Name 2]
,CST_0NAME3 as [Customer Name 3]
,CST_0STREET as [Street Address]
,CST_0CITY as [City]
,CST_0COUNTRY as [Country Key]
,CST_0CREATEDON as [Created On]
,CST_0PHONE as [Telephone Number]
--,CST_0REGION as [State]
,CST_0REGION___TXTSH as [State ]
,CST_0COUNTRY___TXTSH as [Country Name]
,CST_0DBDUNS_NUM as [DUNS Number]
,CST_0ACCNT_GRP as [Customer Account Group Key]
,CST_0ACCNT_GRP___TXTMD as [Customer Account Group Name]
,CST_YCHNTYPE as [Channel Type Key]
,CST_YCHNTYPE___TXTMD as [Channel Type Name]
,CST_YCOMPNYSZ as [Company Size Key]
,CST_YMNGDSYST as [Managed System]
,CST_YMNGSYSID as [Managed System ID]
,CST_YSFBLUEID as [Blue SFDC ID]
,CST_YSFORNGID as [Orange SFDC ID]
,CST_YSICCODE as [SIC Code 4 Key]
,CST_YMTUSRGRP as [Mitel User Group]
,CST_YPTNRLVL as [Partner Level Key]
,CST_YPTNRLVL___TXTSH as [Partner Level Name]
,CST_YSALESOFF as [Sub Territory Key]
,CST_YSALESOFF___TXTMD as [Sub Territory Name]
,CST_ZKATR3 as [Managed By Key]
,CST_ZKATR3___TXTSH as [Managed By Name]
,CST_NAME4 as [Customer Name 4]
,CST_YCOMPNYSZ___TXTLG as [Company Size Name]
,CST_POSTAL_CODE as [Postal Code ]
,CST_0POSTAL_CD as [Postal Code CD]
,CST_0CREATEDBY as [Created By]
,COSTG_UK as [CostGuard UK ID]
,COSTG_US as [CostGuard US ID]
,COSTG_DE as [CostGuard DE ID]
,BOSS_EU as [BOSS EU ID]
,BOSS_AU as [BOSS AU ID]
,BOSS_US as [BOSS US ID]
,YCUST_CBLK as [Credit Block]
,DEL_INDICATOR as [Marked for Deletion]
,CUST_RESELRPRTNR as [Reseller Partner Key]
,[INDEX] as [Index]
,RESEL_CHN_TYPE as [Reseller Partner Channel Type Key]
,RESEL_CHN_TYPTEXT as [Reseller Partner Channel Type Name]
,DISTRI_RECORD as [Distributor of Record Key]
,YCUST_BL as [Billing Block Key]
,YCUST_ORD as [Order Block Key]
,CUST_0PRICE_LIST as [Price List Key]
,CST_CUSTOMER as [Customer Number]
,KNVV_COUNT as [KNVV Count]
,KNA1_Count as [KNA1 Count]
,CUST_REG as [Region]
,CUST_SAREA as [Sales Area]
,CUST_YSTHEATRE as [Sub Theatre]
,CUST_SUBR as [Sub Region]
,CUST_TERRTRY as [Territory]
,CUST_THEATR as [Theatre]
,E_YCHNHR1 as [Channel Hierarchy Level 1]
,E_YCHNHR2 as [Channel Hierarchy Level 2]
,CUST_L1 as [Customer Hierarchy Level 1 Key]
,CUST_L2 as [Customer Hierarchy Level 2 Key]
,CUST_L3 as [Customer Hierarchy Level 3 Key]
,CUST_L1TXT as [Customer Hierarchy Level 1 Name]
,CUST_L2TXT as [Customer Hierarchy Level 2 Name]
,CUST_L3TXT as [Customer Hierarchy Level 3 Name]
,END_SLSEMP as [Account Manager Name]
--,END_YREPREGN as [End Customer Reporting Region (M)]
,BB_TXT as [Billing Block Name]
,PL_TXTSH as [Price List Name]
,ORD_TXT as [Order Block Name]
,RESEL_NAME as [Reseller Partner Name]
,DISTTR_TXT as [Distributor of Record Name]


FROM OPENQUERY (BWP,  
	'SELECT   
*
	FROM    "ZMITEL_BOOKINGS.TABLEAU_VIEWS::YR_MD_CV_CUSTOMERMASTER" 
  '
	 )
 

 
