
 


Create View [dbo].V_HANA_REVENUE as
-- MW 12282020 HANA Revenue
 select 
 
 "0BILL_TYPE" as [Billing Type Key],
--"0BILL_TYPE_T" as [Billing Type Name],
"0BILLTOPRTY___T" as [Bill-to Party Name],
"0BILLTOPRTY" as [Bill-to Party Number],
"YFISYEAR" as [Calendar Year],
"YFISPER" as [Calendar Year Period],
"YCY_QRTER" as [Calendar Year Quarter],
"0COMP_CODE" as [Company Code Key],
--"0COMP_CODE_T" as [Company Code Name],
"YCON_TYPE" as [Condition Type Key],
--"YCON_TYPE_T" as [Condition Type Name],
"YCTR_NUM" as [Contract Number],
"0COSTCENTER" as [Cost Center Key],
"0COSTCENTER___T" as [Cost Center Name],
"0CUST_GROUP" as [Customer Group Key],
"0CUST_GROUP___T" as [Customer Group Name],
--"0EMPLOYEE_T" as [Employee Name],
"0EMPLOYEE" as [Employee Number],
"0ACCNT_GRP" as [End Customer Account Group Key],
--"0ACCNT_GRP_T" as [End Customer Account Group Name],
"YCHNHIER1" as [End Customer Channel Hierarchy Level 1],
"YCHNHIER2" as [End Customer Channel Hierarchy Level 2],
"YCHNTYPE" as [End Customer Channel Type Key],
--"YCHNTYPE_T" as [End Customer Channel Type Name],
--"YEUCUSTC" as [End Customer City],
--"YEUCUSTCN" as [End Customer Country],
"YCUSHRL1" as [End Customer Hierarchy Level 1 Key],
--"YCUSHRL1_T" as [End Customer Hierarchy Level 1 Name],
"YCUSHRL2" as [End Customer Hierarchy Level 2 Key],
--"YCUSHRL2_T" as [End Customer Hierarchy Level 2 Name],
"YCUSHRL3" as [End Customer Hierarchy Level 3 Key],
--"YCUSHRL3_T" as [End Customer Hierarchy Level 3 Name],
"ZENDCUSTNM" as [End Customer Name],
"C_YEUCUST" as [End Customer Number],
--"YEUCUSTPC" as [End Customer Postal Code],
--"0LOGSYS" as [End Customer Source],
--"YEUCUSTR" as [End Customer State / Province],
"FREIGHT" as [Freight],
"GROSS_REV" as [Gross Revenue],
"YUEPOS" as [Higher-level Item],
"0COORDER" as [Internal Order],
"0BILL_DATE" as [Create Date (Invoice Date)],
"0BILL_ITEM" as [Invoice Item],
"YEPOS_NUM" as [Invoice Number],
"0ITEM_CATEG" as [Item Category Key],
"0ITEM_CATEG___T" as [Item Category Name],
"0MATL_GRP_1" as [Material Group 1 Key],
"0MATL_GRP_1___T" as [Material Group 1 Name],
"0MATL_GRP_2" as [Material Group 2 Key],
"0MATL_GRP_2___T" as [Material Group 2 Name],
"0MATL_GRP_4" as [Material Listing Group Key],
"0MATL_GRP_4___T" as [Material Listing Group Name],
--"0MATERIAL_T" as [Material Name],
"0MATERIAL" as [Material Number],
"YMPG" as [Material Pricing Group Key],
--"YMPG_T" as [Material Pricing Group Name],
"0MATL_TYPE" as [Material Type Key],
--"0MATL_TYPE_T" as [Material Type Name],
"NET_REV" as [Net Revenues],
"NON_STD_DISC" as [Non-std Discounts],
"0NOTIFICATN" as [Notification],
"0CUST_GRP2" as [Operator Code Key],
--"0CUST_GRP2_T" as [Operator Code Name],
"0ORD_REASON" as [Order Reason Key],
--"ORD_REASON_T" as [Order Reason Name],
"YBELNR" as [PA Doc Item Number],
"YPERIOD" as [Period],
"0PLANT" as [Plant Key],
--"0PLANT_T" as [Plant Name],
"0PROD_HIER" as [Product Hierarchy Key],
"YPRDH_L1_T" as [Product Hierarchy Level 1 Name],
"YPRDH_L2_T" as [Product Hierarchy Level 2 Name],
"YPRDH_L3_T" as [Product Hierarchy Level 3 Name],
"YPRDH_L4_T" as [Product Hierarchy Level 4 Name],
"YPRDH_L5_T" as [Product Hierarchy Level 5 Name],
"YPRDH_L6_T" as [Product Hierarchy Level 6 Name],
"YPRDH_L7_T" as [Product Hierarchy Level 7 Name],
"YPRDH_L8_T" as [Product Hierarchy Level 8 Name],
"YPRDH_L9_T" as [Product Hierarchy Level 9 Name],
--"0PROD_HIER_T" as [Product Hierarchy Name],
"YPCTR_L1_T" as [Profit Center Hierarchy Level 1 Name],
"YPCTR_L2_T" as [Profit Center Hierarchy Level 2 Name],
"YPCTR_L3_T" as [Profit Center Hierarchy Level 3 Name],
"YPCTR_L4_T" as [Profit Center Hierarchy Level 4 Name],
"YPCTR_L5_T" as [Profit Center Hierarchy Level 5 Name],
"YPCTR_L6_T" as [Profit Center Hierarchy Level 6 Name],
"YPCTR_L7_T" as [Profit Center Hierarchy Level 7 Name],
"0PROFIT_CTR" as [Profit Center Key],
"0PROFIT_CTR___T" as [Profit Center Name],
"YSLS_QTY" as [Quantity],
"YQUARTER" as [Quarter],
"0REC_TYPE" as [Record Type Key],
--"0REC_TYPE_T" as [Record Type Name],
"0REFER_DOC" as [Reference Document],
"0DOC_NUMBER" as [Sales Order],
"0S_ORD_ITEM" as [Sales Order Item],
"0DOC_TYPE" as [Sales Order Type Key],
--"0DOC_TYPE_T" as [Sales Order Type Name],
"0SALESORG" as [Sales Organization Key],
--"0SALESORG_T" as [Sales Organization Name],
"VOL_REBATE" as [Sales Rebates],
--"0SHIP_TO_T" as [Ship-to Party Name],
"0SHIP_TO" as [Ship-to Party Number],
"S_YCHNHIER1" as [Sold-to Party Channel Hierarchy Level 1],
"S_YCHNHIER2" as [Sold-to Party Channel Hierarchy Level 2],
"S_YCHNTYPE" as [Sold-to Party Channel Type Key],
"S_YCHNTYPE_T" as [Sold-to Party Channel Type Name],
"S_L1" as [Sold-to Party Hierarchy Level 1 Key],
"S_L1_T" as [Sold-to Party Hierarchy Level 1 Name],
"S_L2" as [Sold-to Party Hierarchy Level 2 Key],
"S_L2_T" as [Sold-to Party Hierarchy Level 2 Name],
"S_L3" as [Sold-to Party Hierarchy Level 3 Key],
"S_L3_T" as [Sold-to Party Hierarchy Level 3 Name],
--"0CUSTOMER_T" as [Sold-to Party Name],
"0CUSTOMER" as [Sold-to Party Number],
"STD_COST" as [Std. Cost],
"STD_DISC" as [Std. Discounts]
 FROM OPENQUERY (BWP,  'SELECT  top 10 * FROM    "ZMITEL_BOOKINGS.TABLEAU_VIEWS::YR_COPA_01_IP"' )   
  





