
-- select * FROM [dbo].[V_SWA_RENEWALOPP] WHERE [Reporting Year Month(YYYYMM)] = '202007'

CREATE VIEW  [dbo].[V_SWA_RENEWALOPP]
AS 
SELECT PRODUCT_FAMILY AS 'Product Family'
	,EXPIREDYEARMONTH AS 'Expired Year Month(YYYYMM)'
	,REPORTING_MONTH AS 'Reporting Year Month(YYYYMM)'
	--,LEFT(EXPIREDYEARMONTH, 4) + '-' + RIGHT(EXPIREDYEARMONTH, 2) + '-01'
	--,LEFT(REPORTING_MONTH, 4) + '-' + RIGHT(REPORTING_MONTH, 2) + '-01'
	,CAST(LEFT(EXPIREDYEARMONTH, 4) + '-' + RIGHT(EXPIREDYEARMONTH, 2) + '-01' AS DATE) AS 'Expired Year Month'
	,CAST(LEFT(REPORTING_MONTH, 4) + '-' + RIGHT(REPORTING_MONTH, 2) + '-01' AS DATE) AS 'Reporting Year Month'
	,SUM(COALESCE(EXPIRED_USERS, 0)) AS 'Expired Users'
	,SUM(COALESCE(ACTIVE_USERS, 0)) AS 'Active Users'
	,MAX(SUM(COALESCE(ACTIVE_USERS, 0))) OVER (
		PARTITION BY PRODUCT_FAMILY ORDER BY EXPIREDYEARMONTH
			,REPORTING_MONTH ROWS BETWEEN 12 PRECEDING
				AND 1 PRECEDING
		) AS 'Renewal Opportunity (Users)'
	,MAX(SUM(COALESCE(ACTIVE_USERS, 0))) OVER (
		PARTITION BY PRODUCT_FAMILY ORDER BY EXPIREDYEARMONTH
			,REPORTING_MONTH ROWS BETWEEN 12 PRECEDING
				AND 1 PRECEDING
		) - SUM(COALESCE(EXPIRED_USERS, 0)) AS 'Renewed Users'
	,(
		(
			MAX(SUM(COALESCE(ACTIVE_USERS, 0))) OVER (
				PARTITION BY PRODUCT_FAMILY ORDER BY EXPIREDYEARMONTH
					,REPORTING_MONTH ROWS BETWEEN 12 PRECEDING
						AND 1 PRECEDING
				) - SUM(COALESCE(EXPIRED_USERS, 0))
			) * 1.0
		) / (
		NULLIF(MAX(SUM(COALESCE(ACTIVE_USERS, 0))) OVER (
				PARTITION BY PRODUCT_FAMILY ORDER BY EXPIREDYEARMONTH
					,REPORTING_MONTH ROWS BETWEEN 12 PRECEDING
						AND 1 PRECEDING
				), 0) * 1.0
		) AS 'Renewal Rate'
--SELECT * 
FROM OPENQUERY(BWP, 'SELECT PRODUCT_FAMILY
							, REPORTING_MONTH
							--, EXPIREDYEARMONTH
							, CASE WHEN LENGTH(EXPIREDYEARMONTH) = 1 AND EXPIREDYEARMONTH IN(''0'', ''1'', ''2'', ''3'', ''4'', ''5'', ''6'', ''7'', ''8'', ''9'') 
									THEN ''190001''
									WHEN LENGTH(EXPIREDYEARMONTH) = 4 
									THEN CONCAT(EXPIREDYEARMONTH, ''01'')
									ELSE EXPIREDYEARMONTH
									END AS EXPIREDYEARMONTH
							, EXPIRED_USERS
							, ACTIVE_USERS
					 FROM    "ZSWA.SWA_CONSOLIDATED::ZSWA_CV_CONSOL_01" 
					 WHERE   (CASE WHEN LENGTH(EXPIREDYEARMONTH) = 1 AND EXPIREDYEARMONTH IN(''0'', ''1'', ''2'', ''3'', ''4'', ''5'', ''6'', ''7'', ''8'', ''9'') 
									THEN ''190001''
									WHEN LENGTH(EXPIREDYEARMONTH) = 4 
									THEN CONCAT(EXPIREDYEARMONTH, ''01'')
									ELSE EXPIREDYEARMONTH
									END) >= ''200708''
						-- LENGTH(EXPIREDYEARMONTH) = 6 AND EXPIREDYEARMONTH > ''200708''
						AND REPORTING_MONTH > ''201901''
	   ')
GROUP BY PRODUCT_FAMILY
	,EXPIREDYEARMONTH
	,REPORTING_MONTH
