


 
  CREATE View [dbo].[V_TABLEAU_E2O_POS] as 
-- MW 01242019  Tabby view for E2O POS	
 select --top 100
[/BIC/YSO_TID] as [Transaction ID],
[RECORDMODE] as [BW Delta Process: Record Mode],
[REGION] as [Region (State, Province, County)],
[/BIC/YSO_DISTR] as [Distributor_DISTR],
[/BIC/YSALESOFF] as [Sub-Territory],
[/BIC/YSORSTATE] as [Roll Up State],
[/BIC/YSO_RCONT] as [Rollup Country],
[COUNTRY] as [Country key],
[/BIC/YSO_RPST] as [Roll Up Postal Code],
[/BIC/YSO_FMAT] as [Final Material],
[/BIC/YSO_FRE] as [Final Reseller],
[/BIC/YSO_FEU] as [Final End User],
[/BIC/YSOCLUP] as [Unit List Price (USD)],
[/BIC/YSOORDNO] as [Distributor Sales Order Number],
[/BIC/YSOINVNO] as [Distributor Invoice Number],
[/BIC/YSOTRADT] as [Invoice Date],
[/BIC/YSO_PO] as [Reseller Purchase Order Number],
[/BIC/YSORENM] as [Reported Reseller Name],
[/BIC/YSORE_PC] as [Reported Reseller Postal Code],
[/BIC/YSORCNT] as [Reported Reseller Country],
[/BIC/YSORS_ID] as [Reported Mitel Reseller ID],
[/BIC/YSOE_CID] as [Reported End Customer ID],
[/BIC/YSOCUSNM] as [End Customer Name],
[/BIC/YSOEADD1] as [Reported End Customer Address 1],
[/BIC/YSOEADD2] as [Reported End Customer Address 2],
[/BIC/YSOEADD3] as [Reported End Customer Address 3],
[/BIC/YEUCUSTC] as [End User Customer City],
[/BIC/YSOE_CST] as [Reported End Customer State/Province],
[/BIC/YSOE_ZC] as [Reported End Customer Postal Code],
[/BIC/YSOECCNT] as [Reported End Customer Country],
[/BIC/YSOECTNM] as [End Customer Contact Name],
[/BIC/YSOEPHNO] as [End Customer Contact Phone Number],
[/BIC/YSOEMLAD] as [End Customer Contact E-Mail Address],
[/BIC/YSOEPONO] as [End Customer PO Number],
[/BIC/YSOC_TY] as [Contract Type],
[/BIC/YSOCONT] as [Contract Number],
[/BIC/YSOEOPID] as [Opportunity ID],
[/BIC/YSOSNM] as [Ship-to Name],
[/BIC/YSOSADD1] as [Ship-to Address 1],
[/BIC/YSOSADD2] as [Ship-to Address 2],
[/BIC/YSOSADD3] as [Ship-to Address 3],
[/BIC/YSOS_CTY] as [Ship-to City],
[/BIC/YSOS_STE] as [Ship-to State / Province],
[/BIC/YSOSZPCD] as [Ship-to Postal Code],
[/BIC/YSOS_CNT] as [Ship-to Country],
[/BIC/YSOMATID] as [Reported Material ID],
[/BIC/YSOM_DPT] as [Reported Material Description],
[/BIC/YSO_SR] as [Service Renewal],
[/BIC/YSO_OTY] as [Order Type],
[/BIC/YSOSPAID] as [SPA ID],
[/BIC/YSO_PID] as [Promotion ID],
[/BIC/YSORVADI] as [Distributor_VADI],
[/BIC/YSORDNM] as [Distributor Name],
[/BIC/YSOVSKU] as [Validated Material ID],
[/BIC/YSO_FSD] as [Fiscal Start Date],
[/BIC/YSO_FED] as [Reported Week Date],
[/BIC/YSO_FSW] as [Reported Week],
[/BIC/YSO_FSY] as [Fiscal Year],
[/BIC/YSO_FSM] as [Fiscal Month],
[/BIC/YSO_FSQ] as [Fiscal Quarter],
[/BIC/YSO_NRC] as [Normalized Reseller Country],
[/BIC/YSONRZIP] as [Normalized Reseller Postal Code],
[/BIC/YSOEUCTY] as [Normalized End Customer City],
[/BIC/YSOEUSTE] as [Normalized End Customer State/Province],
[/BIC/YSONEUZP] as [Normalized End Customer Postal Code],
[/BIC/YSONEUCT] as [Normalized End Customer Country],
[/BIC/YSOVEUNM] as [Validated End Customer Name],
[/BIC/YSOVEAD1] as [Validated End Customer Address 1],
[/BIC/YSOVEAD2] as [Validated End Customer Address 2],
[/BIC/YSOVEUCY] as [Validated End Customer City],
[/BIC/YSOVEUST] as [Validated End User State/Province],
[/BIC/YSOVEZIP] as [Validated End Customer Postal Code],
[/BIC/YSOVECT] as [Validated End Customer Country],
[/BIC/YSOVESPN] as [Validated End Customer SAP Number],
[/BIC/YSOVESID] as [Validated End Customer ShoreTel ID],
[/BIC/YSOEACCO] as [End User Account Owner],
[/BIC/YSOEACTH] as [End Customer Theatre],
[/BIC/YSOEACCR] as [End Customer Region],
[/BIC/YSOEUSR] as [End Customer Sales Region],
[/BIC/YSOEUT] as [End Customer Territory],
[/BIC/YSOPR] as [Partner of Record],
[/BIC/YSOSICD] as [SIC Code],
[/BIC/YSO_SICD] as [SIC Description],
[/BIC/YSOZBLID] as [Zyme End Customer Business Location ID],
[/BIC/YSOZINID] as [Zyme End Customer Incorporation ID],
[/BIC/YSOVRES] as [Reseller Validation Source],
[/BIC/YSOVRSPN] as [Validated Reseller SAP Number],
[/BIC/YSOVRNM] as [Validated Reseller Name],
[/BIC/YSOVRAD1] as [Validated Reseller Address 1],
[/BIC/YSOVRAD2] as [Validated Reseller Address 2],
[/BIC/YSOVRPC] as [Validated Reseller Postal Code],
[/BIC/YSOVRCTY] as [Validated Reseller City],
[/BIC/YSOVRSTE] as [Validated Reseller State/Province],
[/BIC/YSOVRCNT] as [Validated Reseller Country],
[/BIC/YSO_PL] as [Partner Level],
[/BIC/YSOCAM] as [Channel Account Manager],
[/BIC/YSORTH] as [Reseller Theatre],
[/BIC/YSORRG] as [Reseller Region],
[/BIC/YSORSRG] as [Reseller Sub Region],
[/BIC/YSORTTY] as [Reseller Territory],
[/BIC/YSO_RTY] as [Reseller Type],
[/BIC/YSOZRIID] as [Zyme Reseller Incorporation ID],
[/BIC/YSOVEUS] as [End Customer Validation Source],
[/BIC/YSORACID] as [Reseller SFDC Account ID],
[/BIC/YSODACID] as [Distributor SFDC Account ID],
[/BIC/YSO_LDFG] as [Zyme Load Indicator],
[/BIC/YSOLICNO] as [Software License Number],
[/BIC/YSO_DRID] as [Deal Registration ID],
[/BIC/YSOVRSID] as [Validated Reseller ShoreTel ID],
[/BIC/YSODCAM] as [Distribution Account Manager],
[/BIC/YSO_CSF] as [Cross Shipment Flag],
[/BIC/YSO_SLNO] as [Serial Number],
[/BIC/YSO_LUTP] as [Unit List Price (Doc)],
[/BIC/YSO_SUTP] as [Gross Unit Price (Doc)],
[/BIC/YSO_SEXP] as [Gross Sales Out (Doc)],
[/BIC/YSO_NBUP] as [Net Unit Price (Doc)],
[/BIC/YSO_NBEP] as [Net Sales Out (Doc)],
[/BIC/YSO_RBEP] as [Reseller Buy Price (Doc)],
[/BIC/YSO_OCCV] as [Other Credit Claim Values (Doc)],
[/BIC/YSO_TCCV] as [Total Credit Claim Value (Doc)],
[CURRENCY] as [Currency key],
[/BIC/YSOCSUP] as [Gross Unit Price (USD)],
[/BIC/YSOCSEP] as [Gross Sales Out (USD)],
[/BIC/YSOCNBUP] as [Net Unit Price (USD)],
[/BIC/YSOCRBUP] as [Reseller Buy Price (USD)],
[/BIC/YSOCNBEP] as [Net Sales Out (USD)],
[/BIC/YSOCOCCV] as [Other Credit Claim Values (USD)],
[/BIC/YSOCTCCV] as [Total Credit Claim Value (USD)],
[/BIC/YSOCCRBE] as [Calculated Reseller Buy Price (USD)],
[/BIC/YSOCRBEP] as [Calculated Reseller Buy Price (Doc)],
[/BIC/YSOCRCURR] as [Currency],
[/BIC/YSO_QUAN] as [Quantity] ,
[/BIC/YSOWHSE] as [WHSE],
--[/BIC/YSOWARSTD] as [Warranty Start Date],
--[/BIC/YSOWAREND] as [Warranty End Date],
[/BIC/YSOFRDATE] as [File Received Date]
	FROM OPENQUERY (BWP,  'SELECT * FROM   SAPBWP."/BIC/AYSOCBK012"' )   
  





