
 
CREATE View [Gainsight].[VwMRRDelta_intl] as
-- MW 10192018 View for Gainsight MRRD extraction AU-EU
SELECT 'AU' as Source
      ,'AU-'+ convert(Varchar(10),[AccountId]) as AccountId
      ,[LocationId]
      ,[OrderProjectManagerId]
      ,[OrderCreatedByPersonId]
      ,[orderedById]
      ,[OrderSalesPersonId]
      ,[Ac Team]
      ,[AccountManagerId]
      ,[MRR Category]
      ,[MRR Prev]
      ,[MRR Expected]
      ,[MRR Delta]
      ,[NRR]
      ,[CurrencyCode]
      ,[MRR Prev LC]
      ,[MRR Expected LC]
      ,[MRR Delta LC]
      ,[NRR LC]
      ,[InvoiceDay]
      ,[InvoiceMonth]
      ,[ServiceId]
      ,[ProductId]
      ,[OrderId]
      ,[OrderTypeId]
      ,[Order Date Created]
      ,[ServiceClassId]
      ,[DateSvcLiveActual]
      ,[ServiceStatusId]
      ,[BillingStage]
      ,[BookToBillDays]
      ,[Quantity]
      ,[DeltaQuantity]
      ,[QMRR]
	  , ROW_NUMBER() over (order by ServiceId) as RowN
 -- FROM [invoice].[MatVwIncrMRRNRR_EX_Current]
	FROM AU_FinanceBI.FinanceBI.[invoice].[MatVwIncrMRRNRR_EX]
	where InvoiceMonth =    dbo.UfnFirstOfMonth(getdate())
  UNION ALL
SELECT 'EU' as Source
      ,'EU-'+ convert(Varchar(10),[AccountId]) as AccountId
      ,[LocationId]
      ,[OrderProjectManagerId]
      ,[OrderCreatedByPersonId]
      ,[orderedById]
      ,[OrderSalesPersonId]
      ,[Ac Team]
      ,[AccountManagerId]
      ,[MRR Category]
      ,[MRR Prev]
      ,[MRR Expected]
      ,[MRR Delta]
      ,[NRR]
      ,[CurrencyCode]
      ,[MRR Prev LC]
      ,[MRR Expected LC]
      ,[MRR Delta LC]
      ,[NRR LC]
      ,[InvoiceDay]
      ,[InvoiceMonth]
      ,[ServiceId]
      ,[ProductId]
      ,[OrderId]
      ,[OrderTypeId]
      ,[Order Date Created]
      ,[ServiceClassId]
      ,[DateSvcLiveActual]
      ,[ServiceStatusId]
      ,[BillingStage]
      ,[BookToBillDays]
      ,[Quantity]
      ,[DeltaQuantity]
      ,[QMRR]
	  , ROW_NUMBER() over (order by ServiceId) as RowN
 -- FROM [invoice].[MatVwIncrMRRNRR_EX_Current]
	FROM EU_FinanceBI.FinanceBI.[invoice].[MatVwIncrMRRNRR_EX]
	where InvoiceMonth =    dbo.UfnFirstOfMonth(getdate())
