CREATE TABLE [support].[MiCustomerSentiment] (
    [AccountId]           VARCHAR (50)    NOT NULL,
    [AccountName]         VARCHAR (100)   NOT NULL,
    [Platform]            VARCHAR (50)    NULL,
    [AccountTeam]         VARCHAR (100)   NULL,
    [CustomerType]        VARCHAR (100)   NULL,
    [Theater]             VARCHAR (100)   NULL,
    [Region]              VARCHAR (50)    NULL,
    [Instance]            VARCHAR (100)   NULL,
    [DiscountType]        VARCHAR (50)    NULL,
    [Cust_Disc]           DECIMAL (18, 2) NULL,
    [AtRiskNow]           NUMERIC (18)    NULL,
    [ActiveMRR_Boss]      FLOAT (53)      NULL,
    [CSM]                 VARCHAR (100)   NULL,
    [AccountCreationDate] DATETIME        NOT NULL,
    [ActivationDate]      VARCHAR (50)    NULL,
    [CaseId]              VARCHAR (50)    NOT NULL,
    [CaseNumber]          VARCHAR (255)   NOT NULL,
    [CreatedDate]         DATETIME        NULL,
    [ClosedDate]          DATETIME        NULL,
    [FCR]                 INT             NULL,
    [Status]              VARCHAR (500)   NULL,
    [AtRisk]              VARCHAR (500)   NULL,
    [CaseOrigin]          VARCHAR (500)   NULL,
    [CaseOwnerRole]       VARCHAR (100)   NULL,
    [CaseOwner]           VARCHAR (500)   NULL,
    [ATEscalation]        VARCHAR (500)   NULL,
    [CaseReason]          VARCHAR (500)   NULL,
    [TransactionId]       VARCHAR (18)    NOT NULL,
    [TransactionBy]       NVARCHAR (2000) NULL,
    [TransactionEmail]    NVARCHAR (2000) NULL,
    [Transaction Date]    DATETIME        NULL,
    [MicsPositive]        DECIMAL (5, 2)  NULL,
    [MicsNegative]        DECIMAL (5, 2)  NULL,
    [MicsNeutral]         DECIMAL (5, 2)  NULL,
    [MicsMax]             DECIMAL (5, 2)  NULL,
    [MicsEmotion]         VARCHAR (20)    NULL,
    [FinalScore]          INT             NULL,
    [TransactionType]     VARCHAR (11)    NOT NULL
);

