CREATE TABLE [support].[NewSupportDataSource] (
    [CaseId]                               VARCHAR (50)  NOT NULL,
    [Status]                               VARCHAR (500) NULL,
    [CaseOwnerRole]                        VARCHAR (100) NULL,
    [CaseOwner]                            VARCHAR (500) NULL,
    [CustomerType]                         VARCHAR (50)  NULL,
    [CaseRegion]                           VARCHAR (50)  NULL,
    [CaseNumber]                           VARCHAR (255) NOT NULL,
    [CaseOrigin]                           VARCHAR (500) NULL,
    [smx_case_no_of_days]                  VARCHAR (500) NULL,
    [CaseReason]                           VARCHAR (500) NULL,
    [SubReason]                            VARCHAR (500) NULL,
    [Feature]                              VARCHAR (500) NULL,
    [SubFeature]                           VARCHAR (500) NULL,
    [ATEscalation]                         VARCHAR (500) NULL,
    [AtRiskIndicator]                      VARCHAR (500) NULL,
    [AtRisk]                               VARCHAR (500) NULL,
    [AccountID]                            VARCHAR (50)  NULL,
    [AccountName]                          VARCHAR (200) NULL,
    [CustomerPlatform]                     VARCHAR (50)  NULL,
    [Instance]                             VARCHAR (500) NULL,
    [Subject]                              VARCHAR (MAX) NULL,
    [Priority]                             VARCHAR (500) NULL,
    [RootCause]                            VARCHAR (500) NULL,
    [Resolution]                           VARCHAR (MAX) NULL,
    [RelatedIncident]                      VARCHAR (500) NULL,
    [Theater]                              VARCHAR (100) NULL,
    [RequestType]                          VARCHAR (100) NULL,
    [RequestSubType]                       VARCHAR (100) NULL,
    [RFOAvailable]                         VARCHAR (500) NULL,
    [RFORequested]                         VARCHAR (500) NULL,
    [OwnerId]                              VARCHAR (25)  NULL,
    [EngStatus]                            VARCHAR (500) NULL,
    [DateEscalated]                        DATETIME      NULL,
    [AccountTeam]                          VARCHAR (50)  NULL,
    [CaseCreatedBy]                        VARCHAR (500) NULL,
    [CaseCreatedDate]                      DATETIME      NULL,
    [CaseClosedDate]                       DATETIME      NULL,
    [CaseLastModifiedDate]                 DATETIME      NULL,
    [CaseContactVARECertified__c]          VARCHAR (5)   NULL,
    [CustomerName]                         VARCHAR (100) NULL,
    [CustomerRegion]                       VARCHAR (50)  NULL,
    [CustomerAccountTeam]                  VARCHAR (100) NULL,
    [CustomerTheater]                      VARCHAR (100) NULL,
    [CustomerCreatedDate]                  DATETIME      NULL,
    [CustomerAccountStatus]                VARCHAR (50)  NULL,
    [Type]                                 VARCHAR (50)  NULL,
    [AtRiskNow]                            NUMERIC (18)  NULL,
    [ActiveMRR_Boss]                       FLOAT (53)    NULL,
    [CaseMileStoneId]                      VARCHAR (50)  NULL,
    [CaseMileStoneCompleted]               VARCHAR (50)  NULL,
    [CaseMileStoneCompletionDate]          DATETIME      NULL,
    [CaseMilestoneCreatedDate]             DATETIME      NULL,
    [CaseMilestoneLastModifiedDate]        DATETIME      NULL,
    [MilestoneName]                        VARCHAR (500) NULL,
    [CaseMileStoneTargetDate]              DATETIME      NULL,
    [CaseMilestoneTimeRemaining]           VARCHAR (50)  NULL,
    [CaseMilestoneViolation]               VARCHAR (50)  NULL,
    [Active]                               VARCHAR (50)  NULL,
    [ContactId]                            VARCHAR (50)  NULL,
    [CaseOwnerCreatedDate]                 DATETIME      NULL,
    [Department]                           VARCHAR (500) NULL,
    [Email]                                VARCHAR (500) NULL,
    [FirstName]                            VARCHAR (500) NULL,
    [LastName]                             VARCHAR (500) NULL,
    [CaseOwnerLastModifiedDate]            DATETIME      NULL,
    [Name]                                 VARCHAR (500) NULL,
    [Title]                                VARCHAR (500) NULL,
    [Username]                             VARCHAR (500) NULL,
    [RoleName]                             VARCHAR (500) NULL,
    [AccountId]                            VARCHAR (50)  NULL,
    [CaseOwnerAccountName]                 VARCHAR (500) NULL,
    [ProfileId]                            VARCHAR (50)  NULL,
    [ProfileName]                          VARCHAR (500) NULL,
    [Phone]                                VARCHAR (50)  NULL,
    [ManagerId]                            VARCHAR (25)  NULL,
    [Extension]                            VARCHAR (25)  NULL,
    [CoachingId]                           VARCHAR (18)  NULL,
    [FinalScore]                           INT           NULL,
    [Overall_QA_Score__c]                  INT           NULL,
    [Overall_QA_Score2__c]                 INT           NULL,
    [Total_Process_Score__c]               INT           NULL,
    [Total_Product_Technical_Score__c]     INT           NULL,
    [CoachingName]                         VARCHAR (50)  NULL,
    [Team__c]                              VARCHAR (100) NULL,
    [Case_Number__c]                       VARCHAR (50)  NULL,
    [CoachingCaseOwner]                    VARCHAR (255) NULL,
    [Evaluated_By__c]                      VARCHAR (250) NULL,
    [Evaluation_Date__c]                   DATETIME      NULL,
    [Total_Communication_Score__c]         INT           NULL,
    [Total_Communication_Score2__c]        INT           NULL,
    [Total_Process_Score2__c]              INT           NULL,
    [Total_Product_Technical_Score2__c]    INT           NULL,
    [Total_Product_Score__c]               INT           NULL,
    [FinalScoreT1T2]                       INT           NULL,
    [Areas_of_Improvement__c]              VARCHAR (100) NULL,
    [Areas_of_Excellence__c]               VARCHAR (250) NULL,
    [Customer_Experience_Score__c]         INT           NULL,
    [Customer_Experience_Score1__c]        INT           NULL,
    [SurveyID]                             VARCHAR (50)  NULL,
    [SurveysCaseNumber]                    VARCHAR (50)  NULL,
    [SurveysPrimaryScore]                  INT           NULL,
    [SurveysDataCollectionName]            VARCHAR (200) NULL,
    [SurveysSource]                        VARCHAR (50)  NULL,
    [RepEffectiveness]                     VARCHAR (255) NULL,
    [RepProfessionalism]                   VARCHAR (255) NULL,
    [RepResponsiveness]                    VARCHAR (255) NULL,
    [RepSpeedToRespond]                    VARCHAR (255) NULL,
    [RepTechKnowledge]                     VARCHAR (255) NULL,
    [Satisfaction_with_Professionalism__c] INT           NULL,
    [Satisfaction_with_Resolution__c]      INT           NULL,
    [Satisfaction_with_Time_to_Answer__c]  INT           NULL,
    [Satisfaction_with_Time_to_Resolve__c] INT           NULL,
    [Satisfaction_with_Troubleshooting__c] INT           NULL,
    [SurveysCreatedDate]                   DATETIME      NULL,
    [SurveysResponseReceivedDate]          DATETIME      NULL
);

