CREATE TABLE [analytics].[ucaas_opps_all_closed] (
    [solution_of_interest]           VARCHAR (500)  NULL,
    [total_contract_value_converted] FLOAT (53)     NULL,
    [product_of_interest]            VARCHAR (500)  NULL,
    [product_name]                   VARCHAR (500)  NULL,
    [opportunity_name]               VARCHAR (500)  NULL,
    [stage]                          VARCHAR (500)  NULL,
    [partner_type]                   VARCHAR (500)  NULL,
    [partner_account_name]           VARCHAR (500)  NULL,
    [sub_agent_account]              VARCHAR (500)  NULL,
    [type]                           VARCHAR (500)  NULL,
    [sub_type]                       VARCHAR (500)  NULL,
    [opportunity_owner]              VARCHAR (500)  NULL,
    [estimated_mrr]                  FLOAT (53)     NULL,
    [term]                           FLOAT (53)     NULL,
    [forecast_theatre]               NVARCHAR (255) NULL,
    [region]                         NVARCHAR (255) NULL,
    [sub_region]                     NVARCHAR (255) NULL,
    [territory]                      NVARCHAR (500) NULL,
    [isr_region]                     VARCHAR (500)  NULL,
    [forecast_category]              VARCHAR (500)  NULL,
    [opportunity_id]                 VARCHAR (500)  NULL,
    [blue_name]                      VARCHAR (500)  NULL,
    [primary_opp_id_orange]          VARCHAR (500)  NULL,
    [secondary_opp_id_orange]        VARCHAR (500)  NULL,
    [opp_id_blue]                    VARCHAR (500)  NULL,
    [num_of_cloud_profiles]          VARCHAR (500)  NULL,
    [account_name]                   VARCHAR (500)  NULL,
    [products]                       VARCHAR (500)  NULL,
    [close_date]                     DATETIME       NULL,
    [close_month]                    VARCHAR (3)    NULL,
    [create_date]                    DATETIME       NULL,
    [created_by]                     VARCHAR (500)  NULL,
    [last_modified_date]             DATETIME       NULL,
    [last_modified_by]               VARCHAR (500)  NULL,
    [extract_date]                   DATETIME       NULL,
    [owner_role]                     VARCHAR (255)  NULL
);

