CREATE TABLE [oss].[OrderItem] (
    [Id]                      INT            NOT NULL,
    [OrderItemTypeId]         INT            NOT NULL,
    [OrderId]                 INT            NOT NULL,
    [Description]             NVARCHAR (256) NULL,
    [DateProcessed]           DATE           NULL,
    [LocationId]              INT            NULL,
    [DateEffective]           DATE           NULL,
    [ServiceClassId]          INT            NULL,
    [InvoiceLabel]            NVARCHAR (100) NULL,
    [Quantity]                INT            NULL,
    [CircuitCarrierCompanyId] INT            NULL,
    [DateModified]            DATETIME2 (4)  NOT NULL,
    [DateCreated]             DATETIME2 (4)  NOT NULL,
    [ModifiedBy]              NVARCHAR (50)  NOT NULL,
    [CreatedByPersonId]       INT            NULL,
    [InvoiceGroupId]          INT            NULL,
    [ProductId]               INT            NULL,
    [InvoiceServiceGroupId]   INT            NULL,
    [MRR]                     MONEY          NULL,
    [NRC]                     MONEY          NULL,
    [PricePlanPriceId]        INT            NULL,
    [PrevMRR]                 MONEY          NULL,
    [PrevNRC]                 MONEY          NULL,
    [PrevPricePlanPriceId]    INT            NULL,
    [CurrencyId]              INT            NULL,
    CONSTRAINT [PK_OrderItem] PRIMARY KEY CLUSTERED ([Id] ASC)
);

