CREATE LOGIN [ITApps]
    WITH PASSWORD = N'mrcfvgg>n$jaygdgf6lhd_lBmsFT7_&#$!~<Pqmg;ewdqnPn', SID = 0x8CD777D649AC2E43AFEBA2A30E1822A0, DEFAULT_DATABASE = [MEGASILO], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

