CREATE LOGIN [ITApps]
    WITH PASSWORD = N'x;vhhlJbGjyGm<fi3hxe{rHjmsFT7_&#$!~<V1g=Fr{h{8+o', SID = 0x51C2E48F06FFA346AAC6ED51B9C2D3AD, DEFAULT_DATABASE = [SMD], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

