CREATE LOGIN [app_MiCC]
    WITH PASSWORD = N'd|fEpvmnGomljq|wws>p4dpcmsFT7_&#$!~<lA55uoWdLnb{', SID = 0xA6B3FF51C4C8C94CACA4AAB7DE7BE0D6, DEFAULT_DATABASE = [FinanceBI], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

