CREATE TABLE [enum].[DimDate] (
    [Date]                  DATE          NOT NULL,
    [Date_Name]             NVARCHAR (50) NOT NULL,
    [Year]                  DATE          NOT NULL,
    [Year_Name]             NVARCHAR (50) NOT NULL,
    [Quarter]               DATE          NOT NULL,
    [Quarter_Name]          NVARCHAR (50) NOT NULL,
    [Month]                 DATE          NOT NULL,
    [Month_Name]            NVARCHAR (50) NOT NULL,
    [Week]                  DATE          NOT NULL,
    [Week_Name]             NVARCHAR (50) NOT NULL,
    [Day_Of_Year]           INT           NOT NULL,
    [Day_Of_Year_Name]      NVARCHAR (50) NOT NULL,
    [Day_Of_Quarter]        INT           NOT NULL,
    [Day_Of_Quarter_Name]   NVARCHAR (50) NOT NULL,
    [Day_Of_Month]          INT           NOT NULL,
    [Day_Of_Month_Name]     NVARCHAR (50) NOT NULL,
    [Day_Of_Week]           INT           NOT NULL,
    [Day_Of_Week_Name]      NVARCHAR (50) NOT NULL,
    [Week_Of_Year]          INT           NOT NULL,
    [Week_Of_Year_Name]     NVARCHAR (50) NOT NULL,
    [Month_Of_Year]         INT           NOT NULL,
    [Month_Of_Year_Name]    NVARCHAR (50) NOT NULL,
    [Month_Of_Quarter]      INT           NOT NULL,
    [Month_Of_Quarter_Name] NVARCHAR (50) NOT NULL,
    [Quarter_Of_Year]       INT           NOT NULL,
    [Quarter_Of_Year_Name]  NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_DimDate] PRIMARY KEY CLUSTERED ([Date] ASC)
);

