CREATE TABLE [audit].[mVwLatestService_Staging] (
    [ServiceId]              INT            NOT NULL,
    [ProductId]              INT            NULL,
    [ServiceClassId]         INT            NOT NULL,
    [ServiceStatusId]        INT            NOT NULL,
    [LocationId]             INT            NULL,
    [InvoiceServiceGroupId]  INT            NULL,
    [AccountId]              INT            NOT NULL,
    [Name]                   NVARCHAR (128) NULL,
    [IsAttachedToTN]         BIT            NOT NULL,
    [TN]                     NVARCHAR (15)  NULL,
    [InvoiceLabel]           NVARCHAR (128) NULL,
    [OrderTypeId]            INT            NULL,
    [WasInInitialOrder]      BIT            NOT NULL,
    [OrderProjectManagerId]  INT            NULL,
    [OrderCreatedByPersonId] INT            NULL,
    [MonthlyCharge]          MONEY          NULL,
    [OneTimeCharge]          MONEY          NULL,
    [DateBillingValidFrom]   DATE           NULL,
    [DateSvcClosed]          DATE           NULL,
    [DateSvcLiveActual]      DATE           NULL,
    [DateSvcLiveScheduled]   DATE           NULL,
    [DateSvcModified]        DATE           NULL,
    [DateSvcCreated]         DATE           NULL,
    [DateBillingValidTo]     DATE           NULL,
    [IsBilledFirstTime]      INT            NOT NULL,
    [MonthSetupInvoiced]     DATE           NULL,
    [MonthLastInvoiced]      DATE           NULL,
    [MonthMRRFirstInvoiced]  DATE           NULL,
    [MonthMRRLastInvoiced]   DATE           NULL,
    [DateMRRInvoicedTo]      DATE           NULL,
    [MonthCreditIssued]      DATE           NULL,
    [DateCreditedFrom]       DATE           NULL,
    [DateCreditedTo]         DATE           NULL,
    [CreatedByPersonId]      INT            NULL,
    [ModifiedByPersonId]     INT            NULL,
    [BillingStage]           VARCHAR (17)   NOT NULL,
    [DataIssueId]            INT            NOT NULL,
    [RankNum]                BIGINT         NULL
);

