CREATE TABLE [audit].[mVwTnProfileService] (
    [TN]                               VARCHAR (15)   NOT NULL,
    [TnStatus]                         NVARCHAR (30)  NULL,
    [TnAccountId]                      INT            NULL,
    [TnAccountPrimaryClusterId]        INT            NULL,
    [IsTnMainNumber]                   INT            NULL,
    [RedirectTn]                       VARCHAR (15)   NULL,
    [TrunkGroupId]                     INT            NULL,
    [Carrier]                          NVARCHAR (100) NULL,
    [ProfileId]                        INT            NULL,
    [ProfileTypeId]                    INT            NULL,
    [ProfileType]                      NVARCHAR (20)  NOT NULL,
    [PartitionId]                      INT            NULL,
    [PartitionClusterId]               INT            NULL,
    [PartitionAccountId]               INT            NULL,
    [PartitionAccountPrimaryClusterId] INT            NULL,
    [ProfileName]                      NVARCHAR (100) NULL,
    [ProfileCallerId]                  NVARCHAR (100) NULL,
    [ProfileIsActive]                  BIT            NOT NULL,
    [ProfileIsDid]                     BIT            NOT NULL,
    [ProfileIsConference]              BIT            NOT NULL,
    [ProfileIsMainLine]                BIT            NOT NULL,
    [ProfileExtension]                 NVARCHAR (15)  NULL,
    [IsUnassignedProfile]              INT            NOT NULL,
    [IsManagedProfile]                 INT            NOT NULL,
    [IsAnalogProfile]                  INT            NOT NULL,
    [IsVirtualProfile]                 INT            NOT NULL,
    [IsCourtesyProfile]                INT            NOT NULL,
    [IsVoicemailProfile]               INT            NOT NULL,
    [IsChargeableProfile]              INT            NOT NULL,
    [DateProfileCreated]               DATETIME2 (4)  NULL,
    [ServiceId]                        INT            NULL,
    [SvcAccountId]                     INT            NULL
);

