CREATE TABLE [commission].[History_PartnerCommission_RPM] (
    [PCMonth]                         DATE            NULL,
    [Region]                          NVARCHAR (50)   NOT NULL,
    [AccountID]                       BIGINT          NULL,
    [ClientName]                      NVARCHAR (100)  NULL,
    [LocationID]                      INT             NULL,
    [Address]                         NVARCHAR (100)  NULL,
    [City]                            NVARCHAR (100)  NULL,
    [CodeAlpha]                       NVARCHAR (10)   NULL,
    [ZipCode]                         NVARCHAR (20)   NULL,
    [LichenClassName]                 NVARCHAR (4000) NULL,
    [ProductId]                       INT             NULL,
    [ProductName]                     NVARCHAR (512)  NULL,
    [ServiceId]                       INT             NULL,
    [ChargeType]                      NVARCHAR (50)   NULL,
    [Charge LC]                       MONEY           NOT NULL,
    [Charge]                          MONEY           NULL,
    [CurrencyCode]                    CHAR (3)        NULL,
    [Description]                     NVARCHAR (512)  NULL,
    [DatePeriodStart]                 DATE            NULL,
    [DatePeriodEnd]                   DATE            NULL,
    [InvoiceMonth]                    DATE            NULL,
    [LineItemId]                      BIGINT          NULL,
    [IsCommisssionable]               INT             NULL,
    [CommissionableBillingsAmount LC] MONEY           NULL,
    [CommissionableBillingsAmount]    MONEY           NULL,
    [CreditingPartnerId]              INT             NULL,
    [CreditingPartner]                NVARCHAR (255)  NULL,
    [PaymentPlan]                     NVARCHAR (255)  NULL,
    [CommRate]                        FLOAT (53)      NULL,
    [PartnerCommissionAmount LC]      MONEY           NULL,
    [PartnerCommissionAmount]         MONEY           NULL,
    [SubAgentId]                      NVARCHAR (128)  NULL,
    [SubAgent]                        NVARCHAR (512)  NULL,
    [RepName]                         NVARCHAR (256)  NULL,
    [CommissionId]                    INT             NULL,
    [LocationChange]                  INT             NULL,
    [AccountChange]                   INT             NULL,
    [ServiceChange]                   INT             NULL,
    [Ac isBillable]                   BIT             NULL,
    [DateCreated]                     DATETIME        NULL,
    [LichenLocationId]                INT             NULL,
    [LichenAccountId]                 INT             NULL,
    [CenturyMonth]                    INT             NULL,
    [InvoiceCount]                    INT             NULL
);


GO
CREATE CLUSTERED INDEX [InvoiceMonth_Partner_PartnerId_CIdx]
    ON [commission].[History_PartnerCommission_RPM]([InvoiceMonth] ASC, [CreditingPartnerId] ASC, [CreditingPartner] ASC);

