CREATE TABLE [commission].[History_Adjustment] (
    [PCmonth]                         DATE            NOT NULL,
    [Region]                          NCHAR (6)       NOT NULL,
    [AccountID]                       BIGINT          NULL,
    [ClientName]                      NVARCHAR (100)  NULL,
    [PaymentPlan]                     NVARCHAR (255)  NULL,
    [CommRate]                        FLOAT (53)      NULL,
    [Description]                     NVARCHAR (512)  NULL,
    [CreditingPartnerID]              BIGINT          NULL,
    [CreditingPartner]                NVARCHAR (255)  NULL,
    [SubAgentID]                      NVARCHAR (128)  NULL,
    [SubAgent]                        NVARCHAR (512)  NULL,
    [RepName]                         NVARCHAR (256)  NULL,
    [Type]                            NVARCHAR (255)  NULL,
    [CurrencyCode]                    CHAR (3)        NULL,
    [NetBilled_LC]                    MONEY           NULL,
    [NetBilled]                       MONEY           NULL,
    [CommissionableBillingsAmount_LC] MONEY           NULL,
    [CommissionableBillingsAmount]    MONEY           NULL,
    [SalesComm_LC]                    MONEY           NULL,
    [SalesComm]                       MONEY           NULL,
    [Notes]                           NVARCHAR (1024) NULL,
    [NotesForStaff]                   NVARCHAR (1024) NULL,
    [ProductId]                       INT             NULL,
    [ProductName]                     NVARCHAR (512)  NULL,
    [Id]                              BIGINT          NULL,
    [Supplier]                        NVARCHAR (255)  NULL,
    [Address]                         NVARCHAR (100)  NULL,
    [City]                            NVARCHAR (100)  NULL,
    [CodeAlpha]                       NVARCHAR (10)   NULL,
    [ZipCode]                         NVARCHAR (20)   NULL,
    [CenturyMonth]                    INT             NULL,
    [invoiceMonth]                    DATE            NULL,
    [ChargeType]                      NVARCHAR (50)   NULL,
    [Charge]                          MONEY           NULL,
    [LichenAccountId]                 INT             NULL,
    [DateModified]                    DATETIME2 (4)   NULL,
    [DateCreated]                     DATETIME2 (4)   NULL,
    [ModifiedBy]                      NVARCHAR (50)   NULL
);

