CREATE TABLE [OrangeStaging].[Location] (
    [Account_c]                  VARCHAR (50)  NULL,
    [Active_Seats_c]             VARCHAR (50)  NULL,
    [boss_Abbrev_c]              VARCHAR (255) NULL,
    [boss_City_c]                VARCHAR (255) NULL,
    [boss_Country_c]             VARCHAR (255) NULL,
    [boss_Demarcation_Point_c]   VARCHAR (MAX) NULL,
    [boss_ForecastDate_c]        VARCHAR (50)  NULL,
    [boss_LATA_c]                VARCHAR (50)  NULL,
    [boss_location_id_c]         VARCHAR (50)  NULL,
    [boss_Location_Live_c]       VARCHAR (50)  NULL,
    [boss_NPA_c]                 VARCHAR (50)  NULL,
    [boss_NXX_c]                 VARCHAR (50)  NULL,
    [boss_State_c]               VARCHAR (50)  NULL,
    [boss_Status_c]              VARCHAR (50)  NULL,
    [boss_Subtenant_c]           VARCHAR (50)  NOT NULL,
    [boss_Zip_Code_c]            VARCHAR (50)  NULL,
    [ConnectionReceivedId]       VARCHAR (50)  NULL,
    [ConnectionSentId]           VARCHAR (50)  NULL,
    [Contract_Commitment_Date_c] VARCHAR (50)  NULL,
    [CreatedById]                VARCHAR (18)  NOT NULL,
    [CreatedDate]                VARCHAR (50)  NOT NULL,
    [CurrencyIsoCode]            VARCHAR (50)  NOT NULL,
    [Date_Set_Active_c]          VARCHAR (50)  NULL,
    [Id]                         VARCHAR (18)  NOT NULL,
    [Installation_Type_c]        VARCHAR (50)  NULL,
    [IsDeleted]                  VARCHAR (50)  NOT NULL,
    [Is_CX_c]                    VARCHAR (50)  NOT NULL,
    [Is_ECC_SCC_c]               VARCHAR (50)  NOT NULL,
    [Is_Hybrid_c]                VARCHAR (50)  NOT NULL,
    [Is_Migration_c]             VARCHAR (50)  NOT NULL,
    [Is_Mitel_Circuit_c]         VARCHAR (50)  NOT NULL,
    [Is_MPLS_c]                  VARCHAR (50)  NOT NULL,
    [LastActivityDate]           VARCHAR (50)  NULL,
    [LastModifiedById]           VARCHAR (18)  NOT NULL,
    [LastModifiedDate]           VARCHAR (50)  NOT NULL,
    [LastReferencedDate]         VARCHAR (50)  NULL,
    [LastViewedDate]             VARCHAR (50)  NULL,
    [Number_of_Locations_c]      FLOAT (53)    NOT NULL,
    [Opportunity_c]              VARCHAR (50)  NULL,
    [OwnerId]                    VARCHAR (255) NOT NULL,
    CONSTRAINT [PK_Orange_Location] PRIMARY KEY CLUSTERED ([Id] ASC)
);

