CREATE TABLE [expinvoice].[IACP_V3] (
    [MRR Category]     VARCHAR (32)   NOT NULL,
    [Client]           NVARCHAR (256) NOT NULL,
    [AccountId]        INT            NOT NULL,
    [LocationId]       INT            NULL,
    [Loc Name]         NVARCHAR (256) NULL,
    [Account Team]     VARCHAR (50)   NULL,
    [Order Creator]    NVARCHAR (256) NULL,
    [Order PM]         NVARCHAR (256) NULL,
    [Price Incr/Decr]  VARCHAR (32)   NULL,
    [New MRR]          MONEY          NULL,
    [Prev MRR]         MONEY          NULL,
    [MRR Delta]        MONEY          NULL,
    [OrderId]          INT            NULL,
    [Order Type]       NVARCHAR (20)  NULL,
    [Order Status]     NVARCHAR (20)  NULL,
    [Order Name]       NVARCHAR (128) NULL,
    [Date Created]     DATE           NULL,
    [Date Closed]      DATE           NULL,
    [Date Live Actual] DATE           NULL,
    [Portal ServiceId] INT            NULL,
    [Svc Name]         NVARCHAR (256) NULL,
    [Service Class]    NVARCHAR (128) NULL,
    [Service Status]   NVARCHAR (128) NULL,
    [CurrencyId]       INT            CONSTRAINT [DF_IACP_V3_CurrencyId] DEFAULT ((1)) NULL,
    [Currency]         NVARCHAR (15)  NULL,
    [InvoiceGroupId]   INT            NULL,
    [InvoiceGroupName] NVARCHAR (256) NULL
);

