
/****** Script for SelectTopNRows command from SSMS  ******/
CREATE view [dbo].[VwMigrate_PartnerCommission_RPM] as
SELECT CommissionMonth [PCMonth]
      ,'US' [Region]
      ,A.Id [AccountID]
      ,[ClientName]
      ,L.Id [LocationID]
      ,L.[Address]
      ,L.[City]
      ,PC.[CodeAlpha]
      ,L.[ZipCode]
      ,PC.[LichenClassName]
      ,null [ProductId]
      ,null [ProductName]
      ,[ServiceId]
      ,[ChargeType]
      ,[Charge] [Charge LC]
      ,[Charge]
      ,'USD' [CurrencyCode]
      ,[Description]
      ,[DatePeriodStart]
      ,[DatePeriodEnd]
      ,[InvoiceMonth]
      ,[LineItemId]
      ,[IsCommisssionable]
      ,[CommissionableBillingsAmount] [CommissionableBillingsAmount LC]
      ,[CommissionableBillingsAmount]
      ,[CreditingPartnerId]
      ,[CreditingPartner]
      ,[PaymentPlan]
      ,[CommRate]
      ,[PartnerCommissionAmount] [PartnerCommissionAmount LC]
      ,[PartnerCommissionAmount]
      ,PC.RepId [SubAgentId]
      ,[SubAgent]
      ,[RepName]
      ,[CommissionId]
      ,[LocationChange]
      ,[AccountChange]
      ,[ServiceChange]
      ,[Ac isBillable]
      ,PC.createdate [DateCreated]
      ,PC.[LichenLocationId]
      ,PC.[LichenAccountId]
      ,[CenturyMonth]
      ,[InvoiceCount]
  FROM [commission].[Commission.Backup_History_PartnerCommission_RPM] PC
  left join company.Location L on L.LichenLocationId = PC.lichenlocationid
   left join company.Account A on A.Id = L.AccountId


