CREATE TABLE [cdr].[CallReport_Spl_AC] (
    [id]                      BIGINT         NOT NULL,
    [start]                   DATETIME       NOT NULL,
    [endTs]                   DATETIME       NULL,
    [duration]                BIGINT         NOT NULL,
    [charge]                  FLOAT (53)     NOT NULL,
    [profileId]               BIGINT         NOT NULL,
    [profileName]             NVARCHAR (128) NOT NULL,
    [tn]                      NVARCHAR (15)  NOT NULL,
    [ani]                     VARCHAR (15)   NOT NULL,
    [orig]                    VARCHAR (15)   NOT NULL,
    [clid]                    VARCHAR (15)   NOT NULL,
    [servicetypeId]           BIGINT         NOT NULL,
    [routetypeId]             BIGINT         NOT NULL,
    [callTypeId]              BIGINT         NULL,
    [accountId]               BIGINT         NOT NULL,
    [locationId]              BIGINT         NOT NULL,
    [locationName]            NVARCHAR (128) NOT NULL,
    [labelName]               NVARCHAR (64)  NOT NULL,
    [aniCountryId]            BIGINT         NULL,
    [aniStateId]              BIGINT         NULL,
    [aniCityId]               BIGINT         NULL,
    [aniCountry]              VARCHAR (64)   NULL,
    [aniState]                VARCHAR (4)    NULL,
    [aniCity]                 VARCHAR (50)   NULL,
    [aniNpaNxx]               VARCHAR (7)    NULL,
    [origCountryId]           BIGINT         NULL,
    [origStateId]             BIGINT         NULL,
    [origCityId]              BIGINT         NULL,
    [origCountry]             VARCHAR (64)   NULL,
    [origState]               VARCHAR (4)    NULL,
    [origCity]                VARCHAR (50)   NULL,
    [origNpaNxx]              VARCHAR (7)    NULL,
    [billCode]                VARCHAR (9)    NULL,
    [switchId]                BIGINT         NOT NULL,
    [switchName]              VARCHAR (50)   NOT NULL,
    [nativeId]                VARCHAR (32)   NOT NULL,
    [callId]                  BIGINT         NULL,
    [ratedId]                 BIGINT         NULL,
    [transferType]            VARCHAR (20)   NULL,
    [terminatingEndpoint]     NVARCHAR (32)  NULL,
    [terminatingEndpointTn]   VARCHAR (15)   NULL,
    [terminatingEndpointName] NVARCHAR (128) NULL,
    [DateModified]            DATETIME       NOT NULL,
    [DateCreated]             DATETIME       NOT NULL,
    [internal]                BIT            NULL,
    [rateId]                  BIGINT         NULL
);

