CREATE TABLE [BlueM].[Case] (
    [Id]                                   VARCHAR (20)    NOT NULL,
    [Status]                               VARCHAR (250)   NULL,
    [OwnerId]                              VARCHAR (20)    NULL,
    [SERVICE_Customer_Type__c]             VARCHAR (250)   NULL,
    [CaseNumber]                           VARCHAR (15)    NULL,
    [CreatedDate]                          DATETIME        NULL,
    [Origin]                               VARCHAR (250)   NULL,
    [SERVICE_Case_Reason__c]               VARCHAR (250)   NULL,
    [SERVICE_Sub_Reason__c]                VARCHAR (250)   NULL,
    [SERVICE_Feature__c]                   VARCHAR (250)   NULL,
    [SERVICE_Sub_Feature__c]               VARCHAR (250)   NULL,
    [Escalation__c]                        BIT             NULL,
    [Escalated_By__c]                      VARCHAR (20)    NULL,
    [Escalation_Origination__c]            VARCHAR (250)   NULL,
    [Escalation_Resolved__c]               VARCHAR (3)     NULL,
    [AccountId]                            VARCHAR (20)    NULL,
    [Service_Platform__c]                  VARCHAR (250)   NULL,
    [Instance__c]                          VARCHAR (250)   NULL,
    [Subject]                              NVARCHAR (3000) NULL,
    [Priority]                             VARCHAR (10)    NULL,
    [SERVICE_Root_Cause__c]                VARCHAR (250)   NULL,
    [IsClosed]                             BIT             NULL,
    [Resolution__c]                        VARCHAR (250)   NULL,
    [SERVICE_Engineering_Status__c]        VARCHAR (250)   NULL,
    [Date_Escalated__c]                    DATETIME        NULL,
    [CreatedById]                          VARCHAR (20)    NULL,
    [ClosedDate]                           DATETIME        NULL,
    [LastModifiedById]                     VARCHAR (20)    NULL,
    [LastModifiedDate]                     DATETIME        NULL,
    [IsDeleted]                            BIT             NULL,
    [Legacy_Case_Id__c]                    VARCHAR (15)    NULL,
    [MilestoneStatus]                      VARCHAR (250)   NULL,
    [ParentId]                             VARCHAR (20)    NULL,
    [Service_Case_Owner_Role__c]           VARCHAR (250)   NULL,
    [SERVICE_End_User_Account_Name__c]     VARCHAR (250)   NULL,
    [Service_Number_of_emails_sent__c]     DECIMAL (5, 2)  NULL,
    [SERVICE_Partner_for_Case__c]          VARCHAR (250)   NULL,
    [SERVICE_Partner_of_Record__c]         VARCHAR (250)   NULL,
    [SERVICE_Priority_at_Case_Creation__c] VARCHAR (10)    NULL,
    CONSTRAINT [PK_blue_Case] PRIMARY KEY CLUSTERED ([Id] ASC)
);

