
Create View [sfdc].[VSfdcTerritoryTableLoad]
AS
SELECT [Created]
      ,[SfdcId]
      ,[AXCode]
      ,[Region]
      ,[TerritoryName]
      ,[Subregion]
      ,[Theatre]
      ,[CSM]
      ,[ASM]
      ,[SE]
      ,[RVP]
      ,[RD]
      ,[ASR]
      ,[DualCSEPBM]
      ,[CloudCSR]
      ,[GOV]
  FROM [sfdc].[Territory]