CREATE TABLE [sfdc].[mVwOpportunity] (
    [OpportunityId]               VARCHAR (50)    COLLATE Latin1_General_BIN NOT NULL,
    [Opportunity Name]            VARCHAR (8000)  NULL,
    [AccountName]                 VARCHAR (500)   NULL,
    [SFDC AccountId]              VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [Client]                      VARCHAR (100)   NULL,
    [Amount]                      NUMERIC (38, 6) NULL,
    [Amount Won]                  NUMERIC (38, 6) NULL,
    [Date Closed]                 DATE            NULL,
    [Contract Type]               VARCHAR (500)   COLLATE Latin1_General_BIN NULL,
    [Lead Source]                 VARCHAR (500)   COLLATE Latin1_General_BIN NULL,
    [Opportunity Type]            VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [Opportunity Lead Source]     VARCHAR (500)   COLLATE Latin1_General_BIN NULL,
    [LeadPartnerID]               VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [Lead Partner]                VARCHAR (100)   NULL,
    [Referred by ParnterId]       VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [Ref Partner]                 VARCHAR (100)   NULL,
    [# Profiles]                  INT             NULL,
    [Deal Size]                   VARCHAR (500)   COLLATE Latin1_General_BIN NULL,
    [Stage]                       VARCHAR (500)   COLLATE Latin1_General_BIN NULL,
    [StageCurrent]                VARCHAR (500)   COLLATE Latin1_General_BIN NULL,
    [Won]                         INT             NOT NULL,
    [Portal AccountId]            INT             NULL,
    [DateCreated]                 DATE            NULL,
    [DateLastModified]            DATE            NULL,
    [SfdcDateLastModified]        DATE            NULL,
    [OpportunityNumber]           VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [SubType]                     VARCHAR (500)   COLLATE Latin1_General_BIN NULL,
    [NumOfConnectBundles]         VARCHAR (500)   COLLATE Latin1_General_BIN NULL,
    [LeadCategory]                VARCHAR (500)   COLLATE Latin1_General_BIN NULL,
    [CountryCode]                 VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [TerritorySfdcId]             VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [LastModifiedById]            VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [Amount_Cur]                  NUMERIC (18, 2) NULL,
    [CurrencyCode]                VARCHAR (50)    COLLATE Latin1_General_BIN NULL,
    [WelcomeContact]              VARCHAR (150)   COLLATE Latin1_General_BIN NULL,
    [NCAM]                        VARCHAR (150)   COLLATE Latin1_General_BIN NULL,
    [AgentCAM]                    VARCHAR (150)   COLLATE Latin1_General_BIN NULL,
    [CommTAM]                     VARCHAR (150)   COLLATE Latin1_General_BIN NULL,
    [AdvancedISRId]               VARCHAR (500)   COLLATE Latin1_General_BIN NULL,
    [SubAgent]                    VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [ShoreTelTerritory]           NVARCHAR (255)  COLLATE Latin1_General_BIN NULL,
    [NoteId]                      VARCHAR (25)    COLLATE Latin1_General_BIN NULL,
    [NoteTitle]                   VARCHAR (250)   COLLATE Latin1_General_BIN NULL,
    [NoteModifiedDate]            DATETIME        NULL,
    [NoteModifiedBy]              VARCHAR (150)   COLLATE Latin1_General_BIN NULL,
    [RecordType]                  VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [OppOwner]                    VARCHAR (500)   COLLATE Latin1_General_BIN NULL,
    [Contract_Signed_By__c]       VARCHAR (150)   COLLATE Latin1_General_BIN NULL,
    [Eligible_Support_Partner__c] VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [OneView_Subtype__c]          VARCHAR (100)   COLLATE Latin1_General_BIN NULL,
    [SelfStart]                   VARCHAR (250)   COLLATE Latin1_General_BIN NULL,
    [VE__c]                       VARCHAR (5)     COLLATE Latin1_General_BIN NULL,
    [Debooked Opportunity]        VARCHAR (3)     COLLATE Latin1_General_BIN NOT NULL
);

