CREATE TABLE [invoice].[MatVwIncrMRRNRR_EX_FY18] (
    [AccountId]              INT             NULL,
    [LocationId]             INT             NULL,
    [OrderProjectManagerId]  INT             NULL,
    [OrderCreatedByPersonId] INT             NULL,
    [orderedById]            INT             NULL,
    [OrderSalesPersonId]     INT             NULL,
    [Ac Team]                NVARCHAR (32)   NULL,
    [AccountManagerId]       INT             NULL,
    [MRR Category]           NVARCHAR (50)   NULL,
    [MRR Prev]               NUMERIC (38, 6) NULL,
    [MRR Expected]           NUMERIC (38, 6) NULL,
    [MRR Delta]              NUMERIC (38, 6) NULL,
    [NRR]                    NUMERIC (38, 6) NULL,
    [CurrencyCode]           CHAR (3)        NOT NULL,
    [MRR Prev LC]            MONEY           NULL,
    [MRR Expected LC]        MONEY           NULL,
    [MRR Delta LC]           MONEY           NULL,
    [NRR LC]                 MONEY           NULL,
    [InvoiceDay]             DATE            NULL,
    [InvoiceMonth]           DATE            NULL,
    [ServiceId]              INT             NULL,
    [ProductId]              INT             NULL,
    [OrderId]                INT             NULL,
    [OrderTypeId]            INT             NULL,
    [Order Date Created]     DATE            NULL,
    [ServiceClassId]         INT             NOT NULL,
    [DateSvcLiveActual]      DATE            NULL,
    [ServiceStatusId]        INT             NOT NULL,
    [BillingStage]           VARCHAR (17)    NOT NULL,
    [BookToBillDays]         FLOAT (53)      NULL,
    [Quantity]               INT             NOT NULL,
    [DeltaQuantity]          INT             NOT NULL,
    [QMRR]                   NUMERIC (19, 4) NULL
);

