CREATE TABLE [invoice].[MatVwIncrMRRNRR] (
    [AccountId]              INT             NULL,
    [LocationId]             INT             NULL,
    [OrderProjectManagerId]  INT             NULL,
    [OrderCreatedByPersonId] INT             NULL,
    [orderedById]            INT             NULL,
    [OrderSalesPersonId]     INT             NULL,
    [Ac Team]                NVARCHAR (32)   NULL,
    [AccountManagerId]       INT             NULL,
    [MRR Category]           NVARCHAR (32)   NULL,
    [MRR Prev]               NUMERIC (19, 4) NULL,
    [MRR Expected]           NUMERIC (19, 4) NULL,
    [MRR Delta]              NUMERIC (19, 4) NULL,
    [NRR]                    MONEY           NULL,
    [InvoiceDay]             DATETIME        NULL,
    [InvoiceMonth]           DATETIME        NULL,
    [ServiceId]              INT             NULL,
    [ProductId]              INT             NULL,
    [OrderId]                INT             NULL,
    [OrderTypeId]            INT             NULL,
    [Order Date Created]     DATE            NULL,
    [ServiceClassId]         INT             NOT NULL,
    [DateSvcLiveActual]      DATE            NULL,
    [ServiceStatusId]        INT             NOT NULL,
    [BillingStage]           VARCHAR (17)    NOT NULL,
    [BookToBillDays]         FLOAT (53)      NULL,
    [Quantity]               INT             NOT NULL,
    [DeltaQuantity]          INT             NOT NULL,
    [QMRR]                   NUMERIC (19, 4) NULL
);

