CREATE TABLE [invoice].[mVwFinalSPItem] (
    [LocationId]                  INT           NULL,
    [AccountId]                   INT           NOT NULL,
    [InvoiceGroupId]              INT           NULL,
    [ServiceId]                   INT           NULL,
    [ProductId]                   INT           NULL,
    [BillingCategoryId]           INT           NULL,
    [ChargeCategoryId]            INT           NOT NULL,
    [MonthlySubCategoryId]        INT           NULL,
    [ServiceMonth]                DATETIME2 (7) NULL,
    [InvoiceMonth]                DATE          NULL,
    [Charge]                      FLOAT (53)    NULL,
    [MonthlyCharge]               FLOAT (53)    NULL,
    [OneTimeCharge]               MONEY         NULL,
    [MRR]                         FLOAT (53)    NULL,
    [MRRDeltaForNextServiceMonth] FLOAT (53)    NULL,
    [MonthsBilled]                FLOAT (53)    NULL,
    [Resub_MoM]                   FLOAT (53)    NULL,
    [Resub_YoY]                   FLOAT (53)    NULL,
    [IsAdvanceBilling]            INT           NOT NULL,
    [IsMovingNextMonth]           INT           NOT NULL,
    [FirsMRRBilling]              INT           NOT NULL,
    [DataIssueId]                 INT           NOT NULL,
    [CCRankAsc]                   BIGINT        NULL,
    [CCRankDesc]                  BIGINT        NULL,
    [ServiceStatusId]             INT           NOT NULL,
    [OrderTypeId]                 INT           NULL,
    [DateSvcLiveScheduled]        DATE          NULL,
    [MonthMRRFirstInvoiced]       DATE          NULL,
    [DateSvcCreated]              DATE          NULL
);

