CREATE TABLE [ax].[CustTable] (
    [ACCOUNTNUM]                 NVARCHAR (40)    NOT NULL,
    [NAME]                       NVARCHAR (100)   NOT NULL,
    [ADDRESS]                    NVARCHAR (250)   NOT NULL,
    [PHONE]                      NVARCHAR (20)    NOT NULL,
    [TELEFAX]                    NVARCHAR (20)    NOT NULL,
    [INVOICEACCOUNT]             NVARCHAR (40)    NOT NULL,
    [CUSTGROUP]                  NVARCHAR (30)    NOT NULL,
    [LINEDISC]                   NVARCHAR (30)    NOT NULL,
    [PAYMTERMID]                 NVARCHAR (30)    NOT NULL,
    [CASHDISC]                   NVARCHAR (30)    NOT NULL,
    [CURRENCY]                   NVARCHAR (3)     NOT NULL,
    [BLOCKED]                    INT              NOT NULL,
    [ONETIMECUSTOMER]            INT              NOT NULL,
    [ACCOUNTSTATEMENT]           INT              NOT NULL,
    [CREDITMAX]                  NUMERIC (28, 12) NOT NULL,
    [MANDATORYCREDITLIMIT]       INT              NOT NULL,
    [DIMENSION]                  NVARCHAR (30)    NOT NULL,
    [DIMENSION2_]                NVARCHAR (30)    NOT NULL,
    [DIMENSION3_]                NVARCHAR (30)    NOT NULL,
    [VENDACCOUNT]                NVARCHAR (40)    NOT NULL,
    [TELEX]                      NVARCHAR (20)    NOT NULL,
    [PRICEGROUP]                 NVARCHAR (30)    NOT NULL,
    [MULTILINEDISC]              NVARCHAR (30)    NOT NULL,
    [ENDDISC]                    NVARCHAR (30)    NOT NULL,
    [VATNUM]                     NVARCHAR (20)    NOT NULL,
    [COUNTRYREGIONID]            NVARCHAR (30)    NOT NULL,
    [INVENTLOCATION]             NVARCHAR (30)    NOT NULL,
    [DLVTERM]                    NVARCHAR (30)    NOT NULL,
    [DLVMODE]                    NVARCHAR (30)    NOT NULL,
    [MARKUPGROUP]                NVARCHAR (30)    NOT NULL,
    [CLEARINGPERIOD]             NVARCHAR (30)    NOT NULL,
    [ZIPCODE]                    NVARCHAR (10)    NOT NULL,
    [STATE]                      NVARCHAR (30)    NOT NULL,
    [COUNTY]                     NVARCHAR (30)    NOT NULL,
    [URL]                        NVARCHAR (255)   NOT NULL,
    [EMAIL]                      NVARCHAR (80)    NOT NULL,
    [CELLULARPHONE]              NVARCHAR (20)    NOT NULL,
    [PHONELOCAL]                 NVARCHAR (10)    NOT NULL,
    [FREIGHTZONE]                NVARCHAR (30)    NOT NULL,
    [CREDITRATING]               NVARCHAR (10)    NOT NULL,
    [TAXGROUP]                   NVARCHAR (30)    NOT NULL,
    [STATISTICSGROUP]            NVARCHAR (30)    NOT NULL,
    [PAYMMODE]                   NVARCHAR (30)    NOT NULL,
    [BANKACCOUNT]                NVARCHAR (10)    NOT NULL,
    [PAYMSCHED]                  NVARCHAR (30)    NOT NULL,
    [NAMEALIAS]                  NVARCHAR (20)    NOT NULL,
    [CONTACTPERSONID]            NVARCHAR (40)    NOT NULL,
    [INVOICEADDRESS]             INT              NOT NULL,
    [OURACCOUNTNUM]              NVARCHAR (20)    NOT NULL,
    [SALESPOOLID]                NVARCHAR (30)    NOT NULL,
    [INCLTAX]                    INT              NOT NULL,
    [CUSTITEMGROUPID]            NVARCHAR (30)    NOT NULL,
    [NUMBERSEQUENCEGROUP]        NVARCHAR (30)    NOT NULL,
    [LANGUAGEID]                 NVARCHAR (7)     NOT NULL,
    [PAYMDAYID]                  NVARCHAR (30)    NOT NULL,
    [LINEOFBUSINESSID]           NVARCHAR (30)    NOT NULL,
    [DESTINATIONCODEID]          NVARCHAR (30)    NOT NULL,
    [SUPPITEMGROUPID]            NVARCHAR (30)    NOT NULL,
    [TAXLICENSENUM]              NVARCHAR (20)    NOT NULL,
    [WEBSALESORDERDISPLAY]       INT              NOT NULL,
    [PAYMSPEC]                   NVARCHAR (30)    NOT NULL,
    [BANKCENTRALBANKPURPOSETEXT] NVARCHAR (140)   NOT NULL,
    [BANKCENTRALBANKPURPOSECODE] NVARCHAR (10)    NOT NULL,
    [CITY]                       NVARCHAR (100)   NOT NULL,
    [STREET]                     NVARCHAR (250)   NOT NULL,
    [PAGER]                      NVARCHAR (20)    NOT NULL,
    [SMS]                        NVARCHAR (80)    NOT NULL,
    [PACKMATERIALFEELICENSENUM]  NVARCHAR (20)    NOT NULL,
    [DLVREASON]                  NVARCHAR (30)    NOT NULL,
    [SALESCALENDARID]            NVARCHAR (10)    NOT NULL,
    [CUSTCLASSIFICATIONID]       NVARCHAR (30)    NOT NULL,
    [SHIPCARRIERACCOUNT]         NVARCHAR (25)    NOT NULL,
    [INVENTSITEID]               NVARCHAR (10)    NOT NULL,
    [ORDERENTRYDEADLINEGROUPID]  NVARCHAR (30)    NOT NULL,
    [SHIPCARRIERID]              NVARCHAR (10)    NOT NULL,
    [SHIPCARRIERFUELSURCHARGE]   INT              NOT NULL,
    [SHIPCARRIERBLINDSHIPMENT]   INT              NOT NULL,
    [PARTYTYPE]                  INT              NOT NULL,
    [PARTYID]                    NVARCHAR (20)    NOT NULL,
    [SHIPCARRIERACCOUNTCODE]     NVARCHAR (20)    NOT NULL,
    [PROJPRICEGROUP]             NVARCHAR (30)    NOT NULL,
    [SYNCENTITYID]               UNIQUEIDENTIFIER NOT NULL,
    [SYNCVERSION]                BIGINT           NOT NULL,
    [MEMO]                       NTEXT            NULL,
    [SALESDISTRICTID]            NVARCHAR (20)    NOT NULL,
    [SEGMENTID]                  NVARCHAR (20)    NOT NULL,
    [SUBSEGMENTID]               NVARCHAR (20)    NOT NULL,
    [COMPANYCHAINID]             NVARCHAR (20)    NOT NULL,
    [MAINCONTACTID]              NVARCHAR (40)    NOT NULL,
    [IDENTIFICATIONNUMBER]       NVARCHAR (50)    NOT NULL,
    [PARTYCOUNTRY]               NVARCHAR (30)    NOT NULL,
    [PARTYSTATE]                 NVARCHAR (30)    NOT NULL,
    [SEMEXCLUDE]                 INT              NOT NULL,
    [SEMDATECODECRITERIA]        NVARCHAR (10)    NOT NULL,
    [MODIFIEDDATETIME]           DATETIME2 (7)    NOT NULL,
    [CREATEDDATETIME]            DATETIME2 (7)    NOT NULL,
    [DATAAREAID]                 NVARCHAR (4)     NOT NULL,
    [RECVERSION]                 INT              NOT NULL,
    [RECID]                      BIGINT           NOT NULL,
    [COLLECTOR]                  NVARCHAR (40)    NOT NULL,
    [ORIGINATINGCUSTOMER]        NVARCHAR (40)    NOT NULL,
    [SEMDNB]                     NVARCHAR (25)    NOT NULL,
    [SEMCUSTINACTIVE]            INT              NOT NULL,
    [SEMCUSTSIEBELID]            NVARCHAR (25)    NOT NULL,
    [SEMECSHIP]                  INT              NOT NULL,
    [SEMCUSTSICID]               NVARCHAR (25)    NOT NULL,
    [FS_COLLECTOR]               NVARCHAR (100)   NOT NULL,
    [DONOTPRINTINVOICE]          INT              NOT NULL,
    [INVOICEEMAIL]               NVARCHAR (80)    NOT NULL,
    [PACKINGSLIPEMAIL]           NVARCHAR (80)    NOT NULL,
    [CONFIRMATIONEMAIL]          NVARCHAR (80)    NOT NULL,
    [MODIFIEDBY]                 NVARCHAR (5)     NOT NULL,
    [CREATEDBY]                  NVARCHAR (5)     NOT NULL,
    [RMAPOSTINPROGRESS]          INT              NOT NULL,
    [AMLINEDISCOUNT]             NUMERIC (28, 12) NOT NULL,
    [DMMDELTADISCADD]            NUMERIC (28, 12) NOT NULL,
    [DMMSERVICEPROVIDER]         INT              NOT NULL,
    [STCLOUDINVOICEID]           NVARCHAR (30)    NOT NULL,
    [STCLOUDLICHENINVOICEID]     NVARCHAR (30)    NOT NULL,
    [STCLOUDACCOUNTTEAM]         NVARCHAR (30)    NOT NULL,
    [ONETIMECUSTOMER1]           INT              NOT NULL,
    [SEM_DONOTREALLOCATE]        INT              NOT NULL,
    [STINVOICEEMAILEDI]          NVARCHAR (80)    NOT NULL,
    [STCLOUDACCOUNTMANAGER]      NVARCHAR (30)    NOT NULL,
    [STGSTACCOUNT]               INT              NOT NULL,
    [STMULTIYEARPRICE]           INT              NOT NULL,
    [STCONNECTCUSTOMER]          INT              NOT NULL,
    [STCONTRACTENDDATE]          DATETIME2 (7)    NOT NULL,
    [STEXCLUDECOBRANDED]         INT              NOT NULL
);

