CREATE TABLE [ax].[PurchTable] (
    [PURCHID]                        NVARCHAR (20)    NOT NULL,
    [PURCHNAME]                      NVARCHAR (100)   NOT NULL,
    [ORDERACCOUNT]                   NVARCHAR (40)    NOT NULL,
    [INVOICEACCOUNT]                 NVARCHAR (40)    NOT NULL,
    [FREIGHTZONE]                    NVARCHAR (30)    NOT NULL,
    [EMAIL]                          NVARCHAR (80)    NOT NULL,
    [DELIVERYDATE]                   DATETIME         NOT NULL,
    [DELIVERYTYPE]                   INT              NOT NULL,
    [ADDRESSREFRECID]                BIGINT           NOT NULL,
    [ADDRESSREFTABLEID]              INT              NOT NULL,
    [INTERCOMPANYORIGINALSALESID]    NVARCHAR (20)    NOT NULL,
    [INTERCOMPANYORIGINALCUSTACCO12] NVARCHAR (40)    NOT NULL,
    [CURRENCYCODE]                   NVARCHAR (3)     NOT NULL,
    [PAYMENT]                        NVARCHAR (30)    NOT NULL,
    [CASHDISC]                       NVARCHAR (30)    NOT NULL,
    [PURCHPLACER]                    NVARCHAR (40)    NOT NULL,
    [VENDGROUP]                      NVARCHAR (30)    NOT NULL,
    [LINEDISC]                       NVARCHAR (30)    NOT NULL,
    [DISCPERCENT]                    NUMERIC (28, 12) NOT NULL,
    [DIMENSION]                      NVARCHAR (30)    NOT NULL,
    [DIMENSION2_]                    NVARCHAR (30)    NOT NULL,
    [DIMENSION3_]                    NVARCHAR (30)    NOT NULL,
    [PRICEGROUPID]                   NVARCHAR (30)    NOT NULL,
    [MULTILINEDISC]                  NVARCHAR (30)    NOT NULL,
    [ENDDISC]                        NVARCHAR (30)    NOT NULL,
    [INTERCOMPANYCUSTPURCHORDERFO26] NVARCHAR (50)    NOT NULL,
    [DELIVERYADDRESS]                NVARCHAR (250)   NOT NULL,
    [TAXGROUP]                       NVARCHAR (30)    NOT NULL,
    [DLVTERM]                        NVARCHAR (30)    NOT NULL,
    [DLVMODE]                        NVARCHAR (30)    NOT NULL,
    [PURCHSTATUS]                    INT              NOT NULL,
    [MARKUPGROUP]                    NVARCHAR (30)    NOT NULL,
    [PURCHASETYPE]                   INT              NOT NULL,
    [URL]                            NVARCHAR (255)   NOT NULL,
    [POSTINGPROFILE]                 NVARCHAR (10)    NOT NULL,
    [DELIVERYZIPCODE]                NVARCHAR (10)    NOT NULL,
    [DLVCOUNTY]                      NVARCHAR (30)    NOT NULL,
    [DLVCOUNTRYREGIONID]             NVARCHAR (30)    NOT NULL,
    [DLVSTATE]                       NVARCHAR (30)    NOT NULL,
    [SETTLEVOUCHER]                  INT              NOT NULL,
    [CASHDISCPERCENT]                NUMERIC (28, 12) NOT NULL,
    [DELIVERYNAME]                   NVARCHAR (100)   NOT NULL,
    [COVSTATUS]                      INT              NOT NULL,
    [PAYMENTSCHED]                   NVARCHAR (30)    NOT NULL,
    [INVENTSITEID]                   NVARCHAR (10)    NOT NULL,
    [ONETIMEVENDOR]                  INT              NOT NULL,
    [RETURNITEMNUM]                  NVARCHAR (15)    NOT NULL,
    [FREIGHTSLIPTYPE]                INT              NOT NULL,
    [DOCUMENTSTATUS]                 INT              NOT NULL,
    [CONTACTPERSONID]                NVARCHAR (40)    NOT NULL,
    [INVENTLOCATIONID]               NVARCHAR (30)    NOT NULL,
    [ITEMBUYERGROUPID]               NVARCHAR (30)    NOT NULL,
    [PROJID]                         NVARCHAR (10)    NOT NULL,
    [PURCHPOOLID]                    NVARCHAR (30)    NOT NULL,
    [VATNUM]                         NVARCHAR (20)    NOT NULL,
    [INCLTAX]                        INT              NOT NULL,
    [NUMBERSEQUENCEGROUP]            NVARCHAR (30)    NOT NULL,
    [LANGUAGEID]                     NVARCHAR (7)     NOT NULL,
    [AUTOSUMMARYMODULETYPE]          INT              NOT NULL,
    [PAYMMODE]                       NVARCHAR (30)    NOT NULL,
    [PAYMSPEC]                       NVARCHAR (30)    NOT NULL,
    [FIXEDDUEDATE]                   DATETIME         NOT NULL,
    [DELIVERYCITY]                   NVARCHAR (100)   NOT NULL,
    [DELIVERYSTREET]                 NVARCHAR (250)   NOT NULL,
    [VENDORREF]                      NVARCHAR (100)   NOT NULL,
    [RETURNREASONCODEID]             NVARCHAR (10)    NOT NULL,
    [RETURNREPLACEMENTCREATED]       INT              NOT NULL,
    [REQATTENTION]                   NVARCHAR (255)   NOT NULL,
    [REQUISITIONER]                  NVARCHAR (40)    NOT NULL,
    [CONTRACTNUM_SA]                 NVARCHAR (60)    NOT NULL,
    [SEMCOPYPURCHASEORDERS]          INT              NOT NULL,
    [SEMSSICUSTOMER]                 NVARCHAR (40)    NOT NULL,
    [SEMINVENTREFID]                 NVARCHAR (20)    NOT NULL,
    [SEMCOMMITDATE]                  DATETIME         NOT NULL,
    [SEMDOCDATE]                     DATETIME         NOT NULL,
    [SEMREQUESTOREMAIL]              NVARCHAR (80)    NOT NULL,
    [SEMPUBLISHREQMANAGER]           INT              NOT NULL,
    [SEMREFERENCE]                   NVARCHAR (10)    NOT NULL,
    [SEMPREVIOUSTOTALAMOUNTOLD]      INT              NOT NULL,
    [SEMPREVIOUSTOTALAMOUNT]         NUMERIC (28, 12) NOT NULL,
    [SEMORDERTYPEID]                 NVARCHAR (20)    NOT NULL,
    [SEMBLANKRELEASEDPURCHORDERS]    INT              NOT NULL,
    [SEMBLANKTOTALAMOUNT]            NUMERIC (28, 12) NOT NULL,
    [SEMUNAPPROVEDBY]                NVARCHAR (100)   NOT NULL,
    [SEMORDEREDBY]                   NVARCHAR (40)    NOT NULL,
    [SEMPOFREIGHTTERMS]              NVARCHAR (30)    NOT NULL,
    [SEMINVENTREFTYPE]               INT              NOT NULL,
    [SEMNAME]                        NVARCHAR (100)   NOT NULL,
    [SEMPOSTINGDATE]                 DATETIME         NOT NULL,
    [SEMREQUESTOR]                   NVARCHAR (100)   NOT NULL,
    [SEMREQUISITIONID]               NVARCHAR (10)    NOT NULL,
    [SEMPOREQUISITIONSTATUS]         INT              NOT NULL,
    [SEMNEXTAPPROVER]                NVARCHAR (40)    NOT NULL,
    [SEMDISPLAYPURCHID]              NVARCHAR (20)    NOT NULL,
    [CREATEDDATETIME]                DATETIME         NOT NULL,
    [CREATEDBY]                      NVARCHAR (5)     NOT NULL,
    [DATAAREAID]                     NVARCHAR (4)     NOT NULL,
    [RECVERSION]                     INT              NOT NULL,
    [RECID]                          BIGINT           NOT NULL,
    [TRANSACTIONCODE]                NVARCHAR (30)    NOT NULL,
    [PORT]                           NVARCHAR (30)    NOT NULL,
    [TRANSPORT]                      NVARCHAR (30)    NOT NULL,
    [STATPROCID]                     NVARCHAR (10)    NOT NULL,
    [SEMISUPDATEDSINCEPURCHPOSTED]   INT              NOT NULL,
    [MODIFIEDDATETIME]               DATETIME         NULL,
    [MODIFIEDBY]                     NVARCHAR (5)     NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_PURCHID_PT]
    ON [ax].[PurchTable]([PURCHID] ASC);

