CREATE TABLE [ax].[SalesTable] (
    [SALESID]                        NVARCHAR (20)    NOT NULL,
    [SALESNAME]                      NVARCHAR (100)   NOT NULL,
    [RESERVATION]                    INT              NOT NULL,
    [CUSTACCOUNT]                    NVARCHAR (40)    NOT NULL,
    [INVOICEACCOUNT]                 NVARCHAR (40)    NOT NULL,
    [DELIVERYDATE]                   DATETIME         NOT NULL,
    [DELIVERYADDRESS]                NVARCHAR (250)   NOT NULL,
    [URL]                            NVARCHAR (255)   NOT NULL,
    [PURCHORDERFORMNUM]              NVARCHAR (50)    NOT NULL,
    [SALESTAKER]                     NVARCHAR (40)    NOT NULL,
    [FREIGHTSLIPTYPE]                INT              NOT NULL,
    [DOCUMENTSTATUS]                 INT              NOT NULL,
    [INTERCOMPANYORIGINALSALESID]    NVARCHAR (20)    NOT NULL,
    [CURRENCYCODE]                   NVARCHAR (3)     NOT NULL,
    [PAYMENT]                        NVARCHAR (30)    NOT NULL,
    [CASHDISC]                       NVARCHAR (30)    NOT NULL,
    [TAXGROUP]                       NVARCHAR (30)    NOT NULL,
    [LINEDISC]                       NVARCHAR (30)    NOT NULL,
    [CUSTGROUP]                      NVARCHAR (30)    NOT NULL,
    [DISCPERCENT]                    NUMERIC (28, 12) NOT NULL,
    [INTERCOMPANYORIGINALCUSTACCO22] NVARCHAR (40)    NOT NULL,
    [DIMENSION]                      NVARCHAR (30)    NOT NULL,
    [DIMENSION2_]                    NVARCHAR (30)    NOT NULL,
    [DIMENSION3_]                    NVARCHAR (30)    NOT NULL,
    [PRICEGROUPID]                   NVARCHAR (30)    NOT NULL,
    [MULTILINEDISC]                  NVARCHAR (30)    NOT NULL,
    [ENDDISC]                        NVARCHAR (30)    NOT NULL,
    [CUSTOMERREF]                    NVARCHAR (100)   NOT NULL,
    [DLVTERM]                        NVARCHAR (30)    NOT NULL,
    [DLVMODE]                        NVARCHAR (30)    NOT NULL,
    [PURCHID]                        NVARCHAR (20)    NOT NULL,
    [SALESSTATUS]                    INT              NOT NULL,
    [MARKUPGROUP]                    NVARCHAR (30)    NOT NULL,
    [SALESTYPE]                      INT              NOT NULL,
    [SALESPOOLID]                    NVARCHAR (30)    NOT NULL,
    [POSTINGPROFILE]                 NVARCHAR (10)    NOT NULL,
    [DELIVERYZIPCODE]                NVARCHAR (10)    NOT NULL,
    [DELIVERYCOUNTY]                 NVARCHAR (30)    NOT NULL,
    [DELIVERYCOUNTRYREGIONID]        NVARCHAR (30)    NOT NULL,
    [SETTLEVOUCHER]                  INT              NOT NULL,
    [DELIVERYSTATE]                  NVARCHAR (30)    NOT NULL,
    [DELIVERYNAME]                   NVARCHAR (100)   NOT NULL,
    [ONETIMECUSTOMER]                INT              NOT NULL,
    [COVSTATUS]                      INT              NOT NULL,
    [PAYMENTSCHED]                   NVARCHAR (30)    NOT NULL,
    [EMAIL]                          NVARCHAR (80)    NOT NULL,
    [FREIGHTZONE]                    NVARCHAR (30)    NOT NULL,
    [RETURNITEMNUM]                  NVARCHAR (15)    NOT NULL,
    [CASHDISCPERCENT]                NUMERIC (28, 12) NOT NULL,
    [CONTACTPERSONID]                NVARCHAR (40)    NOT NULL,
    [DEADLINE]                       DATETIME         NOT NULL,
    [PROJID]                         NVARCHAR (10)    NOT NULL,
    [INVENTLOCATIONID]               NVARCHAR (30)    NOT NULL,
    [ADDRESSREFTABLEID]              INT              NOT NULL,
    [VATNUM]                         NVARCHAR (20)    NOT NULL,
    [INCLTAX]                        INT              NOT NULL,
    [EINVOICELINESPEC]               INT              NOT NULL,
    [NUMBERSEQUENCEGROUP]            NVARCHAR (30)    NOT NULL,
    [FIXEDEXCHRATE]                  NUMERIC (28, 12) NOT NULL,
    [LANGUAGEID]                     NVARCHAR (7)     NOT NULL,
    [AUTOSUMMARYMODULETYPE]          INT              NOT NULL,
    [SALESORIGINID]                  NVARCHAR (30)    NOT NULL,
    [ESTIMATE]                       NUMERIC (28, 12) NOT NULL,
    [PAYMMODE]                       NVARCHAR (30)    NOT NULL,
    [PAYMSPEC]                       NVARCHAR (30)    NOT NULL,
    [FIXEDDUEDATE]                   DATETIME         NOT NULL,
    [DELIVERYCITY]                   NVARCHAR (100)   NOT NULL,
    [DELIVERYSTREET]                 NVARCHAR (250)   NOT NULL,
    [EXPORTREASON]                   NVARCHAR (100)   NOT NULL,
    [DLVREASON]                      NVARCHAR (30)    NOT NULL,
    [QUOTATIONID]                    NVARCHAR (20)    NOT NULL,
    [RECEIPTDATEREQUESTED]           DATETIME         NOT NULL,
    [RECEIPTDATECONFIRMED]           DATETIME         NOT NULL,
    [SHIPPINGDATEREQUESTED]          DATETIME         NOT NULL,
    [SHIPPINGDATECONFIRMED]          DATETIME         NOT NULL,
    [EINVOICEACCOUNTCODE]            NVARCHAR (35)    NOT NULL,
    [ADDRESSREFRECID]                BIGINT           NOT NULL,
    [CUSTINVOICEID]                  NVARCHAR (20)    NOT NULL,
    [INVENTSITEID]                   NVARCHAR (10)    NOT NULL,
    [CREDITCARDCUSTREFID]            BIGINT           NOT NULL,
    [SHIPCARRIERACCOUNT]             NVARCHAR (25)    NOT NULL,
    [SHIPCARRIERID]                  NVARCHAR (10)    NOT NULL,
    [SHIPCARRIERFUELSURCHARGE]       INT              NOT NULL,
    [SHIPCARRIERBLINDSHIPMENT]       INT              NOT NULL,
    [CREDITCARDPROCESSORTRANSACT140] NVARCHAR (48)    NOT NULL,
    [SHIPCARRIERDELIVERYCONTACT]     NVARCHAR (100)   NOT NULL,
    [CREDITCARDAPPROVALAMOUNT]       NUMERIC (28, 12) NOT NULL,
    [CREDITCARDAUTHORIZATION]        NVARCHAR (20)    NOT NULL,
    [RETURNDEADLINE]                 DATETIME         NOT NULL,
    [RETURNREPLACEMENTID]            NVARCHAR (20)    NOT NULL,
    [RETURNSTATUS]                   INT              NOT NULL,
    [RETURNREASONCODEID]             NVARCHAR (10)    NOT NULL,
    [CREDITCARDAUTHORIZATIONERROR]   INT              NOT NULL,
    [SHIPCARRIERACCOUNTCODE]         NVARCHAR (20)    NOT NULL,
    [RETURNREPLACEMENTCREATED]       INT              NOT NULL,
    [SHIPCARRIERDLVTYPE]             INT              NOT NULL,
    [ATPINCLPLANNEDORDERS]           INT              NOT NULL,
    [ATPTIMEFENCE]                   INT              NOT NULL,
    [DELIVERYDATECONTROLTYPE]        INT              NOT NULL,
    [SHIPCARRIEREXPEDITEDSHIPMENT]   INT              NOT NULL,
    [SHIPCARRIERRESIDENTIAL]         INT              NOT NULL,
    [SALESRESPONSIBLE]               NVARCHAR (40)    NOT NULL,
    [SALESUNITID]                    NVARCHAR (20)    NOT NULL,
    [SMMSALESAMOUNTTOTAL]            NUMERIC (28, 12) NOT NULL,
    [SMMCAMPAIGNID]                  NVARCHAR (10)    NOT NULL,
    [SEMCONFIRMEDOK]                 INT              NOT NULL,
    [SEMENDCUST]                     NVARCHAR (40)    NOT NULL,
    [SEMUSCUSTACCOUNT]               NVARCHAR (40)    NOT NULL,
    [SEMSOLDTOCUST]                  NVARCHAR (40)    NOT NULL,
    [SEMSHIPTOLOCATION]              NVARCHAR (10)    NOT NULL,
    [SEMDELIVERYTRACKING]            NVARCHAR (60)    NOT NULL,
    [SEMUSCUSTNAME]                  NVARCHAR (100)   NOT NULL,
    [SEMCREATEDDATE]                 DATETIME         NOT NULL,
    [SEMCREATEDDATETZID]             INT              NOT NULL,
    [DMMDPAENABLED]                  INT              NOT NULL,
    [DMMCMACCOUNT]                   NVARCHAR (40)    NOT NULL,
    [DMMDPAID]                       NVARCHAR (15)    NOT NULL,
    [DMMDISTRIBUTOR]                 INT              NOT NULL,
    [MODIFIEDBY]                     NVARCHAR (5)     NOT NULL,
    [CREATEDDATETIME]                DATETIME         NOT NULL,
    [CREATEDBY]                      NVARCHAR (5)     NOT NULL,
    [DATAAREAID]                     NVARCHAR (4)     NOT NULL,
    [RECVERSION]                     INT              NOT NULL,
    [RECID]                          BIGINT           NOT NULL,
    [LISTCODE]                       INT              NOT NULL,
    [TRANSACTIONCODE]                NVARCHAR (30)    NOT NULL,
    [PORT]                           NVARCHAR (30)    NOT NULL,
    [TRANSPORT]                      NVARCHAR (30)    NOT NULL,
    [STATPROCID]                     NVARCHAR (10)    NOT NULL,
    [SEMBASEDISC]                    NUMERIC (28, 12) NOT NULL,
    [SEMVOLDISC]                     NUMERIC (28, 12) NOT NULL,
    [SEMCSATDISC]                    NUMERIC (28, 12) NOT NULL,
    [SEMVPADISC]                     NUMERIC (28, 12) NOT NULL,
    [SEMDISCTYPE]                    NVARCHAR (10)    NOT NULL,
    [SEMCONCESDISC]                  NUMERIC (28, 12) NOT NULL,
    [SEMINTDEMODISC]                 NUMERIC (28, 12) NOT NULL,
    [SEMNEWPART]                     NUMERIC (28, 12) NOT NULL,
    [SEMDOLLARDISC]                  INT              NOT NULL,
    [DELIVERYCOUNTRY]                NVARCHAR (30)    NOT NULL,
    [ORIGINATINGCUSTOMER]            NVARCHAR (40)    NOT NULL,
    [SEMPOSTINGORDERTYPE]            NVARCHAR (10)    NOT NULL,
    [SEMSUPPCOTERMDATE]              DATETIME         NOT NULL,
    [SEMFINANCE]                     NVARCHAR (15)    NOT NULL,
    [SEMMAPACCT]                     NVARCHAR (10)    NOT NULL,
    [SEMSUPPRENEWDATE]               DATETIME         NOT NULL,
    [SEMSUPPID]                      NVARCHAR (15)    NOT NULL,
    [SEMQMSID]                       NVARCHAR (25)    NOT NULL,
    [SEMCOOP]                        NVARCHAR (12)    NOT NULL,
    [FSONHOLD]                       INT              NOT NULL,
    [FSONHOLDSAVESALESSTATUS]        INT              NOT NULL,
    [SEMQMSORDER]                    INT              NOT NULL,
    [ORDERPROCESSINGOPTION]          NVARCHAR (25)    NOT NULL,
    [SEMRESELLERNAME]                NVARCHAR (100)   NOT NULL,
    [SEMRESELLERACCT]                NVARCHAR (40)    NOT NULL,
    [MSINVOICEID]                    NVARCHAR (60)    NOT NULL,
    [MODIFIEDDATETIME]               DATETIME         NOT NULL,
    [DMMEXCLUDEDISTI]                INT              NOT NULL,
    [DMMORIGDISTISO]                 NVARCHAR (20)    NOT NULL,
    [STTRAININGCOUPON]               NVARCHAR (100)   NOT NULL,
    [PURCHORDERFORMID]               NVARCHAR (10)    NOT NULL,
    [STSUPPORTPROGRAM]               NVARCHAR (66)    NOT NULL,
    [STEDIMEMOLINES]                 NVARCHAR (300)   NOT NULL,
    [STEDIEUCONTACTEMAIL]            NVARCHAR (50)    NOT NULL,
    [STEDIEUCONTACTPHONE]            NVARCHAR (50)    NOT NULL,
    [STEDIEUCONTACTNAME]             NVARCHAR (50)    NOT NULL,
    [STEDIPARENTNAME]                NVARCHAR (100)   NOT NULL,
    [STSERVICEREQUESTNUM]            NVARCHAR (30)    NOT NULL,
    [STEDIORDERMODIFIED]             INT              NOT NULL,
    [STCONFIRMRETURNNUMBER]          INT              NOT NULL,
    [STSIEBELSERVICEREQUESTNUM]      NVARCHAR (20)    NOT NULL,
    [STRETURNORDERSTATUS]            INT              NOT NULL,
    [STCONTACTNAME]                  NVARCHAR (80)    NOT NULL,
    [STRMAFLAGGED]                   INT              NOT NULL,
    [STSHIPTOZIPCODE]                NVARCHAR (10)    NOT NULL,
    [STSHIPTOSTREET]                 NVARCHAR (250)   NOT NULL,
    [STSHIPTOCITY]                   NVARCHAR (100)   NOT NULL,
    [STSHIPTOCOUNTRYREGIONID]        NVARCHAR (30)    NOT NULL,
    [STSHIPTONAME]                   NVARCHAR (100)   NOT NULL,
    [STSHIPTOSTATE]                  NVARCHAR (30)    NOT NULL,
    [STSBADISCOUNT]                  NVARCHAR (50)    NOT NULL,
    [STEDIMEMOLINESEXT]              NVARCHAR (300)   NOT NULL,
    [STEXEMPTIONTYPE]                INT              NOT NULL,
    [CloudInvoiceId]                 AS               (case when isnumeric([PURCHORDERFORMNUM])=(1) AND len([PURCHORDERFORMNUM])<(8) then CONVERT([int],replace(replace([PURCHORDERFORMNUM],',',''),'.',''),(0)) else (0) end),
    [STRENEWAL]                      NVARCHAR (10)    NULL,
    [STVPNCONCENTRATORSENT]          INT              NULL,
    [STSIPIRATORSENT]                INT              NULL,
    [STDIRCCADVAPPMOBSENT]           INT              NULL,
    [STVPNCONCENTRATORREQUIRED]      INT              NULL,
    [STSIPIRATORREQUIRED]            INT              NULL,
    [STDIRCCADVAPPMOBREQUIRED]       INT              NULL,
    [STVPNCONCENTRATORREADY]         INT              NULL,
    [STSIPIRATORREADY]               INT              NULL,
    [STDIRCCADVAPPMOBREADY]          INT              NULL,
    [STCLOUDSHIPPINGCHARGE]          NUMERIC (28, 12) NULL,
    [STENDUSERPO]                    NVARCHAR (1)     NULL,
    [STVERTICALMARKET]               NVARCHAR (5)     NULL
);


GO
CREATE CLUSTERED INDEX [RecId_idx]
    ON [ax].[SalesTable]([RECID] ASC);


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-SalesId]
    ON [ax].[SalesTable]([SALESID] ASC);

